// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: proto/enums/accountType.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountType int32

const (
	AccountType_Unspecified AccountType = 0
	AccountType_Regular     AccountType = 1 // Обычный счет
	AccountType_Expense     AccountType = 2 // Счет расходов
	AccountType_Debt        AccountType = 3 // Долговой счет
	AccountType_Earnings    AccountType = 4 // Счет доходов
	AccountType_Balancing   AccountType = 5 // Балансировочный счет
)

// Enum value maps for AccountType.
var (
	AccountType_name = map[int32]string{
		0: "Unspecified",
		1: "Regular",
		2: "Expense",
		3: "Debt",
		4: "Earnings",
		5: "Balancing",
	}
	AccountType_value = map[string]int32{
		"Unspecified": 0,
		"Regular":     1,
		"Expense":     2,
		"Debt":        3,
		"Earnings":    4,
		"Balancing":   5,
	}
)

func (x AccountType) Enum() *AccountType {
	p := new(AccountType)
	*p = x
	return p
}

func (x AccountType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccountType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_enums_accountType_proto_enumTypes[0].Descriptor()
}

func (AccountType) Type() protoreflect.EnumType {
	return &file_proto_enums_accountType_proto_enumTypes[0]
}

func (x AccountType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccountType.Descriptor instead.
func (AccountType) EnumDescriptor() ([]byte, []int) {
	return file_proto_enums_accountType_proto_rawDescGZIP(), []int{0}
}

var File_proto_enums_accountType_proto protoreflect.FileDescriptor

const file_proto_enums_accountType_proto_rawDesc = "" +
	"\n" +
	"\x1dproto/enums/accountType.proto\x12\vaccountType*_\n" +
	"\vAccountType\x12\x0f\n" +
	"\vUnspecified\x10\x00\x12\v\n" +
	"\aRegular\x10\x01\x12\v\n" +
	"\aExpense\x10\x02\x12\b\n" +
	"\x04Debt\x10\x03\x12\f\n" +
	"\bEarnings\x10\x04\x12\r\n" +
	"\tBalancing\x10\x05B\bZ\x06/protob\x06proto3"

var (
	file_proto_enums_accountType_proto_rawDescOnce sync.Once
	file_proto_enums_accountType_proto_rawDescData []byte
)

func file_proto_enums_accountType_proto_rawDescGZIP() []byte {
	file_proto_enums_accountType_proto_rawDescOnce.Do(func() {
		file_proto_enums_accountType_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_enums_accountType_proto_rawDesc), len(file_proto_enums_accountType_proto_rawDesc)))
	})
	return file_proto_enums_accountType_proto_rawDescData
}

var file_proto_enums_accountType_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_enums_accountType_proto_goTypes = []any{
	(AccountType)(0), // 0: accountType.AccountType
}
var file_proto_enums_accountType_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_enums_accountType_proto_init() }
func file_proto_enums_accountType_proto_init() {
	if File_proto_enums_accountType_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_enums_accountType_proto_rawDesc), len(file_proto_enums_accountType_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_enums_accountType_proto_goTypes,
		DependencyIndexes: file_proto_enums_accountType_proto_depIdxs,
		EnumInfos:         file_proto_enums_accountType_proto_enumTypes,
	}.Build()
	File_proto_enums_accountType_proto = out.File
	file_proto_enums_accountType_proto_goTypes = nil
	file_proto_enums_accountType_proto_depIdxs = nil
}
