// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: proto/account/account-endpoint.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountBudget struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Amount         *float64               `protobuf:"fixed64,1,opt,name=amount,proto3,oneof" json:"amount,omitempty"`                // Сумма бюджета
	DaysOffset     *int32                 `protobuf:"varint,2,opt,name=daysOffset,proto3,oneof" json:"daysOffset,omitempty"`         // Смещение в днях
	FixedSum       *float64               `protobuf:"fixed64,3,opt,name=fixedSum,proto3,oneof" json:"fixedSum,omitempty"`            // Фиксированная сумма
	GradualFilling *bool                  `protobuf:"varint,4,opt,name=gradualFilling,proto3,oneof" json:"gradualFilling,omitempty"` // Постепенное пополнение
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AccountBudget) Reset() {
	*x = AccountBudget{}
	mi := &file_proto_account_account_endpoint_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountBudget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountBudget) ProtoMessage() {}

func (x *AccountBudget) ProtoReflect() protoreflect.Message {
	mi := &file_proto_account_account_endpoint_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountBudget.ProtoReflect.Descriptor instead.
func (*AccountBudget) Descriptor() ([]byte, []int) {
	return file_proto_account_account_endpoint_proto_rawDescGZIP(), []int{0}
}

func (x *AccountBudget) GetAmount() float64 {
	if x != nil && x.Amount != nil {
		return *x.Amount
	}
	return 0
}

func (x *AccountBudget) GetDaysOffset() int32 {
	if x != nil && x.DaysOffset != nil {
		return *x.DaysOffset
	}
	return 0
}

func (x *AccountBudget) GetFixedSum() float64 {
	if x != nil && x.FixedSum != nil {
		return *x.FixedSum
	}
	return 0
}

func (x *AccountBudget) GetGradualFilling() bool {
	if x != nil && x.GradualFilling != nil {
		return *x.GradualFilling
	}
	return false
}

type Account struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                   // Идентификатор счета
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                               // Название счета
	Type               AccountType            `protobuf:"varint,3,opt,name=type,proto3,enum=accountType.AccountType" json:"type,omitempty"` // Тип счета
	Currency           string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`                       // Валюта счета
	Remainder          float64                `protobuf:"fixed64,5,opt,name=remainder,proto3" json:"remainder,omitempty"`                   // Остаток средств на счету
	Visible            bool                   `protobuf:"varint,6,opt,name=visible,proto3" json:"visible,omitempty"`                        // Видимость счета
	AccountingInCharts bool                   `protobuf:"varint,7,opt,name=accountingInCharts,proto3" json:"accountingInCharts,omitempty"`  // Учитывать ли счет в графиках
	AccountingInHeader bool                   `protobuf:"varint,8,opt,name=accountingInHeader,proto3" json:"accountingInHeader,omitempty"`  // Будет ли счет учитываться в шапке
	AccountGroupID     int32                  `protobuf:"varint,9,opt,name=accountGroupID,proto3" json:"accountGroupID,omitempty"`          // Идентификатор группы счета
	ParentAccountID    int32                  `protobuf:"varint,10,opt,name=parentAccountID,proto3" json:"parentAccountID,omitempty"`       // Идентификатор родительского аккаунта
	IsParent           bool                   `protobuf:"varint,11,opt,name=isParent,proto3" json:"isParent,omitempty"`                     // Является ли счет родительским
	IconID             int32                  `protobuf:"varint,12,opt,name=iconID,proto3" json:"iconID,omitempty"`                         // Идентификатор иконки
	SerialNumber       int32                  `protobuf:"varint,13,opt,name=serialNumber,proto3" json:"serialNumber,omitempty"`             // Порядковый номер счета
	CreatedByUserID    int32                  `protobuf:"varint,14,opt,name=createdByUserID,proto3" json:"createdByUserID,omitempty"`       // Идентификатор пользователя, создавшего счет
	DatetimeCreate     *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=datetimeCreate,proto3" json:"datetimeCreate,omitempty"`          // Дата и время создания счета
	Budget             *AccountBudget         `protobuf:"bytes,16,opt,name=budget,proto3,oneof" json:"budget,omitempty"`                    // Бюджет
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_proto_account_account_endpoint_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_proto_account_account_endpoint_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_proto_account_account_endpoint_proto_rawDescGZIP(), []int{1}
}

func (x *Account) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Account) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Account) GetType() AccountType {
	if x != nil {
		return x.Type
	}
	return AccountType_Unspecified
}

func (x *Account) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Account) GetRemainder() float64 {
	if x != nil {
		return x.Remainder
	}
	return 0
}

func (x *Account) GetVisible() bool {
	if x != nil {
		return x.Visible
	}
	return false
}

func (x *Account) GetAccountingInCharts() bool {
	if x != nil {
		return x.AccountingInCharts
	}
	return false
}

func (x *Account) GetAccountingInHeader() bool {
	if x != nil {
		return x.AccountingInHeader
	}
	return false
}

func (x *Account) GetAccountGroupID() int32 {
	if x != nil {
		return x.AccountGroupID
	}
	return 0
}

func (x *Account) GetParentAccountID() int32 {
	if x != nil {
		return x.ParentAccountID
	}
	return 0
}

func (x *Account) GetIsParent() bool {
	if x != nil {
		return x.IsParent
	}
	return false
}

func (x *Account) GetIconID() int32 {
	if x != nil {
		return x.IconID
	}
	return 0
}

func (x *Account) GetSerialNumber() int32 {
	if x != nil {
		return x.SerialNumber
	}
	return 0
}

func (x *Account) GetCreatedByUserID() int32 {
	if x != nil {
		return x.CreatedByUserID
	}
	return 0
}

func (x *Account) GetDatetimeCreate() *timestamppb.Timestamp {
	if x != nil {
		return x.DatetimeCreate
	}
	return nil
}

func (x *Account) GetBudget() *AccountBudget {
	if x != nil {
		return x.Budget
	}
	return nil
}

type GetAccountsRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AccessToken        string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`                       // Токен доступа
	AccountGroupIDs    []int32                `protobuf:"varint,2,rep,packed,name=accountGroupIDs,proto3" json:"accountGroupIDs,omitempty"`       // Идентификаторы групп счетов
	AccountingInCharts *bool                  `protobuf:"varint,3,opt,name=accountingInCharts,proto3,oneof" json:"accountingInCharts,omitempty"`  // Учитывать ли счет в графиках
	AccountingInHeader *bool                  `protobuf:"varint,4,opt,name=accountingInHeader,proto3,oneof" json:"accountingInHeader,omitempty"`  // Учитывать ли счет в шапке
	DateFrom           *string                `protobuf:"bytes,5,opt,name=dateFrom,proto3,oneof" json:"dateFrom,omitempty"`                       // Дата начала выборки
	DateTo             *string                `protobuf:"bytes,6,opt,name=dateTo,proto3,oneof" json:"dateTo,omitempty"`                           // Дата конца выборки
	Type               *AccountType           `protobuf:"varint,7,opt,name=type,proto3,enum=accountType.AccountType,oneof" json:"type,omitempty"` // Тип счета
	Visible            *bool                  `protobuf:"varint,8,opt,name=visible,proto3,oneof" json:"visible,omitempty"`                        // Видимость счета
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetAccountsRequest) Reset() {
	*x = GetAccountsRequest{}
	mi := &file_proto_account_account_endpoint_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountsRequest) ProtoMessage() {}

func (x *GetAccountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_account_account_endpoint_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountsRequest.ProtoReflect.Descriptor instead.
func (*GetAccountsRequest) Descriptor() ([]byte, []int) {
	return file_proto_account_account_endpoint_proto_rawDescGZIP(), []int{2}
}

func (x *GetAccountsRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *GetAccountsRequest) GetAccountGroupIDs() []int32 {
	if x != nil {
		return x.AccountGroupIDs
	}
	return nil
}

func (x *GetAccountsRequest) GetAccountingInCharts() bool {
	if x != nil && x.AccountingInCharts != nil {
		return *x.AccountingInCharts
	}
	return false
}

func (x *GetAccountsRequest) GetAccountingInHeader() bool {
	if x != nil && x.AccountingInHeader != nil {
		return *x.AccountingInHeader
	}
	return false
}

func (x *GetAccountsRequest) GetDateFrom() string {
	if x != nil && x.DateFrom != nil {
		return *x.DateFrom
	}
	return ""
}

func (x *GetAccountsRequest) GetDateTo() string {
	if x != nil && x.DateTo != nil {
		return *x.DateTo
	}
	return ""
}

func (x *GetAccountsRequest) GetType() AccountType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return AccountType_Unspecified
}

func (x *GetAccountsRequest) GetVisible() bool {
	if x != nil && x.Visible != nil {
		return *x.Visible
	}
	return false
}

type GetAccountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"` // Объект ошибки
	Accounts      []*Account             `protobuf:"bytes,2,rep,name=accounts,proto3" json:"accounts,omitempty"` // Список счетов
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountsResponse) Reset() {
	*x = GetAccountsResponse{}
	mi := &file_proto_account_account_endpoint_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountsResponse) ProtoMessage() {}

func (x *GetAccountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_account_account_endpoint_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountsResponse.ProtoReflect.Descriptor instead.
func (*GetAccountsResponse) Descriptor() ([]byte, []int) {
	return file_proto_account_account_endpoint_proto_rawDescGZIP(), []int{3}
}

func (x *GetAccountsResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *GetAccountsResponse) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

type CreateAccountRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AccessToken        string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`                 // Токен доступа
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                               // Название счета
	Type               AccountType            `protobuf:"varint,3,opt,name=type,proto3,enum=accountType.AccountType" json:"type,omitempty"` // Тип счета
	Currency           string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`                       // Валюта счета
	AccountGroupID     int32                  `protobuf:"varint,5,opt,name=accountGroupID,proto3" json:"accountGroupID,omitempty"`          // Группа счета
	AccountingInCharts bool                   `protobuf:"varint,6,opt,name=accountingInCharts,proto3" json:"accountingInCharts,omitempty"`  // Учитывать ли счет в графиках
	AccountingInHeader bool                   `protobuf:"varint,7,opt,name=accountingInHeader,proto3" json:"accountingInHeader,omitempty"`  // Подсчет суммы счета в статистике
	IconID             int32                  `protobuf:"varint,8,opt,name=iconID,proto3" json:"iconID,omitempty"`                          // Идентификатор иконки
	IsParent           bool                   `protobuf:"varint,9,opt,name=isParent,proto3" json:"isParent,omitempty"`                      // Является ли счет родительским
	DatetimeCreate     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=datetimeCreate,proto3" json:"datetimeCreate,omitempty"`          // Дата создания счета
	ParentAccountID    *int32                 `protobuf:"varint,11,opt,name=parentAccountID,proto3,oneof" json:"parentAccountID,omitempty"` // Идентификатор родительского счета
	Remainder          *float64               `protobuf:"fixed64,12,opt,name=remainder,proto3,oneof" json:"remainder,omitempty"`            // Остаток средств на счету
	Budget             *AccountBudget         `protobuf:"bytes,13,opt,name=budget,proto3,oneof" json:"budget,omitempty"`                    // Бюджет
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_proto_account_account_endpoint_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_account_account_endpoint_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_account_account_endpoint_proto_rawDescGZIP(), []int{4}
}

func (x *CreateAccountRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *CreateAccountRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAccountRequest) GetType() AccountType {
	if x != nil {
		return x.Type
	}
	return AccountType_Unspecified
}

func (x *CreateAccountRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CreateAccountRequest) GetAccountGroupID() int32 {
	if x != nil {
		return x.AccountGroupID
	}
	return 0
}

func (x *CreateAccountRequest) GetAccountingInCharts() bool {
	if x != nil {
		return x.AccountingInCharts
	}
	return false
}

func (x *CreateAccountRequest) GetAccountingInHeader() bool {
	if x != nil {
		return x.AccountingInHeader
	}
	return false
}

func (x *CreateAccountRequest) GetIconID() int32 {
	if x != nil {
		return x.IconID
	}
	return 0
}

func (x *CreateAccountRequest) GetIsParent() bool {
	if x != nil {
		return x.IsParent
	}
	return false
}

func (x *CreateAccountRequest) GetDatetimeCreate() *timestamppb.Timestamp {
	if x != nil {
		return x.DatetimeCreate
	}
	return nil
}

func (x *CreateAccountRequest) GetParentAccountID() int32 {
	if x != nil && x.ParentAccountID != nil {
		return *x.ParentAccountID
	}
	return 0
}

func (x *CreateAccountRequest) GetRemainder() float64 {
	if x != nil && x.Remainder != nil {
		return *x.Remainder
	}
	return 0
}

func (x *CreateAccountRequest) GetBudget() *AccountBudget {
	if x != nil {
		return x.Budget
	}
	return nil
}

type CreateAccountResponse struct {
	state                        protoimpl.MessageState `protogen:"open.v1"`
	Error                        *Error                 `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`                                                // Объект ошибки
	Id                           []byte                 `protobuf:"bytes,2,opt,name=id,proto3,oneof" json:"id,omitempty"`                                                      // Идентификатор созданного счета
	SerialNumber                 *int32                 `protobuf:"varint,3,opt,name=serialNumber,proto3,oneof" json:"serialNumber,omitempty"`                                 // Порядковый номер счета
	BalancingAccountID           *int32                 `protobuf:"varint,4,opt,name=balancingAccountID,proto3,oneof" json:"balancingAccountID,omitempty"`                     // Идентификатор балансировочного счета
	BalancingAccountSerialNumber *int32                 `protobuf:"varint,5,opt,name=balancingAccountSerialNumber,proto3,oneof" json:"balancingAccountSerialNumber,omitempty"` // Порядковый номер балансировочного счета
	BalancingTransactionID       *int32                 `protobuf:"varint,6,opt,name=balancingTransactionID,proto3,oneof" json:"balancingTransactionID,omitempty"`             // Идентификатор транзакции балансировки
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *CreateAccountResponse) Reset() {
	*x = CreateAccountResponse{}
	mi := &file_proto_account_account_endpoint_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountResponse) ProtoMessage() {}

func (x *CreateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_account_account_endpoint_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return file_proto_account_account_endpoint_proto_rawDescGZIP(), []int{5}
}

func (x *CreateAccountResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *CreateAccountResponse) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *CreateAccountResponse) GetSerialNumber() int32 {
	if x != nil && x.SerialNumber != nil {
		return *x.SerialNumber
	}
	return 0
}

func (x *CreateAccountResponse) GetBalancingAccountID() int32 {
	if x != nil && x.BalancingAccountID != nil {
		return *x.BalancingAccountID
	}
	return 0
}

func (x *CreateAccountResponse) GetBalancingAccountSerialNumber() int32 {
	if x != nil && x.BalancingAccountSerialNumber != nil {
		return *x.BalancingAccountSerialNumber
	}
	return 0
}

func (x *CreateAccountResponse) GetBalancingTransactionID() int32 {
	if x != nil && x.BalancingTransactionID != nil {
		return *x.BalancingTransactionID
	}
	return 0
}

type UpdateAccountRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AccessToken        string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`                      // Токен доступа
	Id                 []byte                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`                                        // Идентификатор счета
	Name               *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`                              // Название счета
	AccountingInCharts *bool                  `protobuf:"varint,4,opt,name=accountingInCharts,proto3,oneof" json:"accountingInCharts,omitempty"` // Будет ли счет учитываться в графиках
	AccountingInHeader *bool                  `protobuf:"varint,5,opt,name=accountingInHeader,proto3,oneof" json:"accountingInHeader,omitempty"` // Будет ли счет учитываться в статистике
	CurrencyCode       *string                `protobuf:"bytes,6,opt,name=currencyCode,proto3,oneof" json:"currencyCode,omitempty"`              // Валюта счета
	IconID             *int32                 `protobuf:"varint,7,opt,name=iconID,proto3,oneof" json:"iconID,omitempty"`                         // Идентификатор иконки
	ParentAccountID    *int32                 `protobuf:"varint,8,opt,name=parentAccountID,proto3,oneof" json:"parentAccountID,omitempty"`       // Идентификатор родительского счета
	Remainder          *float64               `protobuf:"fixed64,9,opt,name=remainder,proto3,oneof" json:"remainder,omitempty"`                  // Остаток средств на счету
	SerialNumber       *int32                 `protobuf:"varint,10,opt,name=serialNumber,proto3,oneof" json:"serialNumber,omitempty"`            // Порядковый номер счета
	Visible            *bool                  `protobuf:"varint,11,opt,name=visible,proto3,oneof" json:"visible,omitempty"`                      // Видимость счета
	Budget             *AccountBudget         `protobuf:"bytes,12,opt,name=budget,proto3,oneof" json:"budget,omitempty"`                         // Месячный бюджет
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdateAccountRequest) Reset() {
	*x = UpdateAccountRequest{}
	mi := &file_proto_account_account_endpoint_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountRequest) ProtoMessage() {}

func (x *UpdateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_account_account_endpoint_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountRequest.ProtoReflect.Descriptor instead.
func (*UpdateAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_account_account_endpoint_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateAccountRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *UpdateAccountRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *UpdateAccountRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateAccountRequest) GetAccountingInCharts() bool {
	if x != nil && x.AccountingInCharts != nil {
		return *x.AccountingInCharts
	}
	return false
}

func (x *UpdateAccountRequest) GetAccountingInHeader() bool {
	if x != nil && x.AccountingInHeader != nil {
		return *x.AccountingInHeader
	}
	return false
}

func (x *UpdateAccountRequest) GetCurrencyCode() string {
	if x != nil && x.CurrencyCode != nil {
		return *x.CurrencyCode
	}
	return ""
}

func (x *UpdateAccountRequest) GetIconID() int32 {
	if x != nil && x.IconID != nil {
		return *x.IconID
	}
	return 0
}

func (x *UpdateAccountRequest) GetParentAccountID() int32 {
	if x != nil && x.ParentAccountID != nil {
		return *x.ParentAccountID
	}
	return 0
}

func (x *UpdateAccountRequest) GetRemainder() float64 {
	if x != nil && x.Remainder != nil {
		return *x.Remainder
	}
	return 0
}

func (x *UpdateAccountRequest) GetSerialNumber() int32 {
	if x != nil && x.SerialNumber != nil {
		return *x.SerialNumber
	}
	return 0
}

func (x *UpdateAccountRequest) GetVisible() bool {
	if x != nil && x.Visible != nil {
		return *x.Visible
	}
	return false
}

func (x *UpdateAccountRequest) GetBudget() *AccountBudget {
	if x != nil {
		return x.Budget
	}
	return nil
}

type UpdateAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"` // Объект ошибки
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAccountResponse) Reset() {
	*x = UpdateAccountResponse{}
	mi := &file_proto_account_account_endpoint_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAccountResponse) ProtoMessage() {}

func (x *UpdateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_account_account_endpoint_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAccountResponse.ProtoReflect.Descriptor instead.
func (*UpdateAccountResponse) Descriptor() ([]byte, []int) {
	return file_proto_account_account_endpoint_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateAccountResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type DeleteAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"` // Токен доступа
	Id            []byte                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`                   // Идентификатор счета
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountRequest) Reset() {
	*x = DeleteAccountRequest{}
	mi := &file_proto_account_account_endpoint_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountRequest) ProtoMessage() {}

func (x *DeleteAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_account_account_endpoint_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountRequest.ProtoReflect.Descriptor instead.
func (*DeleteAccountRequest) Descriptor() ([]byte, []int) {
	return file_proto_account_account_endpoint_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteAccountRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *DeleteAccountRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

type DeleteAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"` // Объект ошибки
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAccountResponse) Reset() {
	*x = DeleteAccountResponse{}
	mi := &file_proto_account_account_endpoint_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAccountResponse) ProtoMessage() {}

func (x *DeleteAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_account_account_endpoint_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAccountResponse.ProtoReflect.Descriptor instead.
func (*DeleteAccountResponse) Descriptor() ([]byte, []int) {
	return file_proto_account_account_endpoint_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteAccountResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_proto_account_account_endpoint_proto protoreflect.FileDescriptor

const file_proto_account_account_endpoint_proto_rawDesc = "" +
	"\n" +
	"$proto/account/account-endpoint.proto\x12\aaccount\x1a\x17proto/error/error.proto\x1a\x1dproto/enums/accountType.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd9\x01\n" +
	"\rAccountBudget\x12\x1b\n" +
	"\x06amount\x18\x01 \x01(\x01H\x00R\x06amount\x88\x01\x01\x12#\n" +
	"\n" +
	"daysOffset\x18\x02 \x01(\x05H\x01R\n" +
	"daysOffset\x88\x01\x01\x12\x1f\n" +
	"\bfixedSum\x18\x03 \x01(\x01H\x02R\bfixedSum\x88\x01\x01\x12+\n" +
	"\x0egradualFilling\x18\x04 \x01(\bH\x03R\x0egradualFilling\x88\x01\x01B\t\n" +
	"\a_amountB\r\n" +
	"\v_daysOffsetB\v\n" +
	"\t_fixedSumB\x11\n" +
	"\x0f_gradualFilling\"\xe7\x04\n" +
	"\aAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12,\n" +
	"\x04type\x18\x03 \x01(\x0e2\x18.accountType.AccountTypeR\x04type\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x1c\n" +
	"\tremainder\x18\x05 \x01(\x01R\tremainder\x12\x18\n" +
	"\avisible\x18\x06 \x01(\bR\avisible\x12.\n" +
	"\x12accountingInCharts\x18\a \x01(\bR\x12accountingInCharts\x12.\n" +
	"\x12accountingInHeader\x18\b \x01(\bR\x12accountingInHeader\x12&\n" +
	"\x0eaccountGroupID\x18\t \x01(\x05R\x0eaccountGroupID\x12(\n" +
	"\x0fparentAccountID\x18\n" +
	" \x01(\x05R\x0fparentAccountID\x12\x1a\n" +
	"\bisParent\x18\v \x01(\bR\bisParent\x12\x16\n" +
	"\x06iconID\x18\f \x01(\x05R\x06iconID\x12\"\n" +
	"\fserialNumber\x18\r \x01(\x05R\fserialNumber\x12(\n" +
	"\x0fcreatedByUserID\x18\x0e \x01(\x05R\x0fcreatedByUserID\x12B\n" +
	"\x0edatetimeCreate\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\x0edatetimeCreate\x123\n" +
	"\x06budget\x18\x10 \x01(\v2\x16.account.AccountBudgetH\x00R\x06budget\x88\x01\x01B\t\n" +
	"\a_budget\"\xb5\x03\n" +
	"\x12GetAccountsRequest\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\x12(\n" +
	"\x0faccountGroupIDs\x18\x02 \x03(\x05R\x0faccountGroupIDs\x123\n" +
	"\x12accountingInCharts\x18\x03 \x01(\bH\x00R\x12accountingInCharts\x88\x01\x01\x123\n" +
	"\x12accountingInHeader\x18\x04 \x01(\bH\x01R\x12accountingInHeader\x88\x01\x01\x12\x1f\n" +
	"\bdateFrom\x18\x05 \x01(\tH\x02R\bdateFrom\x88\x01\x01\x12\x1b\n" +
	"\x06dateTo\x18\x06 \x01(\tH\x03R\x06dateTo\x88\x01\x01\x121\n" +
	"\x04type\x18\a \x01(\x0e2\x18.accountType.AccountTypeH\x04R\x04type\x88\x01\x01\x12\x1d\n" +
	"\avisible\x18\b \x01(\bH\x05R\avisible\x88\x01\x01B\x15\n" +
	"\x13_accountingInChartsB\x15\n" +
	"\x13_accountingInHeaderB\v\n" +
	"\t_dateFromB\t\n" +
	"\a_dateToB\a\n" +
	"\x05_typeB\n" +
	"\n" +
	"\b_visible\"v\n" +
	"\x13GetAccountsResponse\x12'\n" +
	"\x05error\x18\x01 \x01(\v2\f.error.ErrorH\x00R\x05error\x88\x01\x01\x12,\n" +
	"\baccounts\x18\x02 \x03(\v2\x10.account.AccountR\baccountsB\b\n" +
	"\x06_error\"\xca\x04\n" +
	"\x14CreateAccountRequest\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12,\n" +
	"\x04type\x18\x03 \x01(\x0e2\x18.accountType.AccountTypeR\x04type\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12&\n" +
	"\x0eaccountGroupID\x18\x05 \x01(\x05R\x0eaccountGroupID\x12.\n" +
	"\x12accountingInCharts\x18\x06 \x01(\bR\x12accountingInCharts\x12.\n" +
	"\x12accountingInHeader\x18\a \x01(\bR\x12accountingInHeader\x12\x16\n" +
	"\x06iconID\x18\b \x01(\x05R\x06iconID\x12\x1a\n" +
	"\bisParent\x18\t \x01(\bR\bisParent\x12B\n" +
	"\x0edatetimeCreate\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\x0edatetimeCreate\x12-\n" +
	"\x0fparentAccountID\x18\v \x01(\x05H\x00R\x0fparentAccountID\x88\x01\x01\x12!\n" +
	"\tremainder\x18\f \x01(\x01H\x01R\tremainder\x88\x01\x01\x123\n" +
	"\x06budget\x18\r \x01(\v2\x16.account.AccountBudgetH\x02R\x06budget\x88\x01\x01B\x12\n" +
	"\x10_parentAccountIDB\f\n" +
	"\n" +
	"_remainderB\t\n" +
	"\a_budget\"\xae\x03\n" +
	"\x15CreateAccountResponse\x12'\n" +
	"\x05error\x18\x01 \x01(\v2\f.error.ErrorH\x00R\x05error\x88\x01\x01\x12\x13\n" +
	"\x02id\x18\x02 \x01(\fH\x01R\x02id\x88\x01\x01\x12'\n" +
	"\fserialNumber\x18\x03 \x01(\x05H\x02R\fserialNumber\x88\x01\x01\x123\n" +
	"\x12balancingAccountID\x18\x04 \x01(\x05H\x03R\x12balancingAccountID\x88\x01\x01\x12G\n" +
	"\x1cbalancingAccountSerialNumber\x18\x05 \x01(\x05H\x04R\x1cbalancingAccountSerialNumber\x88\x01\x01\x12;\n" +
	"\x16balancingTransactionID\x18\x06 \x01(\x05H\x05R\x16balancingTransactionID\x88\x01\x01B\b\n" +
	"\x06_errorB\x05\n" +
	"\x03_idB\x0f\n" +
	"\r_serialNumberB\x15\n" +
	"\x13_balancingAccountIDB\x1f\n" +
	"\x1d_balancingAccountSerialNumberB\x19\n" +
	"\x17_balancingTransactionID\"\xfd\x04\n" +
	"\x14UpdateAccountRequest\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\fR\x02id\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x00R\x04name\x88\x01\x01\x123\n" +
	"\x12accountingInCharts\x18\x04 \x01(\bH\x01R\x12accountingInCharts\x88\x01\x01\x123\n" +
	"\x12accountingInHeader\x18\x05 \x01(\bH\x02R\x12accountingInHeader\x88\x01\x01\x12'\n" +
	"\fcurrencyCode\x18\x06 \x01(\tH\x03R\fcurrencyCode\x88\x01\x01\x12\x1b\n" +
	"\x06iconID\x18\a \x01(\x05H\x04R\x06iconID\x88\x01\x01\x12-\n" +
	"\x0fparentAccountID\x18\b \x01(\x05H\x05R\x0fparentAccountID\x88\x01\x01\x12!\n" +
	"\tremainder\x18\t \x01(\x01H\x06R\tremainder\x88\x01\x01\x12'\n" +
	"\fserialNumber\x18\n" +
	" \x01(\x05H\aR\fserialNumber\x88\x01\x01\x12\x1d\n" +
	"\avisible\x18\v \x01(\bH\bR\avisible\x88\x01\x01\x123\n" +
	"\x06budget\x18\f \x01(\v2\x16.account.AccountBudgetH\tR\x06budget\x88\x01\x01B\a\n" +
	"\x05_nameB\x15\n" +
	"\x13_accountingInChartsB\x15\n" +
	"\x13_accountingInHeaderB\x0f\n" +
	"\r_currencyCodeB\t\n" +
	"\a_iconIDB\x12\n" +
	"\x10_parentAccountIDB\f\n" +
	"\n" +
	"_remainderB\x0f\n" +
	"\r_serialNumberB\n" +
	"\n" +
	"\b_visibleB\t\n" +
	"\a_budget\"J\n" +
	"\x15UpdateAccountResponse\x12'\n" +
	"\x05error\x18\x01 \x01(\v2\f.error.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"H\n" +
	"\x14DeleteAccountRequest\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\fR\x02id\"J\n" +
	"\x15DeleteAccountResponse\x12'\n" +
	"\x05error\x18\x01 \x01(\v2\f.error.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error2\xd3\x02\n" +
	"\x0fAccountEndpoint\x12J\n" +
	"\vGetAccounts\x12\x1b.account.GetAccountsRequest\x1a\x1c.account.GetAccountsResponse\"\x00\x12P\n" +
	"\rCreateAccount\x12\x1d.account.CreateAccountRequest\x1a\x1e.account.CreateAccountResponse\"\x00\x12P\n" +
	"\rUpdateAccount\x12\x1d.account.UpdateAccountRequest\x1a\x1e.account.UpdateAccountResponse\"\x00\x12P\n" +
	"\rDeleteAccount\x12\x1d.account.DeleteAccountRequest\x1a\x1e.account.DeleteAccountResponse\"\x00B\bZ\x06/protob\x06proto3"

var (
	file_proto_account_account_endpoint_proto_rawDescOnce sync.Once
	file_proto_account_account_endpoint_proto_rawDescData []byte
)

func file_proto_account_account_endpoint_proto_rawDescGZIP() []byte {
	file_proto_account_account_endpoint_proto_rawDescOnce.Do(func() {
		file_proto_account_account_endpoint_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_account_account_endpoint_proto_rawDesc), len(file_proto_account_account_endpoint_proto_rawDesc)))
	})
	return file_proto_account_account_endpoint_proto_rawDescData
}

var file_proto_account_account_endpoint_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_account_account_endpoint_proto_goTypes = []any{
	(*AccountBudget)(nil),         // 0: account.AccountBudget
	(*Account)(nil),               // 1: account.Account
	(*GetAccountsRequest)(nil),    // 2: account.GetAccountsRequest
	(*GetAccountsResponse)(nil),   // 3: account.GetAccountsResponse
	(*CreateAccountRequest)(nil),  // 4: account.CreateAccountRequest
	(*CreateAccountResponse)(nil), // 5: account.CreateAccountResponse
	(*UpdateAccountRequest)(nil),  // 6: account.UpdateAccountRequest
	(*UpdateAccountResponse)(nil), // 7: account.UpdateAccountResponse
	(*DeleteAccountRequest)(nil),  // 8: account.DeleteAccountRequest
	(*DeleteAccountResponse)(nil), // 9: account.DeleteAccountResponse
	(AccountType)(0),              // 10: accountType.AccountType
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
	(*Error)(nil),                 // 12: error.Error
}
var file_proto_account_account_endpoint_proto_depIdxs = []int32{
	10, // 0: account.Account.type:type_name -> accountType.AccountType
	11, // 1: account.Account.datetimeCreate:type_name -> google.protobuf.Timestamp
	0,  // 2: account.Account.budget:type_name -> account.AccountBudget
	10, // 3: account.GetAccountsRequest.type:type_name -> accountType.AccountType
	12, // 4: account.GetAccountsResponse.error:type_name -> error.Error
	1,  // 5: account.GetAccountsResponse.accounts:type_name -> account.Account
	10, // 6: account.CreateAccountRequest.type:type_name -> accountType.AccountType
	11, // 7: account.CreateAccountRequest.datetimeCreate:type_name -> google.protobuf.Timestamp
	0,  // 8: account.CreateAccountRequest.budget:type_name -> account.AccountBudget
	12, // 9: account.CreateAccountResponse.error:type_name -> error.Error
	0,  // 10: account.UpdateAccountRequest.budget:type_name -> account.AccountBudget
	12, // 11: account.UpdateAccountResponse.error:type_name -> error.Error
	12, // 12: account.DeleteAccountResponse.error:type_name -> error.Error
	2,  // 13: account.AccountEndpoint.GetAccounts:input_type -> account.GetAccountsRequest
	4,  // 14: account.AccountEndpoint.CreateAccount:input_type -> account.CreateAccountRequest
	6,  // 15: account.AccountEndpoint.UpdateAccount:input_type -> account.UpdateAccountRequest
	8,  // 16: account.AccountEndpoint.DeleteAccount:input_type -> account.DeleteAccountRequest
	3,  // 17: account.AccountEndpoint.GetAccounts:output_type -> account.GetAccountsResponse
	5,  // 18: account.AccountEndpoint.CreateAccount:output_type -> account.CreateAccountResponse
	7,  // 19: account.AccountEndpoint.UpdateAccount:output_type -> account.UpdateAccountResponse
	9,  // 20: account.AccountEndpoint.DeleteAccount:output_type -> account.DeleteAccountResponse
	17, // [17:21] is the sub-list for method output_type
	13, // [13:17] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_account_account_endpoint_proto_init() }
func file_proto_account_account_endpoint_proto_init() {
	if File_proto_account_account_endpoint_proto != nil {
		return
	}
	file_proto_error_error_proto_init()
	file_proto_enums_accountType_proto_init()
	file_proto_account_account_endpoint_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_account_account_endpoint_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_account_account_endpoint_proto_msgTypes[2].OneofWrappers = []any{}
	file_proto_account_account_endpoint_proto_msgTypes[3].OneofWrappers = []any{}
	file_proto_account_account_endpoint_proto_msgTypes[4].OneofWrappers = []any{}
	file_proto_account_account_endpoint_proto_msgTypes[5].OneofWrappers = []any{}
	file_proto_account_account_endpoint_proto_msgTypes[6].OneofWrappers = []any{}
	file_proto_account_account_endpoint_proto_msgTypes[7].OneofWrappers = []any{}
	file_proto_account_account_endpoint_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_account_account_endpoint_proto_rawDesc), len(file_proto_account_account_endpoint_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_account_account_endpoint_proto_goTypes,
		DependencyIndexes: file_proto_account_account_endpoint_proto_depIdxs,
		MessageInfos:      file_proto_account_account_endpoint_proto_msgTypes,
	}.Build()
	File_proto_account_account_endpoint_proto = out.File
	file_proto_account_account_endpoint_proto_goTypes = nil
	file_proto_account_account_endpoint_proto_depIdxs = nil
}
