// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: proto/accountBudget/accountBudget-endpoint.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountBudget struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Id              []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                           // Идентификатор версии бюджета
	AccountID       []byte                 `protobuf:"bytes,2,opt,name=accountID,proto3" json:"accountID,omitempty"`             // Идентификатор счета
	Amount          float64                `protobuf:"fixed64,3,opt,name=amount,proto3" json:"amount,omitempty"`                 // Сумма бюджета
	FixedSum        float64                `protobuf:"fixed64,4,opt,name=fixedSum,proto3" json:"fixedSum,omitempty"`             // Фиксированная сумма
	DaysOffset      uint32                 `protobuf:"varint,5,opt,name=daysOffset,proto3" json:"daysOffset,omitempty"`          // Смещение в днях
	GradualFilling  bool                   `protobuf:"varint,6,opt,name=gradualFilling,proto3" json:"gradualFilling,omitempty"`  // Заполняется ли бюджет постепенно
	EffectiveFrom   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=effectiveFrom,proto3" json:"effectiveFrom,omitempty"`     // Дата, с которой действует эта версия бюджета
	CreatedByUserID []byte                 `protobuf:"bytes,8,opt,name=createdByUserID,proto3" json:"createdByUserID,omitempty"` // Идентификатор пользователя, создавшего версию
	DatetimeCreate  *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=datetimeCreate,proto3" json:"datetimeCreate,omitempty"`   // Дата и время создания версии
	AccountGroupID  []byte                 `protobuf:"bytes,10,opt,name=accountGroupID,proto3" json:"accountGroupID,omitempty"`  // Идентификатор группы счетов
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AccountBudget) Reset() {
	*x = AccountBudget{}
	mi := &file_proto_accountBudget_accountBudget_endpoint_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountBudget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountBudget) ProtoMessage() {}

func (x *AccountBudget) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accountBudget_accountBudget_endpoint_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountBudget.ProtoReflect.Descriptor instead.
func (*AccountBudget) Descriptor() ([]byte, []int) {
	return file_proto_accountBudget_accountBudget_endpoint_proto_rawDescGZIP(), []int{0}
}

func (x *AccountBudget) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *AccountBudget) GetAccountID() []byte {
	if x != nil {
		return x.AccountID
	}
	return nil
}

func (x *AccountBudget) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *AccountBudget) GetFixedSum() float64 {
	if x != nil {
		return x.FixedSum
	}
	return 0
}

func (x *AccountBudget) GetDaysOffset() uint32 {
	if x != nil {
		return x.DaysOffset
	}
	return 0
}

func (x *AccountBudget) GetGradualFilling() bool {
	if x != nil {
		return x.GradualFilling
	}
	return false
}

func (x *AccountBudget) GetEffectiveFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.EffectiveFrom
	}
	return nil
}

func (x *AccountBudget) GetCreatedByUserID() []byte {
	if x != nil {
		return x.CreatedByUserID
	}
	return nil
}

func (x *AccountBudget) GetDatetimeCreate() *timestamppb.Timestamp {
	if x != nil {
		return x.DatetimeCreate
	}
	return nil
}

func (x *AccountBudget) GetAccountGroupID() []byte {
	if x != nil {
		return x.AccountGroupID
	}
	return nil
}

type CreateAccountBudgetRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AccessToken    string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`        // Токен доступа
	Id             []byte                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`                          // Идентификатор версии бюджета
	AccountID      []byte                 `protobuf:"bytes,3,opt,name=accountID,proto3" json:"accountID,omitempty"`            // Идентификатор счета
	Amount         float64                `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`                // Сумма бюджета
	FixedSum       float64                `protobuf:"fixed64,5,opt,name=fixedSum,proto3" json:"fixedSum,omitempty"`            // Фиксированная сумма
	DaysOffset     uint32                 `protobuf:"varint,6,opt,name=daysOffset,proto3" json:"daysOffset,omitempty"`         // Смещение в днях
	GradualFilling bool                   `protobuf:"varint,7,opt,name=gradualFilling,proto3" json:"gradualFilling,omitempty"` // Заполняется ли бюджет постепенно
	EffectiveFrom  *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=effectiveFrom,proto3" json:"effectiveFrom,omitempty"`    // Дата, с которой действует эта версия бюджета
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateAccountBudgetRequest) Reset() {
	*x = CreateAccountBudgetRequest{}
	mi := &file_proto_accountBudget_accountBudget_endpoint_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountBudgetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountBudgetRequest) ProtoMessage() {}

func (x *CreateAccountBudgetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accountBudget_accountBudget_endpoint_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountBudgetRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountBudgetRequest) Descriptor() ([]byte, []int) {
	return file_proto_accountBudget_accountBudget_endpoint_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAccountBudgetRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *CreateAccountBudgetRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *CreateAccountBudgetRequest) GetAccountID() []byte {
	if x != nil {
		return x.AccountID
	}
	return nil
}

func (x *CreateAccountBudgetRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CreateAccountBudgetRequest) GetFixedSum() float64 {
	if x != nil {
		return x.FixedSum
	}
	return 0
}

func (x *CreateAccountBudgetRequest) GetDaysOffset() uint32 {
	if x != nil {
		return x.DaysOffset
	}
	return 0
}

func (x *CreateAccountBudgetRequest) GetGradualFilling() bool {
	if x != nil {
		return x.GradualFilling
	}
	return false
}

func (x *CreateAccountBudgetRequest) GetEffectiveFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.EffectiveFrom
	}
	return nil
}

type CreateAccountBudgetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"` // Объект ошибки
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountBudgetResponse) Reset() {
	*x = CreateAccountBudgetResponse{}
	mi := &file_proto_accountBudget_accountBudget_endpoint_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountBudgetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountBudgetResponse) ProtoMessage() {}

func (x *CreateAccountBudgetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accountBudget_accountBudget_endpoint_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountBudgetResponse.ProtoReflect.Descriptor instead.
func (*CreateAccountBudgetResponse) Descriptor() ([]byte, []int) {
	return file_proto_accountBudget_accountBudget_endpoint_proto_rawDescGZIP(), []int{2}
}

func (x *CreateAccountBudgetResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetAccountBudgetsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccessToken     string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`         // Токен доступа
	AccountGroupIDs [][]byte               `protobuf:"bytes,2,rep,name=accountGroupIDs,proto3" json:"accountGroupIDs,omitempty"` // Идентификаторы групп счетов (пусто - все доступные пользователю группы)
	DateFrom        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=dateFrom,proto3,oneof" json:"dateFrom,omitempty"`         // Дата, от которой показывать версии бюджета
	DateTo          *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=dateTo,proto3,oneof" json:"dateTo,omitempty"`             // Дата, до которой показывать версии бюджета
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetAccountBudgetsRequest) Reset() {
	*x = GetAccountBudgetsRequest{}
	mi := &file_proto_accountBudget_accountBudget_endpoint_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountBudgetsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountBudgetsRequest) ProtoMessage() {}

func (x *GetAccountBudgetsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accountBudget_accountBudget_endpoint_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountBudgetsRequest.ProtoReflect.Descriptor instead.
func (*GetAccountBudgetsRequest) Descriptor() ([]byte, []int) {
	return file_proto_accountBudget_accountBudget_endpoint_proto_rawDescGZIP(), []int{3}
}

func (x *GetAccountBudgetsRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *GetAccountBudgetsRequest) GetAccountGroupIDs() [][]byte {
	if x != nil {
		return x.AccountGroupIDs
	}
	return nil
}

func (x *GetAccountBudgetsRequest) GetDateFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.DateFrom
	}
	return nil
}

func (x *GetAccountBudgetsRequest) GetDateTo() *timestamppb.Timestamp {
	if x != nil {
		return x.DateTo
	}
	return nil
}

type GetAccountBudgetsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"` // Объект ошибки
	Budgets       []*AccountBudget       `protobuf:"bytes,2,rep,name=budgets,proto3" json:"budgets,omitempty"`   // Все версии бюджета по всем счетам запрошенных групп счетов
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountBudgetsResponse) Reset() {
	*x = GetAccountBudgetsResponse{}
	mi := &file_proto_accountBudget_accountBudget_endpoint_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountBudgetsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountBudgetsResponse) ProtoMessage() {}

func (x *GetAccountBudgetsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_accountBudget_accountBudget_endpoint_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountBudgetsResponse.ProtoReflect.Descriptor instead.
func (*GetAccountBudgetsResponse) Descriptor() ([]byte, []int) {
	return file_proto_accountBudget_accountBudget_endpoint_proto_rawDescGZIP(), []int{4}
}

func (x *GetAccountBudgetsResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *GetAccountBudgetsResponse) GetBudgets() []*AccountBudget {
	if x != nil {
		return x.Budgets
	}
	return nil
}

var File_proto_accountBudget_accountBudget_endpoint_proto protoreflect.FileDescriptor

const file_proto_accountBudget_accountBudget_endpoint_proto_rawDesc = "" +
	"\n" +
	"0proto/accountBudget/accountBudget-endpoint.proto\x12\raccountBudget\x1a\x17proto/error/error.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x91\x03\n" +
	"\rAccountBudget\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x1c\n" +
	"\taccountID\x18\x02 \x01(\fR\taccountID\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bfixedSum\x18\x04 \x01(\x01R\bfixedSum\x12\x1e\n" +
	"\n" +
	"daysOffset\x18\x05 \x01(\rR\n" +
	"daysOffset\x12&\n" +
	"\x0egradualFilling\x18\x06 \x01(\bR\x0egradualFilling\x12@\n" +
	"\reffectiveFrom\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\reffectiveFrom\x12(\n" +
	"\x0fcreatedByUserID\x18\b \x01(\fR\x0fcreatedByUserID\x12B\n" +
	"\x0edatetimeCreate\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x0edatetimeCreate\x12&\n" +
	"\x0eaccountGroupID\x18\n" +
	" \x01(\fR\x0eaccountGroupID\"\xaa\x02\n" +
	"\x1aCreateAccountBudgetRequest\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\fR\x02id\x12\x1c\n" +
	"\taccountID\x18\x03 \x01(\fR\taccountID\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x01R\x06amount\x12\x1a\n" +
	"\bfixedSum\x18\x05 \x01(\x01R\bfixedSum\x12\x1e\n" +
	"\n" +
	"daysOffset\x18\x06 \x01(\rR\n" +
	"daysOffset\x12&\n" +
	"\x0egradualFilling\x18\a \x01(\bR\x0egradualFilling\x12@\n" +
	"\reffectiveFrom\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\reffectiveFrom\"P\n" +
	"\x1bCreateAccountBudgetResponse\x12'\n" +
	"\x05error\x18\x01 \x01(\v2\f.error.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\xf4\x01\n" +
	"\x18GetAccountBudgetsRequest\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\x12(\n" +
	"\x0faccountGroupIDs\x18\x02 \x03(\fR\x0faccountGroupIDs\x12;\n" +
	"\bdateFrom\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x00R\bdateFrom\x88\x01\x01\x127\n" +
	"\x06dateTo\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x06dateTo\x88\x01\x01B\v\n" +
	"\t_dateFromB\t\n" +
	"\a_dateTo\"\x86\x01\n" +
	"\x19GetAccountBudgetsResponse\x12'\n" +
	"\x05error\x18\x01 \x01(\v2\f.error.ErrorH\x00R\x05error\x88\x01\x01\x126\n" +
	"\abudgets\x18\x02 \x03(\v2\x1c.accountBudget.AccountBudgetR\abudgetsB\b\n" +
	"\x06_error2\xf1\x01\n" +
	"\x15AccountBudgetEndpoint\x12n\n" +
	"\x13CreateAccountBudget\x12).accountBudget.CreateAccountBudgetRequest\x1a*.accountBudget.CreateAccountBudgetResponse\"\x00\x12h\n" +
	"\x11GetAccountBudgets\x12'.accountBudget.GetAccountBudgetsRequest\x1a(.accountBudget.GetAccountBudgetsResponse\"\x00B\bZ\x06/protob\x06proto3"

var (
	file_proto_accountBudget_accountBudget_endpoint_proto_rawDescOnce sync.Once
	file_proto_accountBudget_accountBudget_endpoint_proto_rawDescData []byte
)

func file_proto_accountBudget_accountBudget_endpoint_proto_rawDescGZIP() []byte {
	file_proto_accountBudget_accountBudget_endpoint_proto_rawDescOnce.Do(func() {
		file_proto_accountBudget_accountBudget_endpoint_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_accountBudget_accountBudget_endpoint_proto_rawDesc), len(file_proto_accountBudget_accountBudget_endpoint_proto_rawDesc)))
	})
	return file_proto_accountBudget_accountBudget_endpoint_proto_rawDescData
}

var file_proto_accountBudget_accountBudget_endpoint_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_accountBudget_accountBudget_endpoint_proto_goTypes = []any{
	(*AccountBudget)(nil),               // 0: accountBudget.AccountBudget
	(*CreateAccountBudgetRequest)(nil),  // 1: accountBudget.CreateAccountBudgetRequest
	(*CreateAccountBudgetResponse)(nil), // 2: accountBudget.CreateAccountBudgetResponse
	(*GetAccountBudgetsRequest)(nil),    // 3: accountBudget.GetAccountBudgetsRequest
	(*GetAccountBudgetsResponse)(nil),   // 4: accountBudget.GetAccountBudgetsResponse
	(*timestamppb.Timestamp)(nil),       // 5: google.protobuf.Timestamp
	(*Error)(nil),                       // 6: error.Error
}
var file_proto_accountBudget_accountBudget_endpoint_proto_depIdxs = []int32{
	5,  // 0: accountBudget.AccountBudget.effectiveFrom:type_name -> google.protobuf.Timestamp
	5,  // 1: accountBudget.AccountBudget.datetimeCreate:type_name -> google.protobuf.Timestamp
	5,  // 2: accountBudget.CreateAccountBudgetRequest.effectiveFrom:type_name -> google.protobuf.Timestamp
	6,  // 3: accountBudget.CreateAccountBudgetResponse.error:type_name -> error.Error
	5,  // 4: accountBudget.GetAccountBudgetsRequest.dateFrom:type_name -> google.protobuf.Timestamp
	5,  // 5: accountBudget.GetAccountBudgetsRequest.dateTo:type_name -> google.protobuf.Timestamp
	6,  // 6: accountBudget.GetAccountBudgetsResponse.error:type_name -> error.Error
	0,  // 7: accountBudget.GetAccountBudgetsResponse.budgets:type_name -> accountBudget.AccountBudget
	1,  // 8: accountBudget.AccountBudgetEndpoint.CreateAccountBudget:input_type -> accountBudget.CreateAccountBudgetRequest
	3,  // 9: accountBudget.AccountBudgetEndpoint.GetAccountBudgets:input_type -> accountBudget.GetAccountBudgetsRequest
	2,  // 10: accountBudget.AccountBudgetEndpoint.CreateAccountBudget:output_type -> accountBudget.CreateAccountBudgetResponse
	4,  // 11: accountBudget.AccountBudgetEndpoint.GetAccountBudgets:output_type -> accountBudget.GetAccountBudgetsResponse
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_accountBudget_accountBudget_endpoint_proto_init() }
func file_proto_accountBudget_accountBudget_endpoint_proto_init() {
	if File_proto_accountBudget_accountBudget_endpoint_proto != nil {
		return
	}
	file_proto_error_error_proto_init()
	file_proto_accountBudget_accountBudget_endpoint_proto_msgTypes[2].OneofWrappers = []any{}
	file_proto_accountBudget_accountBudget_endpoint_proto_msgTypes[3].OneofWrappers = []any{}
	file_proto_accountBudget_accountBudget_endpoint_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_accountBudget_accountBudget_endpoint_proto_rawDesc), len(file_proto_accountBudget_accountBudget_endpoint_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_accountBudget_accountBudget_endpoint_proto_goTypes,
		DependencyIndexes: file_proto_accountBudget_accountBudget_endpoint_proto_depIdxs,
		MessageInfos:      file_proto_accountBudget_accountBudget_endpoint_proto_msgTypes,
	}.Build()
	File_proto_accountBudget_accountBudget_endpoint_proto = out.File
	file_proto_accountBudget_accountBudget_endpoint_proto_goTypes = nil
	file_proto_accountBudget_accountBudget_endpoint_proto_depIdxs = nil
}
