// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/accountBudget/accountBudget-endpoint.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AccountBudgetEndpoint_CreateAccountBudget_FullMethodName     = "/accountBudget.AccountBudgetEndpoint/CreateAccountBudget"
	AccountBudgetEndpoint_GetAccountBudgetHistory_FullMethodName = "/accountBudget.AccountBudgetEndpoint/GetAccountBudgetHistory"
)

// AccountBudgetEndpointClient is the client API for AccountBudgetEndpoint service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccountBudgetEndpointClient interface {
	// CreateAccountBudget создание новой версии бюджета счета, действующей с указанной даты
	CreateAccountBudget(ctx context.Context, in *CreateAccountBudgetRequest, opts ...grpc.CallOption) (*CreateAccountBudgetResponse, error)
	// GetAccountBudgetHistory получение истории версий бюджета счета
	GetAccountBudgetHistory(ctx context.Context, in *GetAccountBudgetHistoryRequest, opts ...grpc.CallOption) (*GetAccountBudgetHistoryResponse, error)
}

type accountBudgetEndpointClient struct {
	cc grpc.ClientConnInterface
}

func NewAccountBudgetEndpointClient(cc grpc.ClientConnInterface) AccountBudgetEndpointClient {
	return &accountBudgetEndpointClient{cc}
}

func (c *accountBudgetEndpointClient) CreateAccountBudget(ctx context.Context, in *CreateAccountBudgetRequest, opts ...grpc.CallOption) (*CreateAccountBudgetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAccountBudgetResponse)
	err := c.cc.Invoke(ctx, AccountBudgetEndpoint_CreateAccountBudget_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountBudgetEndpointClient) GetAccountBudgetHistory(ctx context.Context, in *GetAccountBudgetHistoryRequest, opts ...grpc.CallOption) (*GetAccountBudgetHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAccountBudgetHistoryResponse)
	err := c.cc.Invoke(ctx, AccountBudgetEndpoint_GetAccountBudgetHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccountBudgetEndpointServer is the server API for AccountBudgetEndpoint service.
// All implementations must embed UnimplementedAccountBudgetEndpointServer
// for forward compatibility.
type AccountBudgetEndpointServer interface {
	// CreateAccountBudget создание новой версии бюджета счета, действующей с указанной даты
	CreateAccountBudget(context.Context, *CreateAccountBudgetRequest) (*CreateAccountBudgetResponse, error)
	// GetAccountBudgetHistory получение истории версий бюджета счета
	GetAccountBudgetHistory(context.Context, *GetAccountBudgetHistoryRequest) (*GetAccountBudgetHistoryResponse, error)
	mustEmbedUnimplementedAccountBudgetEndpointServer()
}

// UnimplementedAccountBudgetEndpointServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAccountBudgetEndpointServer struct{}

func (UnimplementedAccountBudgetEndpointServer) CreateAccountBudget(context.Context, *CreateAccountBudgetRequest) (*CreateAccountBudgetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAccountBudget not implemented")
}
func (UnimplementedAccountBudgetEndpointServer) GetAccountBudgetHistory(context.Context, *GetAccountBudgetHistoryRequest) (*GetAccountBudgetHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAccountBudgetHistory not implemented")
}
func (UnimplementedAccountBudgetEndpointServer) mustEmbedUnimplementedAccountBudgetEndpointServer() {}
func (UnimplementedAccountBudgetEndpointServer) testEmbeddedByValue()                               {}

// UnsafeAccountBudgetEndpointServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccountBudgetEndpointServer will
// result in compilation errors.
type UnsafeAccountBudgetEndpointServer interface {
	mustEmbedUnimplementedAccountBudgetEndpointServer()
}

func RegisterAccountBudgetEndpointServer(s grpc.ServiceRegistrar, srv AccountBudgetEndpointServer) {
	// If the following call panics, it indicates UnimplementedAccountBudgetEndpointServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AccountBudgetEndpoint_ServiceDesc, srv)
}

func _AccountBudgetEndpoint_CreateAccountBudget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountBudgetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountBudgetEndpointServer).CreateAccountBudget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountBudgetEndpoint_CreateAccountBudget_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountBudgetEndpointServer).CreateAccountBudget(ctx, req.(*CreateAccountBudgetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountBudgetEndpoint_GetAccountBudgetHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountBudgetHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountBudgetEndpointServer).GetAccountBudgetHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccountBudgetEndpoint_GetAccountBudgetHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountBudgetEndpointServer).GetAccountBudgetHistory(ctx, req.(*GetAccountBudgetHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccountBudgetEndpoint_ServiceDesc is the grpc.ServiceDesc for AccountBudgetEndpoint service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccountBudgetEndpoint_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "accountBudget.AccountBudgetEndpoint",
	HandlerType: (*AccountBudgetEndpointServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAccountBudget",
			Handler:    _AccountBudgetEndpoint_CreateAccountBudget_Handler,
		},
		{
			MethodName: "GetAccountBudgetHistory",
			Handler:    _AccountBudgetEndpoint_GetAccountBudgetHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/accountBudget/accountBudget-endpoint.proto",
}
