// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: proto/enums/applicationType.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplicationType int32

const (
	ApplicationType_Unspecified ApplicationType = 0
	ApplicationType_IOS         ApplicationType = 1
	ApplicationType_Android     ApplicationType = 2
	ApplicationType_Web         ApplicationType = 3
	ApplicationType_Server      ApplicationType = 4
)

// Enum value maps for ApplicationType.
var (
	ApplicationType_name = map[int32]string{
		0: "Unspecified",
		1: "IOS",
		2: "Android",
		3: "Web",
		4: "Server",
	}
	ApplicationType_value = map[string]int32{
		"Unspecified": 0,
		"IOS":         1,
		"Android":     2,
		"Web":         3,
		"Server":      4,
	}
)

func (x ApplicationType) Enum() *ApplicationType {
	p := new(ApplicationType)
	*p = x
	return p
}

func (x ApplicationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ApplicationType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_enums_applicationType_proto_enumTypes[0].Descriptor()
}

func (ApplicationType) Type() protoreflect.EnumType {
	return &file_proto_enums_applicationType_proto_enumTypes[0]
}

func (x ApplicationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ApplicationType.Descriptor instead.
func (ApplicationType) EnumDescriptor() ([]byte, []int) {
	return file_proto_enums_applicationType_proto_rawDescGZIP(), []int{0}
}

var File_proto_enums_applicationType_proto protoreflect.FileDescriptor

const file_proto_enums_applicationType_proto_rawDesc = "" +
	"\n" +
	"!proto/enums/applicationType.proto\x12\x0fapplicationType*M\n" +
	"\x0fApplicationType\x12\x0f\n" +
	"\vUnspecified\x10\x00\x12\a\n" +
	"\x03IOS\x10\x01\x12\v\n" +
	"\aAndroid\x10\x02\x12\a\n" +
	"\x03Web\x10\x03\x12\n" +
	"\n" +
	"\x06Server\x10\x04B\bZ\x06/protob\x06proto3"

var (
	file_proto_enums_applicationType_proto_rawDescOnce sync.Once
	file_proto_enums_applicationType_proto_rawDescData []byte
)

func file_proto_enums_applicationType_proto_rawDescGZIP() []byte {
	file_proto_enums_applicationType_proto_rawDescOnce.Do(func() {
		file_proto_enums_applicationType_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_enums_applicationType_proto_rawDesc), len(file_proto_enums_applicationType_proto_rawDesc)))
	})
	return file_proto_enums_applicationType_proto_rawDescData
}

var file_proto_enums_applicationType_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_enums_applicationType_proto_goTypes = []any{
	(ApplicationType)(0), // 0: applicationType.ApplicationType
}
var file_proto_enums_applicationType_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_enums_applicationType_proto_init() }
func file_proto_enums_applicationType_proto_init() {
	if File_proto_enums_applicationType_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_enums_applicationType_proto_rawDesc), len(file_proto_enums_applicationType_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_enums_applicationType_proto_goTypes,
		DependencyIndexes: file_proto_enums_applicationType_proto_depIdxs,
		EnumInfos:         file_proto_enums_applicationType_proto_enumTypes,
	}.Build()
	File_proto_enums_applicationType_proto = out.File
	file_proto_enums_applicationType_proto_goTypes = nil
	file_proto_enums_applicationType_proto_depIdxs = nil
}
