// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/auditLog/auditLog-endpoint.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuditLogEndpoint_GetAuditLogs_FullMethodName = "/auditLog.AuditLogEndpoint/GetAuditLogs"
)

// AuditLogEndpointClient is the client API for AuditLogEndpoint service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuditLogEndpointClient interface {
	// GetAuditLogs получение записей аудит-лога, доступных пользователю по группам счетов
	GetAuditLogs(ctx context.Context, in *GetAuditLogsRequest, opts ...grpc.CallOption) (*GetAuditLogsResponse, error)
}

type auditLogEndpointClient struct {
	cc grpc.ClientConnInterface
}

func NewAuditLogEndpointClient(cc grpc.ClientConnInterface) AuditLogEndpointClient {
	return &auditLogEndpointClient{cc}
}

func (c *auditLogEndpointClient) GetAuditLogs(ctx context.Context, in *GetAuditLogsRequest, opts ...grpc.CallOption) (*GetAuditLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAuditLogsResponse)
	err := c.cc.Invoke(ctx, AuditLogEndpoint_GetAuditLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuditLogEndpointServer is the server API for AuditLogEndpoint service.
// All implementations must embed UnimplementedAuditLogEndpointServer
// for forward compatibility.
type AuditLogEndpointServer interface {
	// GetAuditLogs получение записей аудит-лога, доступных пользователю по группам счетов
	GetAuditLogs(context.Context, *GetAuditLogsRequest) (*GetAuditLogsResponse, error)
	mustEmbedUnimplementedAuditLogEndpointServer()
}

// UnimplementedAuditLogEndpointServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuditLogEndpointServer struct{}

func (UnimplementedAuditLogEndpointServer) GetAuditLogs(context.Context, *GetAuditLogsRequest) (*GetAuditLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAuditLogs not implemented")
}
func (UnimplementedAuditLogEndpointServer) mustEmbedUnimplementedAuditLogEndpointServer() {}
func (UnimplementedAuditLogEndpointServer) testEmbeddedByValue()                          {}

// UnsafeAuditLogEndpointServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuditLogEndpointServer will
// result in compilation errors.
type UnsafeAuditLogEndpointServer interface {
	mustEmbedUnimplementedAuditLogEndpointServer()
}

func RegisterAuditLogEndpointServer(s grpc.ServiceRegistrar, srv AuditLogEndpointServer) {
	// If the following call panics, it indicates UnimplementedAuditLogEndpointServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuditLogEndpoint_ServiceDesc, srv)
}

func _AuditLogEndpoint_GetAuditLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuditLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuditLogEndpointServer).GetAuditLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuditLogEndpoint_GetAuditLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuditLogEndpointServer).GetAuditLogs(ctx, req.(*GetAuditLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuditLogEndpoint_ServiceDesc is the grpc.ServiceDesc for AuditLogEndpoint service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuditLogEndpoint_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auditLog.AuditLogEndpoint",
	HandlerType: (*AuditLogEndpointServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAuditLogs",
			Handler:    _AuditLogEndpoint_GetAuditLogs_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/auditLog/auditLog-endpoint.proto",
}
