// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: proto/auth/auth-endpoint.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tokens struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`   // Токен доступа
	RefreshToken  string                 `protobuf:"bytes,2,opt,name=refreshToken,proto3" json:"refreshToken,omitempty"` // Токен восстановления доступа
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tokens) Reset() {
	*x = Tokens{}
	mi := &file_proto_auth_auth_endpoint_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tokens) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tokens) ProtoMessage() {}

func (x *Tokens) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_endpoint_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tokens.ProtoReflect.Descriptor instead.
func (*Tokens) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_endpoint_proto_rawDescGZIP(), []int{0}
}

func (x *Tokens) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *Tokens) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type ApplicationInformation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`   // Версия приложения
	Build         string                 `protobuf:"bytes,2,opt,name=build,proto3" json:"build,omitempty"`       // Билд приложения
	BundleID      string                 `protobuf:"bytes,3,opt,name=bundleID,proto3" json:"bundleID,omitempty"` // Бандл приложения
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplicationInformation) Reset() {
	*x = ApplicationInformation{}
	mi := &file_proto_auth_auth_endpoint_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationInformation) ProtoMessage() {}

func (x *ApplicationInformation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_endpoint_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationInformation.ProtoReflect.Descriptor instead.
func (*ApplicationInformation) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_endpoint_proto_rawDescGZIP(), []int{1}
}

func (x *ApplicationInformation) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ApplicationInformation) GetBuild() string {
	if x != nil {
		return x.Build
	}
	return ""
}

func (x *ApplicationInformation) GetBundleID() string {
	if x != nil {
		return x.BundleID
	}
	return ""
}

type DeviceInformation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceName    string                 `protobuf:"bytes,1,opt,name=deviceName,proto3" json:"deviceName,omitempty"`             // Название девайса
	ModelName     string                 `protobuf:"bytes,2,opt,name=modelName,proto3" json:"modelName,omitempty"`               // Название модели
	NameOS        OSType                 `protobuf:"varint,3,opt,name=nameOS,proto3,enum=osType.OSType" json:"nameOS,omitempty"` // Название операционной системы
	VersionOS     string                 `protobuf:"bytes,4,opt,name=versionOS,proto3" json:"versionOS,omitempty"`               // Версия операционной системы
	IpAddress     string                 `protobuf:"bytes,5,opt,name=ipAddress,proto3" json:"ipAddress,omitempty"`               // IP адрес
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceInformation) Reset() {
	*x = DeviceInformation{}
	mi := &file_proto_auth_auth_endpoint_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInformation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInformation) ProtoMessage() {}

func (x *DeviceInformation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_endpoint_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInformation.ProtoReflect.Descriptor instead.
func (*DeviceInformation) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_endpoint_proto_rawDescGZIP(), []int{2}
}

func (x *DeviceInformation) GetDeviceName() string {
	if x != nil {
		return x.DeviceName
	}
	return ""
}

func (x *DeviceInformation) GetModelName() string {
	if x != nil {
		return x.ModelName
	}
	return ""
}

func (x *DeviceInformation) GetNameOS() OSType {
	if x != nil {
		return x.NameOS
	}
	return OSType_Unspecified
}

func (x *DeviceInformation) GetVersionOS() string {
	if x != nil {
		return x.VersionOS
	}
	return ""
}

func (x *DeviceInformation) GetIpAddress() string {
	if x != nil {
		return x.IpAddress
	}
	return ""
}

type SignInRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Email         string                  `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`             // Электронная почта пользователя
	Password      string                  `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`       // Пароль пользователя
	Application   *ApplicationInformation `protobuf:"bytes,3,opt,name=application,proto3" json:"application,omitempty"` // Информация о приложении
	Device        *DeviceInformation      `protobuf:"bytes,4,opt,name=device,proto3" json:"device,omitempty"`           // Информация о девайсе
	DeviceID      string                  `protobuf:"bytes,5,opt,name=deviceID,proto3" json:"deviceID,omitempty"`       // Идентификатор устройства
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignInRequest) Reset() {
	*x = SignInRequest{}
	mi := &file_proto_auth_auth_endpoint_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInRequest) ProtoMessage() {}

func (x *SignInRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_endpoint_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInRequest.ProtoReflect.Descriptor instead.
func (*SignInRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_endpoint_proto_rawDescGZIP(), []int{3}
}

func (x *SignInRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SignInRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SignInRequest) GetApplication() *ApplicationInformation {
	if x != nil {
		return x.Application
	}
	return nil
}

func (x *SignInRequest) GetDevice() *DeviceInformation {
	if x != nil {
		return x.Device
	}
	return nil
}

func (x *SignInRequest) GetDeviceID() string {
	if x != nil {
		return x.DeviceID
	}
	return ""
}

type SignInResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"` // Объект ошибки
	Id            []byte                 `protobuf:"bytes,2,opt,name=id,proto3,oneof" json:"id,omitempty"`       // Идентификатор пользователя
	Token         *Tokens                `protobuf:"bytes,3,opt,name=token,proto3,oneof" json:"token,omitempty"` // Токены доступа
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignInResponse) Reset() {
	*x = SignInResponse{}
	mi := &file_proto_auth_auth_endpoint_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignInResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignInResponse) ProtoMessage() {}

func (x *SignInResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_endpoint_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignInResponse.ProtoReflect.Descriptor instead.
func (*SignInResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_endpoint_proto_rawDescGZIP(), []int{4}
}

func (x *SignInResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *SignInResponse) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *SignInResponse) GetToken() *Tokens {
	if x != nil {
		return x.Token
	}
	return nil
}

type SignUpRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Name          string                  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`               // Имя пользователя
	Email         string                  `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`             // Электронная почта пользователя
	Password      string                  `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`       // Пароль пользователя
	Application   *ApplicationInformation `protobuf:"bytes,4,opt,name=application,proto3" json:"application,omitempty"` // Информация о приложении
	Device        *DeviceInformation      `protobuf:"bytes,5,opt,name=device,proto3" json:"device,omitempty"`           // Информация о девайсе
	DeviceID      string                  `protobuf:"bytes,6,opt,name=deviceID,proto3" json:"deviceID,omitempty"`       // Идентификатор устройства
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignUpRequest) Reset() {
	*x = SignUpRequest{}
	mi := &file_proto_auth_auth_endpoint_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpRequest) ProtoMessage() {}

func (x *SignUpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_endpoint_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpRequest.ProtoReflect.Descriptor instead.
func (*SignUpRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_endpoint_proto_rawDescGZIP(), []int{5}
}

func (x *SignUpRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SignUpRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *SignUpRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *SignUpRequest) GetApplication() *ApplicationInformation {
	if x != nil {
		return x.Application
	}
	return nil
}

func (x *SignUpRequest) GetDevice() *DeviceInformation {
	if x != nil {
		return x.Device
	}
	return nil
}

func (x *SignUpRequest) GetDeviceID() string {
	if x != nil {
		return x.DeviceID
	}
	return ""
}

type SignUpResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"` // Объект ошибки
	Id            []byte                 `protobuf:"bytes,2,opt,name=id,proto3,oneof" json:"id,omitempty"`       // Идентификатор пользователя
	Token         *Tokens                `protobuf:"bytes,3,opt,name=token,proto3,oneof" json:"token,omitempty"` // Токены доступа
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignUpResponse) Reset() {
	*x = SignUpResponse{}
	mi := &file_proto_auth_auth_endpoint_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignUpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignUpResponse) ProtoMessage() {}

func (x *SignUpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_endpoint_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignUpResponse.ProtoReflect.Descriptor instead.
func (*SignUpResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_endpoint_proto_rawDescGZIP(), []int{6}
}

func (x *SignUpResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *SignUpResponse) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *SignUpResponse) GetToken() *Tokens {
	if x != nil {
		return x.Token
	}
	return nil
}

type SignOutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"` // Токен доступа
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignOutRequest) Reset() {
	*x = SignOutRequest{}
	mi := &file_proto_auth_auth_endpoint_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignOutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignOutRequest) ProtoMessage() {}

func (x *SignOutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_endpoint_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignOutRequest.ProtoReflect.Descriptor instead.
func (*SignOutRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_endpoint_proto_rawDescGZIP(), []int{7}
}

func (x *SignOutRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type SignOutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"` // Объект ошибки
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignOutResponse) Reset() {
	*x = SignOutResponse{}
	mi := &file_proto_auth_auth_endpoint_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignOutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignOutResponse) ProtoMessage() {}

func (x *SignOutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_endpoint_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignOutResponse.ProtoReflect.Descriptor instead.
func (*SignOutResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_endpoint_proto_rawDescGZIP(), []int{8}
}

func (x *SignOutResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type RefreshTokensRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Token         string                  `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                   // Токен восстановления доступа
	Application   *ApplicationInformation `protobuf:"bytes,2,opt,name=application,proto3,oneof" json:"application,omitempty"` // Информация о приложении
	Device        *DeviceInformation      `protobuf:"bytes,3,opt,name=device,proto3,oneof" json:"device,omitempty"`           // Информация о девайсе
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokensRequest) Reset() {
	*x = RefreshTokensRequest{}
	mi := &file_proto_auth_auth_endpoint_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokensRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokensRequest) ProtoMessage() {}

func (x *RefreshTokensRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_endpoint_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokensRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokensRequest) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_endpoint_proto_rawDescGZIP(), []int{9}
}

func (x *RefreshTokensRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *RefreshTokensRequest) GetApplication() *ApplicationInformation {
	if x != nil {
		return x.Application
	}
	return nil
}

func (x *RefreshTokensRequest) GetDevice() *DeviceInformation {
	if x != nil {
		return x.Device
	}
	return nil
}

type RefreshTokensResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`               // Объект ошибки
	AccessToken   *string                `protobuf:"bytes,2,opt,name=accessToken,proto3,oneof" json:"accessToken,omitempty"`   // Токен доступа
	RefreshToken  *string                `protobuf:"bytes,3,opt,name=refreshToken,proto3,oneof" json:"refreshToken,omitempty"` // Токен восстановления доступа
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokensResponse) Reset() {
	*x = RefreshTokensResponse{}
	mi := &file_proto_auth_auth_endpoint_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokensResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokensResponse) ProtoMessage() {}

func (x *RefreshTokensResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auth_auth_endpoint_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokensResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokensResponse) Descriptor() ([]byte, []int) {
	return file_proto_auth_auth_endpoint_proto_rawDescGZIP(), []int{10}
}

func (x *RefreshTokensResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *RefreshTokensResponse) GetAccessToken() string {
	if x != nil && x.AccessToken != nil {
		return *x.AccessToken
	}
	return ""
}

func (x *RefreshTokensResponse) GetRefreshToken() string {
	if x != nil && x.RefreshToken != nil {
		return *x.RefreshToken
	}
	return ""
}

var File_proto_auth_auth_endpoint_proto protoreflect.FileDescriptor

const file_proto_auth_auth_endpoint_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/auth/auth-endpoint.proto\x12\x04auth\x1a\x17proto/error/error.proto\x1a\x18proto/enums/osType.proto\"N\n" +
	"\x06Tokens\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\x12\"\n" +
	"\frefreshToken\x18\x02 \x01(\tR\frefreshToken\"d\n" +
	"\x16ApplicationInformation\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x14\n" +
	"\x05build\x18\x02 \x01(\tR\x05build\x12\x1a\n" +
	"\bbundleID\x18\x03 \x01(\tR\bbundleID\"\xb5\x01\n" +
	"\x11DeviceInformation\x12\x1e\n" +
	"\n" +
	"deviceName\x18\x01 \x01(\tR\n" +
	"deviceName\x12\x1c\n" +
	"\tmodelName\x18\x02 \x01(\tR\tmodelName\x12&\n" +
	"\x06nameOS\x18\x03 \x01(\x0e2\x0e.osType.OSTypeR\x06nameOS\x12\x1c\n" +
	"\tversionOS\x18\x04 \x01(\tR\tversionOS\x12\x1c\n" +
	"\tipAddress\x18\x05 \x01(\tR\tipAddress\"\xce\x01\n" +
	"\rSignInRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12>\n" +
	"\vapplication\x18\x03 \x01(\v2\x1c.auth.ApplicationInformationR\vapplication\x12/\n" +
	"\x06device\x18\x04 \x01(\v2\x17.auth.DeviceInformationR\x06device\x12\x1a\n" +
	"\bdeviceID\x18\x05 \x01(\tR\bdeviceID\"\x92\x01\n" +
	"\x0eSignInResponse\x12'\n" +
	"\x05error\x18\x01 \x01(\v2\f.error.ErrorH\x00R\x05error\x88\x01\x01\x12\x13\n" +
	"\x02id\x18\x02 \x01(\fH\x01R\x02id\x88\x01\x01\x12'\n" +
	"\x05token\x18\x03 \x01(\v2\f.auth.TokensH\x02R\x05token\x88\x01\x01B\b\n" +
	"\x06_errorB\x05\n" +
	"\x03_idB\b\n" +
	"\x06_token\"\xe2\x01\n" +
	"\rSignUpRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12>\n" +
	"\vapplication\x18\x04 \x01(\v2\x1c.auth.ApplicationInformationR\vapplication\x12/\n" +
	"\x06device\x18\x05 \x01(\v2\x17.auth.DeviceInformationR\x06device\x12\x1a\n" +
	"\bdeviceID\x18\x06 \x01(\tR\bdeviceID\"\x92\x01\n" +
	"\x0eSignUpResponse\x12'\n" +
	"\x05error\x18\x01 \x01(\v2\f.error.ErrorH\x00R\x05error\x88\x01\x01\x12\x13\n" +
	"\x02id\x18\x02 \x01(\fH\x01R\x02id\x88\x01\x01\x12'\n" +
	"\x05token\x18\x03 \x01(\v2\f.auth.TokensH\x02R\x05token\x88\x01\x01B\b\n" +
	"\x06_errorB\x05\n" +
	"\x03_idB\b\n" +
	"\x06_token\"2\n" +
	"\x0eSignOutRequest\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\"D\n" +
	"\x0fSignOutResponse\x12'\n" +
	"\x05error\x18\x01 \x01(\v2\f.error.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\xc2\x01\n" +
	"\x14RefreshTokensRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12C\n" +
	"\vapplication\x18\x02 \x01(\v2\x1c.auth.ApplicationInformationH\x00R\vapplication\x88\x01\x01\x124\n" +
	"\x06device\x18\x03 \x01(\v2\x17.auth.DeviceInformationH\x01R\x06device\x88\x01\x01B\x0e\n" +
	"\f_applicationB\t\n" +
	"\a_device\"\xbb\x01\n" +
	"\x15RefreshTokensResponse\x12'\n" +
	"\x05error\x18\x01 \x01(\v2\f.error.ErrorH\x00R\x05error\x88\x01\x01\x12%\n" +
	"\vaccessToken\x18\x02 \x01(\tH\x01R\vaccessToken\x88\x01\x01\x12'\n" +
	"\frefreshToken\x18\x03 \x01(\tH\x02R\frefreshToken\x88\x01\x01B\b\n" +
	"\x06_errorB\x0e\n" +
	"\f_accessTokenB\x0f\n" +
	"\r_refreshToken2\x82\x02\n" +
	"\fAuthEndpoint\x125\n" +
	"\x06SignIn\x12\x13.auth.SignInRequest\x1a\x14.auth.SignInResponse\"\x00\x125\n" +
	"\x06SignUp\x12\x13.auth.SignUpRequest\x1a\x14.auth.SignUpResponse\"\x00\x128\n" +
	"\aSignOut\x12\x14.auth.SignOutRequest\x1a\x15.auth.SignOutResponse\"\x00\x12J\n" +
	"\rRefreshTokens\x12\x1a.auth.RefreshTokensRequest\x1a\x1b.auth.RefreshTokensResponse\"\x00B\bZ\x06/protob\x06proto3"

var (
	file_proto_auth_auth_endpoint_proto_rawDescOnce sync.Once
	file_proto_auth_auth_endpoint_proto_rawDescData []byte
)

func file_proto_auth_auth_endpoint_proto_rawDescGZIP() []byte {
	file_proto_auth_auth_endpoint_proto_rawDescOnce.Do(func() {
		file_proto_auth_auth_endpoint_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_auth_auth_endpoint_proto_rawDesc), len(file_proto_auth_auth_endpoint_proto_rawDesc)))
	})
	return file_proto_auth_auth_endpoint_proto_rawDescData
}

var file_proto_auth_auth_endpoint_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_auth_auth_endpoint_proto_goTypes = []any{
	(*Tokens)(nil),                 // 0: auth.Tokens
	(*ApplicationInformation)(nil), // 1: auth.ApplicationInformation
	(*DeviceInformation)(nil),      // 2: auth.DeviceInformation
	(*SignInRequest)(nil),          // 3: auth.SignInRequest
	(*SignInResponse)(nil),         // 4: auth.SignInResponse
	(*SignUpRequest)(nil),          // 5: auth.SignUpRequest
	(*SignUpResponse)(nil),         // 6: auth.SignUpResponse
	(*SignOutRequest)(nil),         // 7: auth.SignOutRequest
	(*SignOutResponse)(nil),        // 8: auth.SignOutResponse
	(*RefreshTokensRequest)(nil),   // 9: auth.RefreshTokensRequest
	(*RefreshTokensResponse)(nil),  // 10: auth.RefreshTokensResponse
	(OSType)(0),                    // 11: osType.OSType
	(*Error)(nil),                  // 12: error.Error
}
var file_proto_auth_auth_endpoint_proto_depIdxs = []int32{
	11, // 0: auth.DeviceInformation.nameOS:type_name -> osType.OSType
	1,  // 1: auth.SignInRequest.application:type_name -> auth.ApplicationInformation
	2,  // 2: auth.SignInRequest.device:type_name -> auth.DeviceInformation
	12, // 3: auth.SignInResponse.error:type_name -> error.Error
	0,  // 4: auth.SignInResponse.token:type_name -> auth.Tokens
	1,  // 5: auth.SignUpRequest.application:type_name -> auth.ApplicationInformation
	2,  // 6: auth.SignUpRequest.device:type_name -> auth.DeviceInformation
	12, // 7: auth.SignUpResponse.error:type_name -> error.Error
	0,  // 8: auth.SignUpResponse.token:type_name -> auth.Tokens
	12, // 9: auth.SignOutResponse.error:type_name -> error.Error
	1,  // 10: auth.RefreshTokensRequest.application:type_name -> auth.ApplicationInformation
	2,  // 11: auth.RefreshTokensRequest.device:type_name -> auth.DeviceInformation
	12, // 12: auth.RefreshTokensResponse.error:type_name -> error.Error
	3,  // 13: auth.AuthEndpoint.SignIn:input_type -> auth.SignInRequest
	5,  // 14: auth.AuthEndpoint.SignUp:input_type -> auth.SignUpRequest
	7,  // 15: auth.AuthEndpoint.SignOut:input_type -> auth.SignOutRequest
	9,  // 16: auth.AuthEndpoint.RefreshTokens:input_type -> auth.RefreshTokensRequest
	4,  // 17: auth.AuthEndpoint.SignIn:output_type -> auth.SignInResponse
	6,  // 18: auth.AuthEndpoint.SignUp:output_type -> auth.SignUpResponse
	8,  // 19: auth.AuthEndpoint.SignOut:output_type -> auth.SignOutResponse
	10, // 20: auth.AuthEndpoint.RefreshTokens:output_type -> auth.RefreshTokensResponse
	17, // [17:21] is the sub-list for method output_type
	13, // [13:17] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_proto_auth_auth_endpoint_proto_init() }
func file_proto_auth_auth_endpoint_proto_init() {
	if File_proto_auth_auth_endpoint_proto != nil {
		return
	}
	file_proto_error_error_proto_init()
	file_proto_enums_osType_proto_init()
	file_proto_auth_auth_endpoint_proto_msgTypes[4].OneofWrappers = []any{}
	file_proto_auth_auth_endpoint_proto_msgTypes[6].OneofWrappers = []any{}
	file_proto_auth_auth_endpoint_proto_msgTypes[8].OneofWrappers = []any{}
	file_proto_auth_auth_endpoint_proto_msgTypes[9].OneofWrappers = []any{}
	file_proto_auth_auth_endpoint_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_auth_auth_endpoint_proto_rawDesc), len(file_proto_auth_auth_endpoint_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_auth_auth_endpoint_proto_goTypes,
		DependencyIndexes: file_proto_auth_auth_endpoint_proto_depIdxs,
		MessageInfos:      file_proto_auth_auth_endpoint_proto_msgTypes,
	}.Build()
	File_proto_auth_auth_endpoint_proto = out.File
	file_proto_auth_auth_endpoint_proto_goTypes = nil
	file_proto_auth_auth_endpoint_proto_depIdxs = nil
}
