// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: proto/enums/currency.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Currency int32

const (
	Currency_Unspecified Currency = 0
	Currency_RUB         Currency = 1
	Currency_USD         Currency = 2
)

// Enum value maps for Currency.
var (
	Currency_name = map[int32]string{
		0: "Unspecified",
		1: "RUB",
		2: "USD",
	}
	Currency_value = map[string]int32{
		"Unspecified": 0,
		"RUB":         1,
		"USD":         2,
	}
)

func (x Currency) Enum() *Currency {
	p := new(Currency)
	*p = x
	return p
}

func (x Currency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Currency) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_enums_currency_proto_enumTypes[0].Descriptor()
}

func (Currency) Type() protoreflect.EnumType {
	return &file_proto_enums_currency_proto_enumTypes[0]
}

func (x Currency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Currency.Descriptor instead.
func (Currency) EnumDescriptor() ([]byte, []int) {
	return file_proto_enums_currency_proto_rawDescGZIP(), []int{0}
}

var File_proto_enums_currency_proto protoreflect.FileDescriptor

const file_proto_enums_currency_proto_rawDesc = "" +
	"\n" +
	"\x1aproto/enums/currency.proto\x12\bcurrency*-\n" +
	"\bCurrency\x12\x0f\n" +
	"\vUnspecified\x10\x00\x12\a\n" +
	"\x03RUB\x10\x01\x12\a\n" +
	"\x03USD\x10\x02B\bZ\x06/protob\x06proto3"

var (
	file_proto_enums_currency_proto_rawDescOnce sync.Once
	file_proto_enums_currency_proto_rawDescData []byte
)

func file_proto_enums_currency_proto_rawDescGZIP() []byte {
	file_proto_enums_currency_proto_rawDescOnce.Do(func() {
		file_proto_enums_currency_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_enums_currency_proto_rawDesc), len(file_proto_enums_currency_proto_rawDesc)))
	})
	return file_proto_enums_currency_proto_rawDescData
}

var file_proto_enums_currency_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_enums_currency_proto_goTypes = []any{
	(Currency)(0), // 0: currency.Currency
}
var file_proto_enums_currency_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_enums_currency_proto_init() }
func file_proto_enums_currency_proto_init() {
	if File_proto_enums_currency_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_enums_currency_proto_rawDesc), len(file_proto_enums_currency_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_enums_currency_proto_goTypes,
		DependencyIndexes: file_proto_enums_currency_proto_depIdxs,
		EnumInfos:         file_proto_enums_currency_proto_enumTypes,
	}.Build()
	File_proto_enums_currency_proto = out.File
	file_proto_enums_currency_proto_goTypes = nil
	file_proto_enums_currency_proto_depIdxs = nil
}
