// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: proto/enums/errorCategory.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCategory int32

const (
	ErrorCategory_Unspecified        ErrorCategory = 0
	ErrorCategory_Internal           ErrorCategory = 1 // Внутренняя ошибка сервера
	ErrorCategory_NeedToLogout       ErrorCategory = 2 // Требуется разлогинить пользователя
	ErrorCategory_NeedToSync         ErrorCategory = 3 // Требуется синхронизация устройства
	ErrorCategory_Other              ErrorCategory = 4 // Прочие ошибки
	ErrorCategory_NeedToRefreshToken ErrorCategory = 5 // Требуется обновить access-токен
)

// Enum value maps for ErrorCategory.
var (
	ErrorCategory_name = map[int32]string{
		0: "Unspecified",
		1: "Internal",
		2: "NeedToLogout",
		3: "NeedToSync",
		4: "Other",
		5: "NeedToRefreshToken",
	}
	ErrorCategory_value = map[string]int32{
		"Unspecified":        0,
		"Internal":           1,
		"NeedToLogout":       2,
		"NeedToSync":         3,
		"Other":              4,
		"NeedToRefreshToken": 5,
	}
)

func (x ErrorCategory) Enum() *ErrorCategory {
	p := new(ErrorCategory)
	*p = x
	return p
}

func (x ErrorCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_enums_errorCategory_proto_enumTypes[0].Descriptor()
}

func (ErrorCategory) Type() protoreflect.EnumType {
	return &file_proto_enums_errorCategory_proto_enumTypes[0]
}

func (x ErrorCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCategory.Descriptor instead.
func (ErrorCategory) EnumDescriptor() ([]byte, []int) {
	return file_proto_enums_errorCategory_proto_rawDescGZIP(), []int{0}
}

var File_proto_enums_errorCategory_proto protoreflect.FileDescriptor

const file_proto_enums_errorCategory_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/enums/errorCategory.proto\x12\rerrorCategory*s\n" +
	"\rErrorCategory\x12\x0f\n" +
	"\vUnspecified\x10\x00\x12\f\n" +
	"\bInternal\x10\x01\x12\x10\n" +
	"\fNeedToLogout\x10\x02\x12\x0e\n" +
	"\n" +
	"NeedToSync\x10\x03\x12\t\n" +
	"\x05Other\x10\x04\x12\x16\n" +
	"\x12NeedToRefreshToken\x10\x05B\bZ\x06/protob\x06proto3"

var (
	file_proto_enums_errorCategory_proto_rawDescOnce sync.Once
	file_proto_enums_errorCategory_proto_rawDescData []byte
)

func file_proto_enums_errorCategory_proto_rawDescGZIP() []byte {
	file_proto_enums_errorCategory_proto_rawDescOnce.Do(func() {
		file_proto_enums_errorCategory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_enums_errorCategory_proto_rawDesc), len(file_proto_enums_errorCategory_proto_rawDesc)))
	})
	return file_proto_enums_errorCategory_proto_rawDescData
}

var file_proto_enums_errorCategory_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_enums_errorCategory_proto_goTypes = []any{
	(ErrorCategory)(0), // 0: errorCategory.ErrorCategory
}
var file_proto_enums_errorCategory_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_enums_errorCategory_proto_init() }
func file_proto_enums_errorCategory_proto_init() {
	if File_proto_enums_errorCategory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_enums_errorCategory_proto_rawDesc), len(file_proto_enums_errorCategory_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_enums_errorCategory_proto_goTypes,
		DependencyIndexes: file_proto_enums_errorCategory_proto_depIdxs,
		EnumInfos:         file_proto_enums_errorCategory_proto_enumTypes,
	}.Build()
	File_proto_enums_errorCategory_proto = out.File
	file_proto_enums_errorCategory_proto_goTypes = nil
	file_proto_enums_errorCategory_proto_depIdxs = nil
}
