// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: proto/enums/osType.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OSType int32

const (
	OSType_Unspecified OSType = 0
	OSType_Android     OSType = 1
	OSType_IOS         OSType = 2
	OSType_IPadOS      OSType = 3
	OSType_OSX         OSType = 4
	OSType_WatchOS     OSType = 5
)

// Enum value maps for OSType.
var (
	OSType_name = map[int32]string{
		0: "Unspecified",
		1: "Android",
		2: "IOS",
		3: "IPadOS",
		4: "OSX",
		5: "WatchOS",
	}
	OSType_value = map[string]int32{
		"Unspecified": 0,
		"Android":     1,
		"IOS":         2,
		"IPadOS":      3,
		"OSX":         4,
		"WatchOS":     5,
	}
)

func (x OSType) Enum() *OSType {
	p := new(OSType)
	*p = x
	return p
}

func (x OSType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OSType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_enums_osType_proto_enumTypes[0].Descriptor()
}

func (OSType) Type() protoreflect.EnumType {
	return &file_proto_enums_osType_proto_enumTypes[0]
}

func (x OSType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OSType.Descriptor instead.
func (OSType) EnumDescriptor() ([]byte, []int) {
	return file_proto_enums_osType_proto_rawDescGZIP(), []int{0}
}

var File_proto_enums_osType_proto protoreflect.FileDescriptor

const file_proto_enums_osType_proto_rawDesc = "" +
	"\n" +
	"\x18proto/enums/osType.proto\x12\x06osType*Q\n" +
	"\x06OSType\x12\x0f\n" +
	"\vUnspecified\x10\x00\x12\v\n" +
	"\aAndroid\x10\x01\x12\a\n" +
	"\x03IOS\x10\x02\x12\n" +
	"\n" +
	"\x06IPadOS\x10\x03\x12\a\n" +
	"\x03OSX\x10\x04\x12\v\n" +
	"\aWatchOS\x10\x05B\bZ\x06/protob\x06proto3"

var (
	file_proto_enums_osType_proto_rawDescOnce sync.Once
	file_proto_enums_osType_proto_rawDescData []byte
)

func file_proto_enums_osType_proto_rawDescGZIP() []byte {
	file_proto_enums_osType_proto_rawDescOnce.Do(func() {
		file_proto_enums_osType_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_enums_osType_proto_rawDesc), len(file_proto_enums_osType_proto_rawDesc)))
	})
	return file_proto_enums_osType_proto_rawDescData
}

var file_proto_enums_osType_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_enums_osType_proto_goTypes = []any{
	(OSType)(0), // 0: osType.OSType
}
var file_proto_enums_osType_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_enums_osType_proto_init() }
func file_proto_enums_osType_proto_init() {
	if File_proto_enums_osType_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_enums_osType_proto_rawDesc), len(file_proto_enums_osType_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_enums_osType_proto_goTypes,
		DependencyIndexes: file_proto_enums_osType_proto_depIdxs,
		EnumInfos:         file_proto_enums_osType_proto_enumTypes,
	}.Build()
	File_proto_enums_osType_proto = out.File
	file_proto_enums_osType_proto_goTypes = nil
	file_proto_enums_osType_proto_depIdxs = nil
}
