// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/pendingLinkedTransfer/pendingLinkedTransfer-endpoint.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PendingLinkedTransferEndpoint_GetPendingLinkedTransfers_FullMethodName   = "/pendingLinkedTransfer.PendingLinkedTransferEndpoint/GetPendingLinkedTransfers"
	PendingLinkedTransferEndpoint_CreatePendingLinkedTransfer_FullMethodName = "/pendingLinkedTransfer.PendingLinkedTransferEndpoint/CreatePendingLinkedTransfer"
	PendingLinkedTransferEndpoint_UpdatePendingLinkedTransfer_FullMethodName = "/pendingLinkedTransfer.PendingLinkedTransferEndpoint/UpdatePendingLinkedTransfer"
	PendingLinkedTransferEndpoint_DeletePendingLinkedTransfer_FullMethodName = "/pendingLinkedTransfer.PendingLinkedTransferEndpoint/DeletePendingLinkedTransfer"
)

// PendingLinkedTransferEndpointClient is the client API for PendingLinkedTransferEndpoint service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Бэкенд для этой сущности — тупая точка правды с CRUD, без проверок доступа/членства в группе:
// вся оркестрация (когда создавать перенос, кому он адресован) — на фронтенде.
type PendingLinkedTransferEndpointClient interface {
	// GetPendingLinkedTransfers получение переносов по фильтрам
	GetPendingLinkedTransfers(ctx context.Context, in *GetPendingLinkedTransfersRequest, opts ...grpc.CallOption) (*GetPendingLinkedTransfersResponse, error)
	// CreatePendingLinkedTransfer создаёт требование довнесения
	CreatePendingLinkedTransfer(ctx context.Context, in *CreatePendingLinkedTransferRequest, opts ...grpc.CallOption) (*CreatePendingLinkedTransferResponse, error)
	// UpdatePendingLinkedTransfer меняет статус переноса (Completed/Ignored)
	UpdatePendingLinkedTransfer(ctx context.Context, in *UpdatePendingLinkedTransferRequest, opts ...grpc.CallOption) (*UpdatePendingLinkedTransferResponse, error)
	// DeletePendingLinkedTransfer удаляет перенос (например, если удалили саму транзакцию-инициатор)
	DeletePendingLinkedTransfer(ctx context.Context, in *DeletePendingLinkedTransferRequest, opts ...grpc.CallOption) (*DeletePendingLinkedTransferResponse, error)
}

type pendingLinkedTransferEndpointClient struct {
	cc grpc.ClientConnInterface
}

func NewPendingLinkedTransferEndpointClient(cc grpc.ClientConnInterface) PendingLinkedTransferEndpointClient {
	return &pendingLinkedTransferEndpointClient{cc}
}

func (c *pendingLinkedTransferEndpointClient) GetPendingLinkedTransfers(ctx context.Context, in *GetPendingLinkedTransfersRequest, opts ...grpc.CallOption) (*GetPendingLinkedTransfersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPendingLinkedTransfersResponse)
	err := c.cc.Invoke(ctx, PendingLinkedTransferEndpoint_GetPendingLinkedTransfers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pendingLinkedTransferEndpointClient) CreatePendingLinkedTransfer(ctx context.Context, in *CreatePendingLinkedTransferRequest, opts ...grpc.CallOption) (*CreatePendingLinkedTransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePendingLinkedTransferResponse)
	err := c.cc.Invoke(ctx, PendingLinkedTransferEndpoint_CreatePendingLinkedTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pendingLinkedTransferEndpointClient) UpdatePendingLinkedTransfer(ctx context.Context, in *UpdatePendingLinkedTransferRequest, opts ...grpc.CallOption) (*UpdatePendingLinkedTransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePendingLinkedTransferResponse)
	err := c.cc.Invoke(ctx, PendingLinkedTransferEndpoint_UpdatePendingLinkedTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pendingLinkedTransferEndpointClient) DeletePendingLinkedTransfer(ctx context.Context, in *DeletePendingLinkedTransferRequest, opts ...grpc.CallOption) (*DeletePendingLinkedTransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePendingLinkedTransferResponse)
	err := c.cc.Invoke(ctx, PendingLinkedTransferEndpoint_DeletePendingLinkedTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PendingLinkedTransferEndpointServer is the server API for PendingLinkedTransferEndpoint service.
// All implementations must embed UnimplementedPendingLinkedTransferEndpointServer
// for forward compatibility.
//
// Бэкенд для этой сущности — тупая точка правды с CRUD, без проверок доступа/членства в группе:
// вся оркестрация (когда создавать перенос, кому он адресован) — на фронтенде.
type PendingLinkedTransferEndpointServer interface {
	// GetPendingLinkedTransfers получение переносов по фильтрам
	GetPendingLinkedTransfers(context.Context, *GetPendingLinkedTransfersRequest) (*GetPendingLinkedTransfersResponse, error)
	// CreatePendingLinkedTransfer создаёт требование довнесения
	CreatePendingLinkedTransfer(context.Context, *CreatePendingLinkedTransferRequest) (*CreatePendingLinkedTransferResponse, error)
	// UpdatePendingLinkedTransfer меняет статус переноса (Completed/Ignored)
	UpdatePendingLinkedTransfer(context.Context, *UpdatePendingLinkedTransferRequest) (*UpdatePendingLinkedTransferResponse, error)
	// DeletePendingLinkedTransfer удаляет перенос (например, если удалили саму транзакцию-инициатор)
	DeletePendingLinkedTransfer(context.Context, *DeletePendingLinkedTransferRequest) (*DeletePendingLinkedTransferResponse, error)
	mustEmbedUnimplementedPendingLinkedTransferEndpointServer()
}

// UnimplementedPendingLinkedTransferEndpointServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPendingLinkedTransferEndpointServer struct{}

func (UnimplementedPendingLinkedTransferEndpointServer) GetPendingLinkedTransfers(context.Context, *GetPendingLinkedTransfersRequest) (*GetPendingLinkedTransfersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPendingLinkedTransfers not implemented")
}
func (UnimplementedPendingLinkedTransferEndpointServer) CreatePendingLinkedTransfer(context.Context, *CreatePendingLinkedTransferRequest) (*CreatePendingLinkedTransferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePendingLinkedTransfer not implemented")
}
func (UnimplementedPendingLinkedTransferEndpointServer) UpdatePendingLinkedTransfer(context.Context, *UpdatePendingLinkedTransferRequest) (*UpdatePendingLinkedTransferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePendingLinkedTransfer not implemented")
}
func (UnimplementedPendingLinkedTransferEndpointServer) DeletePendingLinkedTransfer(context.Context, *DeletePendingLinkedTransferRequest) (*DeletePendingLinkedTransferResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePendingLinkedTransfer not implemented")
}
func (UnimplementedPendingLinkedTransferEndpointServer) mustEmbedUnimplementedPendingLinkedTransferEndpointServer() {
}
func (UnimplementedPendingLinkedTransferEndpointServer) testEmbeddedByValue() {}

// UnsafePendingLinkedTransferEndpointServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PendingLinkedTransferEndpointServer will
// result in compilation errors.
type UnsafePendingLinkedTransferEndpointServer interface {
	mustEmbedUnimplementedPendingLinkedTransferEndpointServer()
}

func RegisterPendingLinkedTransferEndpointServer(s grpc.ServiceRegistrar, srv PendingLinkedTransferEndpointServer) {
	// If the following call panics, it indicates UnimplementedPendingLinkedTransferEndpointServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PendingLinkedTransferEndpoint_ServiceDesc, srv)
}

func _PendingLinkedTransferEndpoint_GetPendingLinkedTransfers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPendingLinkedTransfersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PendingLinkedTransferEndpointServer).GetPendingLinkedTransfers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PendingLinkedTransferEndpoint_GetPendingLinkedTransfers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PendingLinkedTransferEndpointServer).GetPendingLinkedTransfers(ctx, req.(*GetPendingLinkedTransfersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PendingLinkedTransferEndpoint_CreatePendingLinkedTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePendingLinkedTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PendingLinkedTransferEndpointServer).CreatePendingLinkedTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PendingLinkedTransferEndpoint_CreatePendingLinkedTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PendingLinkedTransferEndpointServer).CreatePendingLinkedTransfer(ctx, req.(*CreatePendingLinkedTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PendingLinkedTransferEndpoint_UpdatePendingLinkedTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePendingLinkedTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PendingLinkedTransferEndpointServer).UpdatePendingLinkedTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PendingLinkedTransferEndpoint_UpdatePendingLinkedTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PendingLinkedTransferEndpointServer).UpdatePendingLinkedTransfer(ctx, req.(*UpdatePendingLinkedTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PendingLinkedTransferEndpoint_DeletePendingLinkedTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePendingLinkedTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PendingLinkedTransferEndpointServer).DeletePendingLinkedTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PendingLinkedTransferEndpoint_DeletePendingLinkedTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PendingLinkedTransferEndpointServer).DeletePendingLinkedTransfer(ctx, req.(*DeletePendingLinkedTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PendingLinkedTransferEndpoint_ServiceDesc is the grpc.ServiceDesc for PendingLinkedTransferEndpoint service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PendingLinkedTransferEndpoint_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pendingLinkedTransfer.PendingLinkedTransferEndpoint",
	HandlerType: (*PendingLinkedTransferEndpointServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPendingLinkedTransfers",
			Handler:    _PendingLinkedTransferEndpoint_GetPendingLinkedTransfers_Handler,
		},
		{
			MethodName: "CreatePendingLinkedTransfer",
			Handler:    _PendingLinkedTransferEndpoint_CreatePendingLinkedTransfer_Handler,
		},
		{
			MethodName: "UpdatePendingLinkedTransfer",
			Handler:    _PendingLinkedTransferEndpoint_UpdatePendingLinkedTransfer_Handler,
		},
		{
			MethodName: "DeletePendingLinkedTransfer",
			Handler:    _PendingLinkedTransferEndpoint_DeletePendingLinkedTransfer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/pendingLinkedTransfer/pendingLinkedTransfer-endpoint.proto",
}
