// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: proto/pendingLinkedTransfer/pendingLinkedTransfer-endpoint.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PendingLinkedTransfer struct {
	state               protoimpl.MessageState      `protogen:"open.v1"`
	Id                  []byte                      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                                                       // Идентификатор переноса
	Status              PendingLinkedTransferStatus `protobuf:"varint,2,opt,name=status,proto3,enum=pendingLinkedTransferStatus.PendingLinkedTransferStatus" json:"status,omitempty"` // Статус
	SourceTransactionID []byte                      `protobuf:"bytes,3,opt,name=sourceTransactionID,proto3" json:"sourceTransactionID,omitempty"`                                     // Транзакция-инициатор
	SourceAccountID     []byte                      `protobuf:"bytes,4,opt,name=sourceAccountID,proto3" json:"sourceAccountID,omitempty"`                                             // Счёт-мост со стороны источника
	TargetAccountID     []byte                      `protobuf:"bytes,5,opt,name=targetAccountID,proto3" json:"targetAccountID,omitempty"`                                             // Счёт-мост со стороны получателя
	AccountGroupID      []byte                      `protobuf:"bytes,6,opt,name=accountGroupID,proto3" json:"accountGroupID,omitempty"`                                               // Группа-источник (sourceAccountID/sourceTransactionID)
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PendingLinkedTransfer) Reset() {
	*x = PendingLinkedTransfer{}
	mi := &file_proto_pendingLinkedTransfer_pendingLinkedTransfer_endpoint_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingLinkedTransfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingLinkedTransfer) ProtoMessage() {}

func (x *PendingLinkedTransfer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pendingLinkedTransfer_pendingLinkedTransfer_endpoint_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingLinkedTransfer.ProtoReflect.Descriptor instead.
func (*PendingLinkedTransfer) Descriptor() ([]byte, []int) {
	return file_proto_pendingLinkedTransfer_pendingLinkedTransfer_endpoint_proto_rawDescGZIP(), []int{0}
}

func (x *PendingLinkedTransfer) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *PendingLinkedTransfer) GetStatus() PendingLinkedTransferStatus {
	if x != nil {
		return x.Status
	}
	return PendingLinkedTransferStatus_Unspecified
}

func (x *PendingLinkedTransfer) GetSourceTransactionID() []byte {
	if x != nil {
		return x.SourceTransactionID
	}
	return nil
}

func (x *PendingLinkedTransfer) GetSourceAccountID() []byte {
	if x != nil {
		return x.SourceAccountID
	}
	return nil
}

func (x *PendingLinkedTransfer) GetTargetAccountID() []byte {
	if x != nil {
		return x.TargetAccountID
	}
	return nil
}

func (x *PendingLinkedTransfer) GetAccountGroupID() []byte {
	if x != nil {
		return x.AccountGroupID
	}
	return nil
}

type GetPendingLinkedTransfersRequest struct {
	state            protoimpl.MessageState       `protogen:"open.v1"`
	AccessToken      string                       `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`                                                           // Токен доступа
	AccountGroupIDs  [][]byte                     `protobuf:"bytes,2,rep,name=accountGroupIDs,proto3" json:"accountGroupIDs,omitempty"`                                                   // Мои группы — вернёт переносы, где я источник
	TargetAccountIDs [][]byte                     `protobuf:"bytes,3,rep,name=targetAccountIDs,proto3" json:"targetAccountIDs,omitempty"`                                                 // Мои счета — вернёт переносы, где я получатель
	Status           *PendingLinkedTransferStatus `protobuf:"varint,4,opt,name=status,proto3,enum=pendingLinkedTransferStatus.PendingLinkedTransferStatus,oneof" json:"status,omitempty"` // Фильтр по статусу
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetPendingLinkedTransfersRequest) Reset() {
	*x = GetPendingLinkedTransfersRequest{}
	mi := &file_proto_pendingLinkedTransfer_pendingLinkedTransfer_endpoint_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPendingLinkedTransfersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingLinkedTransfersRequest) ProtoMessage() {}

func (x *GetPendingLinkedTransfersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pendingLinkedTransfer_pendingLinkedTransfer_endpoint_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingLinkedTransfersRequest.ProtoReflect.Descriptor instead.
func (*GetPendingLinkedTransfersRequest) Descriptor() ([]byte, []int) {
	return file_proto_pendingLinkedTransfer_pendingLinkedTransfer_endpoint_proto_rawDescGZIP(), []int{1}
}

func (x *GetPendingLinkedTransfersRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *GetPendingLinkedTransfersRequest) GetAccountGroupIDs() [][]byte {
	if x != nil {
		return x.AccountGroupIDs
	}
	return nil
}

func (x *GetPendingLinkedTransfersRequest) GetTargetAccountIDs() [][]byte {
	if x != nil {
		return x.TargetAccountIDs
	}
	return nil
}

func (x *GetPendingLinkedTransfersRequest) GetStatus() PendingLinkedTransferStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return PendingLinkedTransferStatus_Unspecified
}

type GetPendingLinkedTransfersResponse struct {
	state                  protoimpl.MessageState   `protogen:"open.v1"`
	Error                  *Error                   `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`                             // Объект ошибки
	PendingLinkedTransfers []*PendingLinkedTransfer `protobuf:"bytes,2,rep,name=pendingLinkedTransfers,proto3" json:"pendingLinkedTransfers,omitempty"` // Список переносов
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetPendingLinkedTransfersResponse) Reset() {
	*x = GetPendingLinkedTransfersResponse{}
	mi := &file_proto_pendingLinkedTransfer_pendingLinkedTransfer_endpoint_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPendingLinkedTransfersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPendingLinkedTransfersResponse) ProtoMessage() {}

func (x *GetPendingLinkedTransfersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pendingLinkedTransfer_pendingLinkedTransfer_endpoint_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPendingLinkedTransfersResponse.ProtoReflect.Descriptor instead.
func (*GetPendingLinkedTransfersResponse) Descriptor() ([]byte, []int) {
	return file_proto_pendingLinkedTransfer_pendingLinkedTransfer_endpoint_proto_rawDescGZIP(), []int{2}
}

func (x *GetPendingLinkedTransfersResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *GetPendingLinkedTransfersResponse) GetPendingLinkedTransfers() []*PendingLinkedTransfer {
	if x != nil {
		return x.PendingLinkedTransfers
	}
	return nil
}

type CreatePendingLinkedTransferRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	AccessToken         string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`                 // Токен доступа
	Id                  []byte                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`                                   // Идентификатор переноса
	SourceTransactionID []byte                 `protobuf:"bytes,3,opt,name=sourceTransactionID,proto3" json:"sourceTransactionID,omitempty"` // Транзакция-инициатор
	SourceAccountID     []byte                 `protobuf:"bytes,4,opt,name=sourceAccountID,proto3" json:"sourceAccountID,omitempty"`         // Счёт-мост со стороны источника
	TargetAccountID     []byte                 `protobuf:"bytes,5,opt,name=targetAccountID,proto3" json:"targetAccountID,omitempty"`         // Счёт-мост со стороны получателя (клиент уже знает его локально из Account.linkedAccountID)
	AccountGroupID      []byte                 `protobuf:"bytes,6,opt,name=accountGroupID,proto3" json:"accountGroupID,omitempty"`           // Группа-источник
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *CreatePendingLinkedTransferRequest) Reset() {
	*x = CreatePendingLinkedTransferRequest{}
	mi := &file_proto_pendingLinkedTransfer_pendingLinkedTransfer_endpoint_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePendingLinkedTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePendingLinkedTransferRequest) ProtoMessage() {}

func (x *CreatePendingLinkedTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pendingLinkedTransfer_pendingLinkedTransfer_endpoint_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePendingLinkedTransferRequest.ProtoReflect.Descriptor instead.
func (*CreatePendingLinkedTransferRequest) Descriptor() ([]byte, []int) {
	return file_proto_pendingLinkedTransfer_pendingLinkedTransfer_endpoint_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePendingLinkedTransferRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *CreatePendingLinkedTransferRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *CreatePendingLinkedTransferRequest) GetSourceTransactionID() []byte {
	if x != nil {
		return x.SourceTransactionID
	}
	return nil
}

func (x *CreatePendingLinkedTransferRequest) GetSourceAccountID() []byte {
	if x != nil {
		return x.SourceAccountID
	}
	return nil
}

func (x *CreatePendingLinkedTransferRequest) GetTargetAccountID() []byte {
	if x != nil {
		return x.TargetAccountID
	}
	return nil
}

func (x *CreatePendingLinkedTransferRequest) GetAccountGroupID() []byte {
	if x != nil {
		return x.AccountGroupID
	}
	return nil
}

type CreatePendingLinkedTransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"` // Объект ошибки
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePendingLinkedTransferResponse) Reset() {
	*x = CreatePendingLinkedTransferResponse{}
	mi := &file_proto_pendingLinkedTransfer_pendingLinkedTransfer_endpoint_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePendingLinkedTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePendingLinkedTransferResponse) ProtoMessage() {}

func (x *CreatePendingLinkedTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pendingLinkedTransfer_pendingLinkedTransfer_endpoint_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePendingLinkedTransferResponse.ProtoReflect.Descriptor instead.
func (*CreatePendingLinkedTransferResponse) Descriptor() ([]byte, []int) {
	return file_proto_pendingLinkedTransfer_pendingLinkedTransfer_endpoint_proto_rawDescGZIP(), []int{4}
}

func (x *CreatePendingLinkedTransferResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type UpdatePendingLinkedTransferRequest struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	AccessToken   string                       `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`                                                           // Токен доступа
	Id            []byte                       `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`                                                                             // Идентификатор переноса
	Status        *PendingLinkedTransferStatus `protobuf:"varint,3,opt,name=status,proto3,enum=pendingLinkedTransferStatus.PendingLinkedTransferStatus,oneof" json:"status,omitempty"` // Новый статус (Completed/Ignored), patch — отсутствие поля значит "не менять"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePendingLinkedTransferRequest) Reset() {
	*x = UpdatePendingLinkedTransferRequest{}
	mi := &file_proto_pendingLinkedTransfer_pendingLinkedTransfer_endpoint_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePendingLinkedTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePendingLinkedTransferRequest) ProtoMessage() {}

func (x *UpdatePendingLinkedTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pendingLinkedTransfer_pendingLinkedTransfer_endpoint_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePendingLinkedTransferRequest.ProtoReflect.Descriptor instead.
func (*UpdatePendingLinkedTransferRequest) Descriptor() ([]byte, []int) {
	return file_proto_pendingLinkedTransfer_pendingLinkedTransfer_endpoint_proto_rawDescGZIP(), []int{5}
}

func (x *UpdatePendingLinkedTransferRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *UpdatePendingLinkedTransferRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *UpdatePendingLinkedTransferRequest) GetStatus() PendingLinkedTransferStatus {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return PendingLinkedTransferStatus_Unspecified
}

type UpdatePendingLinkedTransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"` // Объект ошибки
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePendingLinkedTransferResponse) Reset() {
	*x = UpdatePendingLinkedTransferResponse{}
	mi := &file_proto_pendingLinkedTransfer_pendingLinkedTransfer_endpoint_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePendingLinkedTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePendingLinkedTransferResponse) ProtoMessage() {}

func (x *UpdatePendingLinkedTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pendingLinkedTransfer_pendingLinkedTransfer_endpoint_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePendingLinkedTransferResponse.ProtoReflect.Descriptor instead.
func (*UpdatePendingLinkedTransferResponse) Descriptor() ([]byte, []int) {
	return file_proto_pendingLinkedTransfer_pendingLinkedTransfer_endpoint_proto_rawDescGZIP(), []int{6}
}

func (x *UpdatePendingLinkedTransferResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type DeletePendingLinkedTransferRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"` // Токен доступа
	Id            []byte                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`                   // Идентификатор переноса
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePendingLinkedTransferRequest) Reset() {
	*x = DeletePendingLinkedTransferRequest{}
	mi := &file_proto_pendingLinkedTransfer_pendingLinkedTransfer_endpoint_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePendingLinkedTransferRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePendingLinkedTransferRequest) ProtoMessage() {}

func (x *DeletePendingLinkedTransferRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pendingLinkedTransfer_pendingLinkedTransfer_endpoint_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePendingLinkedTransferRequest.ProtoReflect.Descriptor instead.
func (*DeletePendingLinkedTransferRequest) Descriptor() ([]byte, []int) {
	return file_proto_pendingLinkedTransfer_pendingLinkedTransfer_endpoint_proto_rawDescGZIP(), []int{7}
}

func (x *DeletePendingLinkedTransferRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *DeletePendingLinkedTransferRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

type DeletePendingLinkedTransferResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"` // Объект ошибки
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePendingLinkedTransferResponse) Reset() {
	*x = DeletePendingLinkedTransferResponse{}
	mi := &file_proto_pendingLinkedTransfer_pendingLinkedTransfer_endpoint_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePendingLinkedTransferResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePendingLinkedTransferResponse) ProtoMessage() {}

func (x *DeletePendingLinkedTransferResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pendingLinkedTransfer_pendingLinkedTransfer_endpoint_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePendingLinkedTransferResponse.ProtoReflect.Descriptor instead.
func (*DeletePendingLinkedTransferResponse) Descriptor() ([]byte, []int) {
	return file_proto_pendingLinkedTransfer_pendingLinkedTransfer_endpoint_proto_rawDescGZIP(), []int{8}
}

func (x *DeletePendingLinkedTransferResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_proto_pendingLinkedTransfer_pendingLinkedTransfer_endpoint_proto protoreflect.FileDescriptor

const file_proto_pendingLinkedTransfer_pendingLinkedTransfer_endpoint_proto_rawDesc = "" +
	"\n" +
	"@proto/pendingLinkedTransfer/pendingLinkedTransfer-endpoint.proto\x12\x15pendingLinkedTransfer\x1a\x17proto/error/error.proto\x1a-proto/enums/pendingLinkedTransferStatus.proto\"\xa7\x02\n" +
	"\x15PendingLinkedTransfer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12P\n" +
	"\x06status\x18\x02 \x01(\x0e28.pendingLinkedTransferStatus.PendingLinkedTransferStatusR\x06status\x120\n" +
	"\x13sourceTransactionID\x18\x03 \x01(\fR\x13sourceTransactionID\x12(\n" +
	"\x0fsourceAccountID\x18\x04 \x01(\fR\x0fsourceAccountID\x12(\n" +
	"\x0ftargetAccountID\x18\x05 \x01(\fR\x0ftargetAccountID\x12&\n" +
	"\x0eaccountGroupID\x18\x06 \x01(\fR\x0eaccountGroupID\"\xfc\x01\n" +
	" GetPendingLinkedTransfersRequest\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\x12(\n" +
	"\x0faccountGroupIDs\x18\x02 \x03(\fR\x0faccountGroupIDs\x12*\n" +
	"\x10targetAccountIDs\x18\x03 \x03(\fR\x10targetAccountIDs\x12U\n" +
	"\x06status\x18\x04 \x01(\x0e28.pendingLinkedTransferStatus.PendingLinkedTransferStatusH\x00R\x06status\x88\x01\x01B\t\n" +
	"\a_status\"\xbc\x01\n" +
	"!GetPendingLinkedTransfersResponse\x12'\n" +
	"\x05error\x18\x01 \x01(\v2\f.error.ErrorH\x00R\x05error\x88\x01\x01\x12d\n" +
	"\x16pendingLinkedTransfers\x18\x02 \x03(\v2,.pendingLinkedTransfer.PendingLinkedTransferR\x16pendingLinkedTransfersB\b\n" +
	"\x06_error\"\x84\x02\n" +
	"\"CreatePendingLinkedTransferRequest\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\fR\x02id\x120\n" +
	"\x13sourceTransactionID\x18\x03 \x01(\fR\x13sourceTransactionID\x12(\n" +
	"\x0fsourceAccountID\x18\x04 \x01(\fR\x0fsourceAccountID\x12(\n" +
	"\x0ftargetAccountID\x18\x05 \x01(\fR\x0ftargetAccountID\x12&\n" +
	"\x0eaccountGroupID\x18\x06 \x01(\fR\x0eaccountGroupID\"X\n" +
	"#CreatePendingLinkedTransferResponse\x12'\n" +
	"\x05error\x18\x01 \x01(\v2\f.error.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\xb8\x01\n" +
	"\"UpdatePendingLinkedTransferRequest\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\fR\x02id\x12U\n" +
	"\x06status\x18\x03 \x01(\x0e28.pendingLinkedTransferStatus.PendingLinkedTransferStatusH\x00R\x06status\x88\x01\x01B\t\n" +
	"\a_status\"X\n" +
	"#UpdatePendingLinkedTransferResponse\x12'\n" +
	"\x05error\x18\x01 \x01(\v2\f.error.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"V\n" +
	"\"DeletePendingLinkedTransferRequest\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\fR\x02id\"X\n" +
	"#DeletePendingLinkedTransferResponse\x12'\n" +
	"\x05error\x18\x01 \x01(\v2\f.error.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error2\xfd\x04\n" +
	"\x1dPendingLinkedTransferEndpoint\x12\x90\x01\n" +
	"\x19GetPendingLinkedTransfers\x127.pendingLinkedTransfer.GetPendingLinkedTransfersRequest\x1a8.pendingLinkedTransfer.GetPendingLinkedTransfersResponse\"\x00\x12\x96\x01\n" +
	"\x1bCreatePendingLinkedTransfer\x129.pendingLinkedTransfer.CreatePendingLinkedTransferRequest\x1a:.pendingLinkedTransfer.CreatePendingLinkedTransferResponse\"\x00\x12\x96\x01\n" +
	"\x1bUpdatePendingLinkedTransfer\x129.pendingLinkedTransfer.UpdatePendingLinkedTransferRequest\x1a:.pendingLinkedTransfer.UpdatePendingLinkedTransferResponse\"\x00\x12\x96\x01\n" +
	"\x1bDeletePendingLinkedTransfer\x129.pendingLinkedTransfer.DeletePendingLinkedTransferRequest\x1a:.pendingLinkedTransfer.DeletePendingLinkedTransferResponse\"\x00B\bZ\x06/protob\x06proto3"

var (
	file_proto_pendingLinkedTransfer_pendingLinkedTransfer_endpoint_proto_rawDescOnce sync.Once
	file_proto_pendingLinkedTransfer_pendingLinkedTransfer_endpoint_proto_rawDescData []byte
)

func file_proto_pendingLinkedTransfer_pendingLinkedTransfer_endpoint_proto_rawDescGZIP() []byte {
	file_proto_pendingLinkedTransfer_pendingLinkedTransfer_endpoint_proto_rawDescOnce.Do(func() {
		file_proto_pendingLinkedTransfer_pendingLinkedTransfer_endpoint_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_pendingLinkedTransfer_pendingLinkedTransfer_endpoint_proto_rawDesc), len(file_proto_pendingLinkedTransfer_pendingLinkedTransfer_endpoint_proto_rawDesc)))
	})
	return file_proto_pendingLinkedTransfer_pendingLinkedTransfer_endpoint_proto_rawDescData
}

var file_proto_pendingLinkedTransfer_pendingLinkedTransfer_endpoint_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_pendingLinkedTransfer_pendingLinkedTransfer_endpoint_proto_goTypes = []any{
	(*PendingLinkedTransfer)(nil),               // 0: pendingLinkedTransfer.PendingLinkedTransfer
	(*GetPendingLinkedTransfersRequest)(nil),    // 1: pendingLinkedTransfer.GetPendingLinkedTransfersRequest
	(*GetPendingLinkedTransfersResponse)(nil),   // 2: pendingLinkedTransfer.GetPendingLinkedTransfersResponse
	(*CreatePendingLinkedTransferRequest)(nil),  // 3: pendingLinkedTransfer.CreatePendingLinkedTransferRequest
	(*CreatePendingLinkedTransferResponse)(nil), // 4: pendingLinkedTransfer.CreatePendingLinkedTransferResponse
	(*UpdatePendingLinkedTransferRequest)(nil),  // 5: pendingLinkedTransfer.UpdatePendingLinkedTransferRequest
	(*UpdatePendingLinkedTransferResponse)(nil), // 6: pendingLinkedTransfer.UpdatePendingLinkedTransferResponse
	(*DeletePendingLinkedTransferRequest)(nil),  // 7: pendingLinkedTransfer.DeletePendingLinkedTransferRequest
	(*DeletePendingLinkedTransferResponse)(nil), // 8: pendingLinkedTransfer.DeletePendingLinkedTransferResponse
	(PendingLinkedTransferStatus)(0),            // 9: pendingLinkedTransferStatus.PendingLinkedTransferStatus
	(*Error)(nil),                               // 10: error.Error
}
var file_proto_pendingLinkedTransfer_pendingLinkedTransfer_endpoint_proto_depIdxs = []int32{
	9,  // 0: pendingLinkedTransfer.PendingLinkedTransfer.status:type_name -> pendingLinkedTransferStatus.PendingLinkedTransferStatus
	9,  // 1: pendingLinkedTransfer.GetPendingLinkedTransfersRequest.status:type_name -> pendingLinkedTransferStatus.PendingLinkedTransferStatus
	10, // 2: pendingLinkedTransfer.GetPendingLinkedTransfersResponse.error:type_name -> error.Error
	0,  // 3: pendingLinkedTransfer.GetPendingLinkedTransfersResponse.pendingLinkedTransfers:type_name -> pendingLinkedTransfer.PendingLinkedTransfer
	10, // 4: pendingLinkedTransfer.CreatePendingLinkedTransferResponse.error:type_name -> error.Error
	9,  // 5: pendingLinkedTransfer.UpdatePendingLinkedTransferRequest.status:type_name -> pendingLinkedTransferStatus.PendingLinkedTransferStatus
	10, // 6: pendingLinkedTransfer.UpdatePendingLinkedTransferResponse.error:type_name -> error.Error
	10, // 7: pendingLinkedTransfer.DeletePendingLinkedTransferResponse.error:type_name -> error.Error
	1,  // 8: pendingLinkedTransfer.PendingLinkedTransferEndpoint.GetPendingLinkedTransfers:input_type -> pendingLinkedTransfer.GetPendingLinkedTransfersRequest
	3,  // 9: pendingLinkedTransfer.PendingLinkedTransferEndpoint.CreatePendingLinkedTransfer:input_type -> pendingLinkedTransfer.CreatePendingLinkedTransferRequest
	5,  // 10: pendingLinkedTransfer.PendingLinkedTransferEndpoint.UpdatePendingLinkedTransfer:input_type -> pendingLinkedTransfer.UpdatePendingLinkedTransferRequest
	7,  // 11: pendingLinkedTransfer.PendingLinkedTransferEndpoint.DeletePendingLinkedTransfer:input_type -> pendingLinkedTransfer.DeletePendingLinkedTransferRequest
	2,  // 12: pendingLinkedTransfer.PendingLinkedTransferEndpoint.GetPendingLinkedTransfers:output_type -> pendingLinkedTransfer.GetPendingLinkedTransfersResponse
	4,  // 13: pendingLinkedTransfer.PendingLinkedTransferEndpoint.CreatePendingLinkedTransfer:output_type -> pendingLinkedTransfer.CreatePendingLinkedTransferResponse
	6,  // 14: pendingLinkedTransfer.PendingLinkedTransferEndpoint.UpdatePendingLinkedTransfer:output_type -> pendingLinkedTransfer.UpdatePendingLinkedTransferResponse
	8,  // 15: pendingLinkedTransfer.PendingLinkedTransferEndpoint.DeletePendingLinkedTransfer:output_type -> pendingLinkedTransfer.DeletePendingLinkedTransferResponse
	12, // [12:16] is the sub-list for method output_type
	8,  // [8:12] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_pendingLinkedTransfer_pendingLinkedTransfer_endpoint_proto_init() }
func file_proto_pendingLinkedTransfer_pendingLinkedTransfer_endpoint_proto_init() {
	if File_proto_pendingLinkedTransfer_pendingLinkedTransfer_endpoint_proto != nil {
		return
	}
	file_proto_error_error_proto_init()
	file_proto_enums_pendingLinkedTransferStatus_proto_init()
	file_proto_pendingLinkedTransfer_pendingLinkedTransfer_endpoint_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_pendingLinkedTransfer_pendingLinkedTransfer_endpoint_proto_msgTypes[2].OneofWrappers = []any{}
	file_proto_pendingLinkedTransfer_pendingLinkedTransfer_endpoint_proto_msgTypes[4].OneofWrappers = []any{}
	file_proto_pendingLinkedTransfer_pendingLinkedTransfer_endpoint_proto_msgTypes[5].OneofWrappers = []any{}
	file_proto_pendingLinkedTransfer_pendingLinkedTransfer_endpoint_proto_msgTypes[6].OneofWrappers = []any{}
	file_proto_pendingLinkedTransfer_pendingLinkedTransfer_endpoint_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_pendingLinkedTransfer_pendingLinkedTransfer_endpoint_proto_rawDesc), len(file_proto_pendingLinkedTransfer_pendingLinkedTransfer_endpoint_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_pendingLinkedTransfer_pendingLinkedTransfer_endpoint_proto_goTypes,
		DependencyIndexes: file_proto_pendingLinkedTransfer_pendingLinkedTransfer_endpoint_proto_depIdxs,
		MessageInfos:      file_proto_pendingLinkedTransfer_pendingLinkedTransfer_endpoint_proto_msgTypes,
	}.Build()
	File_proto_pendingLinkedTransfer_pendingLinkedTransfer_endpoint_proto = out.File
	file_proto_pendingLinkedTransfer_pendingLinkedTransfer_endpoint_proto_goTypes = nil
	file_proto_pendingLinkedTransfer_pendingLinkedTransfer_endpoint_proto_depIdxs = nil
}
