// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: proto/enums/pendingLinkedTransferStatus.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PendingLinkedTransferStatus int32

const (
	PendingLinkedTransferStatus_Unspecified PendingLinkedTransferStatus = 0
	PendingLinkedTransferStatus_Pending     PendingLinkedTransferStatus = 1 // Ожидает довнесения получателем
	PendingLinkedTransferStatus_Completed   PendingLinkedTransferStatus = 2 // Получатель довнёс связанную транзакцию
	PendingLinkedTransferStatus_Ignored     PendingLinkedTransferStatus = 3 // Получатель пометил "не переносить" (не удаление — статус)
)

// Enum value maps for PendingLinkedTransferStatus.
var (
	PendingLinkedTransferStatus_name = map[int32]string{
		0: "Unspecified",
		1: "Pending",
		2: "Completed",
		3: "Ignored",
	}
	PendingLinkedTransferStatus_value = map[string]int32{
		"Unspecified": 0,
		"Pending":     1,
		"Completed":   2,
		"Ignored":     3,
	}
)

func (x PendingLinkedTransferStatus) Enum() *PendingLinkedTransferStatus {
	p := new(PendingLinkedTransferStatus)
	*p = x
	return p
}

func (x PendingLinkedTransferStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PendingLinkedTransferStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_enums_pendingLinkedTransferStatus_proto_enumTypes[0].Descriptor()
}

func (PendingLinkedTransferStatus) Type() protoreflect.EnumType {
	return &file_proto_enums_pendingLinkedTransferStatus_proto_enumTypes[0]
}

func (x PendingLinkedTransferStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PendingLinkedTransferStatus.Descriptor instead.
func (PendingLinkedTransferStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_enums_pendingLinkedTransferStatus_proto_rawDescGZIP(), []int{0}
}

var File_proto_enums_pendingLinkedTransferStatus_proto protoreflect.FileDescriptor

const file_proto_enums_pendingLinkedTransferStatus_proto_rawDesc = "" +
	"\n" +
	"-proto/enums/pendingLinkedTransferStatus.proto\x12\x1bpendingLinkedTransferStatus*W\n" +
	"\x1bPendingLinkedTransferStatus\x12\x0f\n" +
	"\vUnspecified\x10\x00\x12\v\n" +
	"\aPending\x10\x01\x12\r\n" +
	"\tCompleted\x10\x02\x12\v\n" +
	"\aIgnored\x10\x03B\bZ\x06/protob\x06proto3"

var (
	file_proto_enums_pendingLinkedTransferStatus_proto_rawDescOnce sync.Once
	file_proto_enums_pendingLinkedTransferStatus_proto_rawDescData []byte
)

func file_proto_enums_pendingLinkedTransferStatus_proto_rawDescGZIP() []byte {
	file_proto_enums_pendingLinkedTransferStatus_proto_rawDescOnce.Do(func() {
		file_proto_enums_pendingLinkedTransferStatus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_enums_pendingLinkedTransferStatus_proto_rawDesc), len(file_proto_enums_pendingLinkedTransferStatus_proto_rawDesc)))
	})
	return file_proto_enums_pendingLinkedTransferStatus_proto_rawDescData
}

var file_proto_enums_pendingLinkedTransferStatus_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_enums_pendingLinkedTransferStatus_proto_goTypes = []any{
	(PendingLinkedTransferStatus)(0), // 0: pendingLinkedTransferStatus.PendingLinkedTransferStatus
}
var file_proto_enums_pendingLinkedTransferStatus_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_enums_pendingLinkedTransferStatus_proto_init() }
func file_proto_enums_pendingLinkedTransferStatus_proto_init() {
	if File_proto_enums_pendingLinkedTransferStatus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_enums_pendingLinkedTransferStatus_proto_rawDesc), len(file_proto_enums_pendingLinkedTransferStatus_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_enums_pendingLinkedTransferStatus_proto_goTypes,
		DependencyIndexes: file_proto_enums_pendingLinkedTransferStatus_proto_depIdxs,
		EnumInfos:         file_proto_enums_pendingLinkedTransferStatus_proto_enumTypes,
	}.Build()
	File_proto_enums_pendingLinkedTransferStatus_proto = out.File
	file_proto_enums_pendingLinkedTransferStatus_proto_goTypes = nil
	file_proto_enums_pendingLinkedTransferStatus_proto_depIdxs = nil
}
