// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: proto/settings/settings-endpoint.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SettingsEndpoint_GetCurrencies_FullMethodName    = "/settings.SettingsEndpoint/GetCurrencies"
	SettingsEndpoint_GetIcons_FullMethodName         = "/settings.SettingsEndpoint/GetIcons"
	SettingsEndpoint_UpdateCurrencies_FullMethodName = "/settings.SettingsEndpoint/UpdateCurrencies"
	SettingsEndpoint_SendNotification_FullMethodName = "/settings.SettingsEndpoint/SendNotification"
	SettingsEndpoint_GetVersion_FullMethodName       = "/settings.SettingsEndpoint/GetVersion"
)

// SettingsEndpointClient is the client API for SettingsEndpoint service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SettingsEndpointClient interface {
	// GetCurrencies получение списка валют
	GetCurrencies(ctx context.Context, in *GetCurrenciesRequest, opts ...grpc.CallOption) (*GetCurrenciesResponse, error)
	// GetIcons получение иконок с их адресами
	GetIcons(ctx context.Context, in *GetIconsRequest, opts ...grpc.CallOption) (*GetIconsResponse, error)
	// UpdateCurrencies обновление курсов валют
	UpdateCurrencies(ctx context.Context, in *UpdateCurrenciesRequest, opts ...grpc.CallOption) (*UpdateCurrenciesResponse, error)
	// SendNotification отправка уведомления пользователю
	SendNotification(ctx context.Context, in *SendNotificationRequest, opts ...grpc.CallOption) (*SendNotificationResponse, error)
	// GetVersion получение текущей версии сервера
	GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*GetVersionResponse, error)
}

type settingsEndpointClient struct {
	cc grpc.ClientConnInterface
}

func NewSettingsEndpointClient(cc grpc.ClientConnInterface) SettingsEndpointClient {
	return &settingsEndpointClient{cc}
}

func (c *settingsEndpointClient) GetCurrencies(ctx context.Context, in *GetCurrenciesRequest, opts ...grpc.CallOption) (*GetCurrenciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCurrenciesResponse)
	err := c.cc.Invoke(ctx, SettingsEndpoint_GetCurrencies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settingsEndpointClient) GetIcons(ctx context.Context, in *GetIconsRequest, opts ...grpc.CallOption) (*GetIconsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIconsResponse)
	err := c.cc.Invoke(ctx, SettingsEndpoint_GetIcons_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settingsEndpointClient) UpdateCurrencies(ctx context.Context, in *UpdateCurrenciesRequest, opts ...grpc.CallOption) (*UpdateCurrenciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCurrenciesResponse)
	err := c.cc.Invoke(ctx, SettingsEndpoint_UpdateCurrencies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settingsEndpointClient) SendNotification(ctx context.Context, in *SendNotificationRequest, opts ...grpc.CallOption) (*SendNotificationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendNotificationResponse)
	err := c.cc.Invoke(ctx, SettingsEndpoint_SendNotification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *settingsEndpointClient) GetVersion(ctx context.Context, in *GetVersionRequest, opts ...grpc.CallOption) (*GetVersionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVersionResponse)
	err := c.cc.Invoke(ctx, SettingsEndpoint_GetVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SettingsEndpointServer is the server API for SettingsEndpoint service.
// All implementations must embed UnimplementedSettingsEndpointServer
// for forward compatibility.
type SettingsEndpointServer interface {
	// GetCurrencies получение списка валют
	GetCurrencies(context.Context, *GetCurrenciesRequest) (*GetCurrenciesResponse, error)
	// GetIcons получение иконок с их адресами
	GetIcons(context.Context, *GetIconsRequest) (*GetIconsResponse, error)
	// UpdateCurrencies обновление курсов валют
	UpdateCurrencies(context.Context, *UpdateCurrenciesRequest) (*UpdateCurrenciesResponse, error)
	// SendNotification отправка уведомления пользователю
	SendNotification(context.Context, *SendNotificationRequest) (*SendNotificationResponse, error)
	// GetVersion получение текущей версии сервера
	GetVersion(context.Context, *GetVersionRequest) (*GetVersionResponse, error)
	mustEmbedUnimplementedSettingsEndpointServer()
}

// UnimplementedSettingsEndpointServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSettingsEndpointServer struct{}

func (UnimplementedSettingsEndpointServer) GetCurrencies(context.Context, *GetCurrenciesRequest) (*GetCurrenciesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCurrencies not implemented")
}
func (UnimplementedSettingsEndpointServer) GetIcons(context.Context, *GetIconsRequest) (*GetIconsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIcons not implemented")
}
func (UnimplementedSettingsEndpointServer) UpdateCurrencies(context.Context, *UpdateCurrenciesRequest) (*UpdateCurrenciesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCurrencies not implemented")
}
func (UnimplementedSettingsEndpointServer) SendNotification(context.Context, *SendNotificationRequest) (*SendNotificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendNotification not implemented")
}
func (UnimplementedSettingsEndpointServer) GetVersion(context.Context, *GetVersionRequest) (*GetVersionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVersion not implemented")
}
func (UnimplementedSettingsEndpointServer) mustEmbedUnimplementedSettingsEndpointServer() {}
func (UnimplementedSettingsEndpointServer) testEmbeddedByValue()                          {}

// UnsafeSettingsEndpointServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SettingsEndpointServer will
// result in compilation errors.
type UnsafeSettingsEndpointServer interface {
	mustEmbedUnimplementedSettingsEndpointServer()
}

func RegisterSettingsEndpointServer(s grpc.ServiceRegistrar, srv SettingsEndpointServer) {
	// If the following call pancis, it indicates UnimplementedSettingsEndpointServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SettingsEndpoint_ServiceDesc, srv)
}

func _SettingsEndpoint_GetCurrencies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCurrenciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingsEndpointServer).GetCurrencies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettingsEndpoint_GetCurrencies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingsEndpointServer).GetCurrencies(ctx, req.(*GetCurrenciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettingsEndpoint_GetIcons_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIconsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingsEndpointServer).GetIcons(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettingsEndpoint_GetIcons_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingsEndpointServer).GetIcons(ctx, req.(*GetIconsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettingsEndpoint_UpdateCurrencies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCurrenciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingsEndpointServer).UpdateCurrencies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettingsEndpoint_UpdateCurrencies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingsEndpointServer).UpdateCurrencies(ctx, req.(*UpdateCurrenciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettingsEndpoint_SendNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendNotificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingsEndpointServer).SendNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettingsEndpoint_SendNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingsEndpointServer).SendNotification(ctx, req.(*SendNotificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SettingsEndpoint_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SettingsEndpointServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SettingsEndpoint_GetVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SettingsEndpointServer).GetVersion(ctx, req.(*GetVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SettingsEndpoint_ServiceDesc is the grpc.ServiceDesc for SettingsEndpoint service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SettingsEndpoint_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "settings.SettingsEndpoint",
	HandlerType: (*SettingsEndpointServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetCurrencies",
			Handler:    _SettingsEndpoint_GetCurrencies_Handler,
		},
		{
			MethodName: "GetIcons",
			Handler:    _SettingsEndpoint_GetIcons_Handler,
		},
		{
			MethodName: "UpdateCurrencies",
			Handler:    _SettingsEndpoint_UpdateCurrencies_Handler,
		},
		{
			MethodName: "SendNotification",
			Handler:    _SettingsEndpoint_SendNotification_Handler,
		},
		{
			MethodName: "GetVersion",
			Handler:    _SettingsEndpoint_GetVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/settings/settings-endpoint.proto",
}
