// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: proto/settings/settings-endpoint.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Currency struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsoCode       string                 `protobuf:"bytes,1,opt,name=isoCode,proto3" json:"isoCode,omitempty"` // Сигнатура валюты
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`       // Название валюты
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`   // Символ валюты
	Rate          float64                `protobuf:"fixed64,4,opt,name=rate,proto3" json:"rate,omitempty"`     // Курс валюты
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Currency) Reset() {
	*x = Currency{}
	mi := &file_proto_settings_settings_endpoint_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Currency) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Currency) ProtoMessage() {}

func (x *Currency) ProtoReflect() protoreflect.Message {
	mi := &file_proto_settings_settings_endpoint_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Currency.ProtoReflect.Descriptor instead.
func (*Currency) Descriptor() ([]byte, []int) {
	return file_proto_settings_settings_endpoint_proto_rawDescGZIP(), []int{0}
}

func (x *Currency) GetIsoCode() string {
	if x != nil {
		return x.IsoCode
	}
	return ""
}

func (x *Currency) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Currency) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *Currency) GetRate() float64 {
	if x != nil {
		return x.Rate
	}
	return 0
}

type Icon struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`       // ID иконки
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`   // Название иконки
	Image         []byte                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"` // Содержимое изображения (PNG/SVG/...)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Icon) Reset() {
	*x = Icon{}
	mi := &file_proto_settings_settings_endpoint_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Icon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Icon) ProtoMessage() {}

func (x *Icon) ProtoReflect() protoreflect.Message {
	mi := &file_proto_settings_settings_endpoint_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Icon.ProtoReflect.Descriptor instead.
func (*Icon) Descriptor() ([]byte, []int) {
	return file_proto_settings_settings_endpoint_proto_rawDescGZIP(), []int{1}
}

func (x *Icon) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Icon) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Icon) GetImage() []byte {
	if x != nil {
		return x.Image
	}
	return nil
}

type Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`            // Заголовок уведомления
	Subtitle      string                 `protobuf:"bytes,2,opt,name=subtitle,proto3" json:"subtitle,omitempty"`      // Подзаголовок уведомления
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`        // Сообщение уведомления
	BadgeCount    uint32                 `protobuf:"varint,4,opt,name=badgeCount,proto3" json:"badgeCount,omitempty"` // Индикатор какое значение показывать в бадже
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_proto_settings_settings_endpoint_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_proto_settings_settings_endpoint_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_proto_settings_settings_endpoint_proto_rawDescGZIP(), []int{2}
}

func (x *Notification) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Notification) GetSubtitle() string {
	if x != nil {
		return x.Subtitle
	}
	return ""
}

func (x *Notification) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Notification) GetBadgeCount() uint32 {
	if x != nil {
		return x.BadgeCount
	}
	return 0
}

type Version struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"` // Версия приложения
	Build         string                 `protobuf:"bytes,2,opt,name=build,proto3" json:"build,omitempty"`     // Номер сборки
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Version) Reset() {
	*x = Version{}
	mi := &file_proto_settings_settings_endpoint_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Version) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Version) ProtoMessage() {}

func (x *Version) ProtoReflect() protoreflect.Message {
	mi := &file_proto_settings_settings_endpoint_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Version.ProtoReflect.Descriptor instead.
func (*Version) Descriptor() ([]byte, []int) {
	return file_proto_settings_settings_endpoint_proto_rawDescGZIP(), []int{3}
}

func (x *Version) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Version) GetBuild() string {
	if x != nil {
		return x.Build
	}
	return ""
}

type GetCurrenciesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"` // Токен доступа
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrenciesRequest) Reset() {
	*x = GetCurrenciesRequest{}
	mi := &file_proto_settings_settings_endpoint_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrenciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrenciesRequest) ProtoMessage() {}

func (x *GetCurrenciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_settings_settings_endpoint_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrenciesRequest.ProtoReflect.Descriptor instead.
func (*GetCurrenciesRequest) Descriptor() ([]byte, []int) {
	return file_proto_settings_settings_endpoint_proto_rawDescGZIP(), []int{4}
}

func (x *GetCurrenciesRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type GetCurrenciesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`     // Объект ошибки
	Currencies    []*Currency            `protobuf:"bytes,2,rep,name=currencies,proto3" json:"currencies,omitempty"` // Список валют
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCurrenciesResponse) Reset() {
	*x = GetCurrenciesResponse{}
	mi := &file_proto_settings_settings_endpoint_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCurrenciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCurrenciesResponse) ProtoMessage() {}

func (x *GetCurrenciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_settings_settings_endpoint_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCurrenciesResponse.ProtoReflect.Descriptor instead.
func (*GetCurrenciesResponse) Descriptor() ([]byte, []int) {
	return file_proto_settings_settings_endpoint_proto_rawDescGZIP(), []int{5}
}

func (x *GetCurrenciesResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *GetCurrenciesResponse) GetCurrencies() []*Currency {
	if x != nil {
		return x.Currencies
	}
	return nil
}

type GetIconsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"` // Токен доступа
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIconsRequest) Reset() {
	*x = GetIconsRequest{}
	mi := &file_proto_settings_settings_endpoint_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIconsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIconsRequest) ProtoMessage() {}

func (x *GetIconsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_settings_settings_endpoint_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIconsRequest.ProtoReflect.Descriptor instead.
func (*GetIconsRequest) Descriptor() ([]byte, []int) {
	return file_proto_settings_settings_endpoint_proto_rawDescGZIP(), []int{6}
}

func (x *GetIconsRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type GetIconsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"` // Объект ошибки
	Icons         []*Icon                `protobuf:"bytes,2,rep,name=icons,proto3" json:"icons,omitempty"`       // Список иконок
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIconsResponse) Reset() {
	*x = GetIconsResponse{}
	mi := &file_proto_settings_settings_endpoint_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIconsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIconsResponse) ProtoMessage() {}

func (x *GetIconsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_settings_settings_endpoint_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIconsResponse.ProtoReflect.Descriptor instead.
func (*GetIconsResponse) Descriptor() ([]byte, []int) {
	return file_proto_settings_settings_endpoint_proto_rawDescGZIP(), []int{7}
}

func (x *GetIconsResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *GetIconsResponse) GetIcons() []*Icon {
	if x != nil {
		return x.Icons
	}
	return nil
}

type UpdateCurrenciesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"` // Токен доступа
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCurrenciesRequest) Reset() {
	*x = UpdateCurrenciesRequest{}
	mi := &file_proto_settings_settings_endpoint_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCurrenciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCurrenciesRequest) ProtoMessage() {}

func (x *UpdateCurrenciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_settings_settings_endpoint_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCurrenciesRequest.ProtoReflect.Descriptor instead.
func (*UpdateCurrenciesRequest) Descriptor() ([]byte, []int) {
	return file_proto_settings_settings_endpoint_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateCurrenciesRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type UpdateCurrenciesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"` // Объект ошибки
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCurrenciesResponse) Reset() {
	*x = UpdateCurrenciesResponse{}
	mi := &file_proto_settings_settings_endpoint_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCurrenciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCurrenciesResponse) ProtoMessage() {}

func (x *UpdateCurrenciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_settings_settings_endpoint_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCurrenciesResponse.ProtoReflect.Descriptor instead.
func (*UpdateCurrenciesResponse) Descriptor() ([]byte, []int) {
	return file_proto_settings_settings_endpoint_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateCurrenciesResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type SendNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`   // Токен доступа
	UserID        []byte                 `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`             // Идентификатор пользователя, которому отправить уведомление
	Notification  *Notification          `protobuf:"bytes,3,opt,name=notification,proto3" json:"notification,omitempty"` // Данные уведомления
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotificationRequest) Reset() {
	*x = SendNotificationRequest{}
	mi := &file_proto_settings_settings_endpoint_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationRequest) ProtoMessage() {}

func (x *SendNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_settings_settings_endpoint_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationRequest.ProtoReflect.Descriptor instead.
func (*SendNotificationRequest) Descriptor() ([]byte, []int) {
	return file_proto_settings_settings_endpoint_proto_rawDescGZIP(), []int{10}
}

func (x *SendNotificationRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *SendNotificationRequest) GetUserID() []byte {
	if x != nil {
		return x.UserID
	}
	return nil
}

func (x *SendNotificationRequest) GetNotification() *Notification {
	if x != nil {
		return x.Notification
	}
	return nil
}

type SendNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"` // Объект ошибки
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotificationResponse) Reset() {
	*x = SendNotificationResponse{}
	mi := &file_proto_settings_settings_endpoint_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationResponse) ProtoMessage() {}

func (x *SendNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_settings_settings_endpoint_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationResponse.ProtoReflect.Descriptor instead.
func (*SendNotificationResponse) Descriptor() ([]byte, []int) {
	return file_proto_settings_settings_endpoint_proto_rawDescGZIP(), []int{11}
}

func (x *SendNotificationResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetVersionRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ApplicationType ApplicationType        `protobuf:"varint,1,opt,name=applicationType,proto3,enum=applicationType.ApplicationType" json:"applicationType,omitempty"` // Тип приложения (ios, android, web)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetVersionRequest) Reset() {
	*x = GetVersionRequest{}
	mi := &file_proto_settings_settings_endpoint_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionRequest) ProtoMessage() {}

func (x *GetVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_settings_settings_endpoint_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionRequest.ProtoReflect.Descriptor instead.
func (*GetVersionRequest) Descriptor() ([]byte, []int) {
	return file_proto_settings_settings_endpoint_proto_rawDescGZIP(), []int{12}
}

func (x *GetVersionRequest) GetApplicationType() ApplicationType {
	if x != nil {
		return x.ApplicationType
	}
	return ApplicationType_Unspecified
}

type GetVersionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`     // Объект ошибки
	Version       *Version               `protobuf:"bytes,2,opt,name=version,proto3,oneof" json:"version,omitempty"` // Версия сервера
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionResponse) Reset() {
	*x = GetVersionResponse{}
	mi := &file_proto_settings_settings_endpoint_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionResponse) ProtoMessage() {}

func (x *GetVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_settings_settings_endpoint_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVersionResponse.ProtoReflect.Descriptor instead.
func (*GetVersionResponse) Descriptor() ([]byte, []int) {
	return file_proto_settings_settings_endpoint_proto_rawDescGZIP(), []int{13}
}

func (x *GetVersionResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *GetVersionResponse) GetVersion() *Version {
	if x != nil {
		return x.Version
	}
	return nil
}

var File_proto_settings_settings_endpoint_proto protoreflect.FileDescriptor

const file_proto_settings_settings_endpoint_proto_rawDesc = "" +
	"\n" +
	"&proto/settings/settings-endpoint.proto\x12\bsettings\x1a\x17proto/error/error.proto\x1a!proto/enums/applicationType.proto\"d\n" +
	"\bCurrency\x12\x18\n" +
	"\aisoCode\x18\x01 \x01(\tR\aisoCode\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04rate\x18\x04 \x01(\x01R\x04rate\"@\n" +
	"\x04Icon\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x03 \x01(\fR\x05image\"z\n" +
	"\fNotification\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x1a\n" +
	"\bsubtitle\x18\x02 \x01(\tR\bsubtitle\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1e\n" +
	"\n" +
	"badgeCount\x18\x04 \x01(\rR\n" +
	"badgeCount\"9\n" +
	"\aVersion\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x14\n" +
	"\x05build\x18\x02 \x01(\tR\x05build\"8\n" +
	"\x14GetCurrenciesRequest\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\"~\n" +
	"\x15GetCurrenciesResponse\x12'\n" +
	"\x05error\x18\x01 \x01(\v2\f.error.ErrorH\x00R\x05error\x88\x01\x01\x122\n" +
	"\n" +
	"currencies\x18\x02 \x03(\v2\x12.settings.CurrencyR\n" +
	"currenciesB\b\n" +
	"\x06_error\"3\n" +
	"\x0fGetIconsRequest\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\"k\n" +
	"\x10GetIconsResponse\x12'\n" +
	"\x05error\x18\x01 \x01(\v2\f.error.ErrorH\x00R\x05error\x88\x01\x01\x12$\n" +
	"\x05icons\x18\x02 \x03(\v2\x0e.settings.IconR\x05iconsB\b\n" +
	"\x06_error\";\n" +
	"\x17UpdateCurrenciesRequest\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\"M\n" +
	"\x18UpdateCurrenciesResponse\x12'\n" +
	"\x05error\x18\x01 \x01(\v2\f.error.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\x8f\x01\n" +
	"\x17SendNotificationRequest\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\x12\x16\n" +
	"\x06userID\x18\x02 \x01(\fR\x06userID\x12:\n" +
	"\fnotification\x18\x03 \x01(\v2\x16.settings.NotificationR\fnotification\"M\n" +
	"\x18SendNotificationResponse\x12'\n" +
	"\x05error\x18\x01 \x01(\v2\f.error.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"_\n" +
	"\x11GetVersionRequest\x12J\n" +
	"\x0fapplicationType\x18\x01 \x01(\x0e2 .applicationType.ApplicationTypeR\x0fapplicationType\"\x85\x01\n" +
	"\x12GetVersionResponse\x12'\n" +
	"\x05error\x18\x01 \x01(\v2\f.error.ErrorH\x00R\x05error\x88\x01\x01\x120\n" +
	"\aversion\x18\x02 \x01(\v2\x11.settings.VersionH\x01R\aversion\x88\x01\x01B\b\n" +
	"\x06_errorB\n" +
	"\n" +
	"\b_version2\xb0\x03\n" +
	"\x10SettingsEndpoint\x12R\n" +
	"\rGetCurrencies\x12\x1e.settings.GetCurrenciesRequest\x1a\x1f.settings.GetCurrenciesResponse\"\x00\x12C\n" +
	"\bGetIcons\x12\x19.settings.GetIconsRequest\x1a\x1a.settings.GetIconsResponse\"\x00\x12[\n" +
	"\x10UpdateCurrencies\x12!.settings.UpdateCurrenciesRequest\x1a\".settings.UpdateCurrenciesResponse\"\x00\x12[\n" +
	"\x10SendNotification\x12!.settings.SendNotificationRequest\x1a\".settings.SendNotificationResponse\"\x00\x12I\n" +
	"\n" +
	"GetVersion\x12\x1b.settings.GetVersionRequest\x1a\x1c.settings.GetVersionResponse\"\x00B\bZ\x06/protob\x06proto3"

var (
	file_proto_settings_settings_endpoint_proto_rawDescOnce sync.Once
	file_proto_settings_settings_endpoint_proto_rawDescData []byte
)

func file_proto_settings_settings_endpoint_proto_rawDescGZIP() []byte {
	file_proto_settings_settings_endpoint_proto_rawDescOnce.Do(func() {
		file_proto_settings_settings_endpoint_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_settings_settings_endpoint_proto_rawDesc), len(file_proto_settings_settings_endpoint_proto_rawDesc)))
	})
	return file_proto_settings_settings_endpoint_proto_rawDescData
}

var file_proto_settings_settings_endpoint_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_settings_settings_endpoint_proto_goTypes = []any{
	(*Currency)(nil),                 // 0: settings.Currency
	(*Icon)(nil),                     // 1: settings.Icon
	(*Notification)(nil),             // 2: settings.Notification
	(*Version)(nil),                  // 3: settings.Version
	(*GetCurrenciesRequest)(nil),     // 4: settings.GetCurrenciesRequest
	(*GetCurrenciesResponse)(nil),    // 5: settings.GetCurrenciesResponse
	(*GetIconsRequest)(nil),          // 6: settings.GetIconsRequest
	(*GetIconsResponse)(nil),         // 7: settings.GetIconsResponse
	(*UpdateCurrenciesRequest)(nil),  // 8: settings.UpdateCurrenciesRequest
	(*UpdateCurrenciesResponse)(nil), // 9: settings.UpdateCurrenciesResponse
	(*SendNotificationRequest)(nil),  // 10: settings.SendNotificationRequest
	(*SendNotificationResponse)(nil), // 11: settings.SendNotificationResponse
	(*GetVersionRequest)(nil),        // 12: settings.GetVersionRequest
	(*GetVersionResponse)(nil),       // 13: settings.GetVersionResponse
	(*Error)(nil),                    // 14: error.Error
	(ApplicationType)(0),             // 15: applicationType.ApplicationType
}
var file_proto_settings_settings_endpoint_proto_depIdxs = []int32{
	14, // 0: settings.GetCurrenciesResponse.error:type_name -> error.Error
	0,  // 1: settings.GetCurrenciesResponse.currencies:type_name -> settings.Currency
	14, // 2: settings.GetIconsResponse.error:type_name -> error.Error
	1,  // 3: settings.GetIconsResponse.icons:type_name -> settings.Icon
	14, // 4: settings.UpdateCurrenciesResponse.error:type_name -> error.Error
	2,  // 5: settings.SendNotificationRequest.notification:type_name -> settings.Notification
	14, // 6: settings.SendNotificationResponse.error:type_name -> error.Error
	15, // 7: settings.GetVersionRequest.applicationType:type_name -> applicationType.ApplicationType
	14, // 8: settings.GetVersionResponse.error:type_name -> error.Error
	3,  // 9: settings.GetVersionResponse.version:type_name -> settings.Version
	4,  // 10: settings.SettingsEndpoint.GetCurrencies:input_type -> settings.GetCurrenciesRequest
	6,  // 11: settings.SettingsEndpoint.GetIcons:input_type -> settings.GetIconsRequest
	8,  // 12: settings.SettingsEndpoint.UpdateCurrencies:input_type -> settings.UpdateCurrenciesRequest
	10, // 13: settings.SettingsEndpoint.SendNotification:input_type -> settings.SendNotificationRequest
	12, // 14: settings.SettingsEndpoint.GetVersion:input_type -> settings.GetVersionRequest
	5,  // 15: settings.SettingsEndpoint.GetCurrencies:output_type -> settings.GetCurrenciesResponse
	7,  // 16: settings.SettingsEndpoint.GetIcons:output_type -> settings.GetIconsResponse
	9,  // 17: settings.SettingsEndpoint.UpdateCurrencies:output_type -> settings.UpdateCurrenciesResponse
	11, // 18: settings.SettingsEndpoint.SendNotification:output_type -> settings.SendNotificationResponse
	13, // 19: settings.SettingsEndpoint.GetVersion:output_type -> settings.GetVersionResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_settings_settings_endpoint_proto_init() }
func file_proto_settings_settings_endpoint_proto_init() {
	if File_proto_settings_settings_endpoint_proto != nil {
		return
	}
	file_proto_error_error_proto_init()
	file_proto_enums_applicationType_proto_init()
	file_proto_settings_settings_endpoint_proto_msgTypes[5].OneofWrappers = []any{}
	file_proto_settings_settings_endpoint_proto_msgTypes[7].OneofWrappers = []any{}
	file_proto_settings_settings_endpoint_proto_msgTypes[9].OneofWrappers = []any{}
	file_proto_settings_settings_endpoint_proto_msgTypes[11].OneofWrappers = []any{}
	file_proto_settings_settings_endpoint_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_settings_settings_endpoint_proto_rawDesc), len(file_proto_settings_settings_endpoint_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_settings_settings_endpoint_proto_goTypes,
		DependencyIndexes: file_proto_settings_settings_endpoint_proto_depIdxs,
		MessageInfos:      file_proto_settings_settings_endpoint_proto_msgTypes,
	}.Build()
	File_proto_settings_settings_endpoint_proto = out.File
	file_proto_settings_settings_endpoint_proto_goTypes = nil
	file_proto_settings_settings_endpoint_proto_depIdxs = nil
}
