// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/sync/sync-endpoint.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SyncEndpoint_Sync_FullMethodName            = "/sync.SyncEndpoint/Sync"
	SyncEndpoint_ConfirmSync_FullMethodName     = "/sync.SyncEndpoint/ConfirmSync"
	SyncEndpoint_SubscribeToSync_FullMethodName = "/sync.SyncEndpoint/SubscribeToSync"
)

// SyncEndpointClient is the client API for SyncEndpoint service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SyncEndpointClient interface {
	// Sync атомарно получает все изменения, доступные пользователю по группам счетов, произошедшие
	// после чекпоинта, переданного клиентом. Хранение чекпоинта - на стороне клиента. Возвращённый
	// pendingCheckpoint/pendingSyncToken нужно подтвердить вызовом ConfirmSync после того, как
	// клиент корректно применит полученные изменения у себя
	Sync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error)
	// ConfirmSync подтверждает, что клиент корректно применил изменения, полученные последним
	// вызовом Sync, и просит бэкенд запомнить новый чекпоинт устройства
	ConfirmSync(ctx context.Context, in *ConfirmSyncRequest, opts ...grpc.CallOption) (*ConfirmSyncResponse, error)
	// SubscribeToSync — server-streaming уведомитель: держит соединение открытым и присылает
	// пустой SyncNotification каждый раз, когда для пользователя появились изменения (создана
	// новая релевантная запись аудит-лога). НЕ несёт сам payload изменений — получив сигнал,
	// клиент должен сам вызвать обычный Sync/ConfirmSync. Предназначен для мгновенного отклика,
	// пока приложение на переднем плане — клиент отключается при уходе в фон и переиспользует
	// обычный периодический Sync как fallback.
	SubscribeToSync(ctx context.Context, in *SubscribeToSyncRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SyncNotification], error)
}

type syncEndpointClient struct {
	cc grpc.ClientConnInterface
}

func NewSyncEndpointClient(cc grpc.ClientConnInterface) SyncEndpointClient {
	return &syncEndpointClient{cc}
}

func (c *syncEndpointClient) Sync(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncResponse)
	err := c.cc.Invoke(ctx, SyncEndpoint_Sync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncEndpointClient) ConfirmSync(ctx context.Context, in *ConfirmSyncRequest, opts ...grpc.CallOption) (*ConfirmSyncResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmSyncResponse)
	err := c.cc.Invoke(ctx, SyncEndpoint_ConfirmSync_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *syncEndpointClient) SubscribeToSync(ctx context.Context, in *SubscribeToSyncRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SyncNotification], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SyncEndpoint_ServiceDesc.Streams[0], SyncEndpoint_SubscribeToSync_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeToSyncRequest, SyncNotification]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SyncEndpoint_SubscribeToSyncClient = grpc.ServerStreamingClient[SyncNotification]

// SyncEndpointServer is the server API for SyncEndpoint service.
// All implementations must embed UnimplementedSyncEndpointServer
// for forward compatibility.
type SyncEndpointServer interface {
	// Sync атомарно получает все изменения, доступные пользователю по группам счетов, произошедшие
	// после чекпоинта, переданного клиентом. Хранение чекпоинта - на стороне клиента. Возвращённый
	// pendingCheckpoint/pendingSyncToken нужно подтвердить вызовом ConfirmSync после того, как
	// клиент корректно применит полученные изменения у себя
	Sync(context.Context, *SyncRequest) (*SyncResponse, error)
	// ConfirmSync подтверждает, что клиент корректно применил изменения, полученные последним
	// вызовом Sync, и просит бэкенд запомнить новый чекпоинт устройства
	ConfirmSync(context.Context, *ConfirmSyncRequest) (*ConfirmSyncResponse, error)
	// SubscribeToSync — server-streaming уведомитель: держит соединение открытым и присылает
	// пустой SyncNotification каждый раз, когда для пользователя появились изменения (создана
	// новая релевантная запись аудит-лога). НЕ несёт сам payload изменений — получив сигнал,
	// клиент должен сам вызвать обычный Sync/ConfirmSync. Предназначен для мгновенного отклика,
	// пока приложение на переднем плане — клиент отключается при уходе в фон и переиспользует
	// обычный периодический Sync как fallback.
	SubscribeToSync(*SubscribeToSyncRequest, grpc.ServerStreamingServer[SyncNotification]) error
	mustEmbedUnimplementedSyncEndpointServer()
}

// UnimplementedSyncEndpointServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSyncEndpointServer struct{}

func (UnimplementedSyncEndpointServer) Sync(context.Context, *SyncRequest) (*SyncResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Sync not implemented")
}
func (UnimplementedSyncEndpointServer) ConfirmSync(context.Context, *ConfirmSyncRequest) (*ConfirmSyncResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmSync not implemented")
}
func (UnimplementedSyncEndpointServer) SubscribeToSync(*SubscribeToSyncRequest, grpc.ServerStreamingServer[SyncNotification]) error {
	return status.Error(codes.Unimplemented, "method SubscribeToSync not implemented")
}
func (UnimplementedSyncEndpointServer) mustEmbedUnimplementedSyncEndpointServer() {}
func (UnimplementedSyncEndpointServer) testEmbeddedByValue()                      {}

// UnsafeSyncEndpointServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SyncEndpointServer will
// result in compilation errors.
type UnsafeSyncEndpointServer interface {
	mustEmbedUnimplementedSyncEndpointServer()
}

func RegisterSyncEndpointServer(s grpc.ServiceRegistrar, srv SyncEndpointServer) {
	// If the following call panics, it indicates UnimplementedSyncEndpointServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SyncEndpoint_ServiceDesc, srv)
}

func _SyncEndpoint_Sync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncEndpointServer).Sync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncEndpoint_Sync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncEndpointServer).Sync(ctx, req.(*SyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncEndpoint_ConfirmSync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmSyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SyncEndpointServer).ConfirmSync(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SyncEndpoint_ConfirmSync_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SyncEndpointServer).ConfirmSync(ctx, req.(*ConfirmSyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SyncEndpoint_SubscribeToSync_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeToSyncRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(SyncEndpointServer).SubscribeToSync(m, &grpc.GenericServerStream[SubscribeToSyncRequest, SyncNotification]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SyncEndpoint_SubscribeToSyncServer = grpc.ServerStreamingServer[SyncNotification]

// SyncEndpoint_ServiceDesc is the grpc.ServiceDesc for SyncEndpoint service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SyncEndpoint_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sync.SyncEndpoint",
	HandlerType: (*SyncEndpointServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Sync",
			Handler:    _SyncEndpoint_Sync_Handler,
		},
		{
			MethodName: "ConfirmSync",
			Handler:    _SyncEndpoint_ConfirmSync_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeToSync",
			Handler:       _SyncEndpoint_SubscribeToSync_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/sync/sync-endpoint.proto",
}
