// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: proto/tag/tag-endpoint.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tag struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                          // Идентификатор подкатегории
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                      // Название подкатегории
	AccountGroupID int32                  `protobuf:"varint,3,opt,name=accountGroupID,proto3" json:"accountGroupID,omitempty"` // Идентификатор группы счетов
	DatetimeCreate *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=datetimeCreate,proto3" json:"datetimeCreate,omitempty"`  // Дата и время создания
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Tag) Reset() {
	*x = Tag{}
	mi := &file_proto_tag_tag_endpoint_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tag) ProtoMessage() {}

func (x *Tag) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tag_tag_endpoint_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tag.ProtoReflect.Descriptor instead.
func (*Tag) Descriptor() ([]byte, []int) {
	return file_proto_tag_tag_endpoint_proto_rawDescGZIP(), []int{0}
}

func (x *Tag) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Tag) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Tag) GetAccountGroupID() int32 {
	if x != nil {
		return x.AccountGroupID
	}
	return 0
}

func (x *Tag) GetDatetimeCreate() *timestamppb.Timestamp {
	if x != nil {
		return x.DatetimeCreate
	}
	return nil
}

type GetTagsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccessToken     string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`                 // Токен доступа
	AccountGroupIDs []int32                `protobuf:"varint,2,rep,packed,name=accountGroupIDs,proto3" json:"accountGroupIDs,omitempty"` // Идентификаторы групп счетов
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetTagsRequest) Reset() {
	*x = GetTagsRequest{}
	mi := &file_proto_tag_tag_endpoint_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagsRequest) ProtoMessage() {}

func (x *GetTagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tag_tag_endpoint_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagsRequest.ProtoReflect.Descriptor instead.
func (*GetTagsRequest) Descriptor() ([]byte, []int) {
	return file_proto_tag_tag_endpoint_proto_rawDescGZIP(), []int{1}
}

func (x *GetTagsRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *GetTagsRequest) GetAccountGroupIDs() []int32 {
	if x != nil {
		return x.AccountGroupIDs
	}
	return nil
}

type GetTagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"` // Объект ошибки
	Tags          []*Tag                 `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`         // Список подкатегорий
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTagsResponse) Reset() {
	*x = GetTagsResponse{}
	mi := &file_proto_tag_tag_endpoint_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagsResponse) ProtoMessage() {}

func (x *GetTagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tag_tag_endpoint_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagsResponse.ProtoReflect.Descriptor instead.
func (*GetTagsResponse) Descriptor() ([]byte, []int) {
	return file_proto_tag_tag_endpoint_proto_rawDescGZIP(), []int{2}
}

func (x *GetTagsResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *GetTagsResponse) GetTags() []*Tag {
	if x != nil {
		return x.Tags
	}
	return nil
}

type CreateTagRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AccessToken    string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`        // Токен доступа
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                      // Название подкатегории
	AccountGroupID int32                  `protobuf:"varint,3,opt,name=accountGroupID,proto3" json:"accountGroupID,omitempty"` // Идентификатор группы счетов
	DatetimeCreate *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=datetimeCreate,proto3" json:"datetimeCreate,omitempty"`  // Дата создания подкатегории
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateTagRequest) Reset() {
	*x = CreateTagRequest{}
	mi := &file_proto_tag_tag_endpoint_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTagRequest) ProtoMessage() {}

func (x *CreateTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tag_tag_endpoint_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTagRequest.ProtoReflect.Descriptor instead.
func (*CreateTagRequest) Descriptor() ([]byte, []int) {
	return file_proto_tag_tag_endpoint_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTagRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *CreateTagRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTagRequest) GetAccountGroupID() int32 {
	if x != nil {
		return x.AccountGroupID
	}
	return 0
}

func (x *CreateTagRequest) GetDatetimeCreate() *timestamppb.Timestamp {
	if x != nil {
		return x.DatetimeCreate
	}
	return nil
}

type CreateTagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"` // Объект ошибки
	Id            []byte                 `protobuf:"bytes,2,opt,name=id,proto3,oneof" json:"id,omitempty"`       // Идентификатор подкатегории
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTagResponse) Reset() {
	*x = CreateTagResponse{}
	mi := &file_proto_tag_tag_endpoint_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTagResponse) ProtoMessage() {}

func (x *CreateTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tag_tag_endpoint_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTagResponse.ProtoReflect.Descriptor instead.
func (*CreateTagResponse) Descriptor() ([]byte, []int) {
	return file_proto_tag_tag_endpoint_proto_rawDescGZIP(), []int{4}
}

func (x *CreateTagResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *CreateTagResponse) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

type UpdateTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"` // Токен доступа
	Id            []byte                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`                   // Идентификатор подкатегории
	Name          *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"`         // Название подкатегории
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTagRequest) Reset() {
	*x = UpdateTagRequest{}
	mi := &file_proto_tag_tag_endpoint_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTagRequest) ProtoMessage() {}

func (x *UpdateTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tag_tag_endpoint_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTagRequest.ProtoReflect.Descriptor instead.
func (*UpdateTagRequest) Descriptor() ([]byte, []int) {
	return file_proto_tag_tag_endpoint_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateTagRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *UpdateTagRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *UpdateTagRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

type UpdateTagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"` // Объект ошибки
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTagResponse) Reset() {
	*x = UpdateTagResponse{}
	mi := &file_proto_tag_tag_endpoint_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTagResponse) ProtoMessage() {}

func (x *UpdateTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tag_tag_endpoint_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTagResponse.ProtoReflect.Descriptor instead.
func (*UpdateTagResponse) Descriptor() ([]byte, []int) {
	return file_proto_tag_tag_endpoint_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateTagResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type DeleteTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"` // Токен доступа
	Id            []byte                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`                   // Идентификатор подкатегории
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTagRequest) Reset() {
	*x = DeleteTagRequest{}
	mi := &file_proto_tag_tag_endpoint_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTagRequest) ProtoMessage() {}

func (x *DeleteTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tag_tag_endpoint_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTagRequest.ProtoReflect.Descriptor instead.
func (*DeleteTagRequest) Descriptor() ([]byte, []int) {
	return file_proto_tag_tag_endpoint_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteTagRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *DeleteTagRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

type DeleteTagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"` // Объект ошибки
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTagResponse) Reset() {
	*x = DeleteTagResponse{}
	mi := &file_proto_tag_tag_endpoint_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTagResponse) ProtoMessage() {}

func (x *DeleteTagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tag_tag_endpoint_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTagResponse.ProtoReflect.Descriptor instead.
func (*DeleteTagResponse) Descriptor() ([]byte, []int) {
	return file_proto_tag_tag_endpoint_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteTagResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type GetTagsToTransactionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"` // Токен доступа
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTagsToTransactionsRequest) Reset() {
	*x = GetTagsToTransactionsRequest{}
	mi := &file_proto_tag_tag_endpoint_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTagsToTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagsToTransactionsRequest) ProtoMessage() {}

func (x *GetTagsToTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tag_tag_endpoint_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagsToTransactionsRequest.ProtoReflect.Descriptor instead.
func (*GetTagsToTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_tag_tag_endpoint_proto_rawDescGZIP(), []int{9}
}

func (x *GetTagsToTransactionsRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type GetTagsToTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"` // Объект ошибки
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTagsToTransactionsResponse) Reset() {
	*x = GetTagsToTransactionsResponse{}
	mi := &file_proto_tag_tag_endpoint_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTagsToTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTagsToTransactionsResponse) ProtoMessage() {}

func (x *GetTagsToTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tag_tag_endpoint_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTagsToTransactionsResponse.ProtoReflect.Descriptor instead.
func (*GetTagsToTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_tag_tag_endpoint_proto_rawDescGZIP(), []int{10}
}

func (x *GetTagsToTransactionsResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_proto_tag_tag_endpoint_proto protoreflect.FileDescriptor

const file_proto_tag_tag_endpoint_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/tag/tag-endpoint.proto\x12\x03tag\x1a\x17proto/error/error.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x95\x01\n" +
	"\x03Tag\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12&\n" +
	"\x0eaccountGroupID\x18\x03 \x01(\x05R\x0eaccountGroupID\x12B\n" +
	"\x0edatetimeCreate\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0edatetimeCreate\"\\\n" +
	"\x0eGetTagsRequest\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\x12(\n" +
	"\x0faccountGroupIDs\x18\x02 \x03(\x05R\x0faccountGroupIDs\"b\n" +
	"\x0fGetTagsResponse\x12'\n" +
	"\x05error\x18\x01 \x01(\v2\f.error.ErrorH\x00R\x05error\x88\x01\x01\x12\x1c\n" +
	"\x04tags\x18\x02 \x03(\v2\b.tag.TagR\x04tagsB\b\n" +
	"\x06_error\"\xb4\x01\n" +
	"\x10CreateTagRequest\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12&\n" +
	"\x0eaccountGroupID\x18\x03 \x01(\x05R\x0eaccountGroupID\x12B\n" +
	"\x0edatetimeCreate\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\x0edatetimeCreate\"b\n" +
	"\x11CreateTagResponse\x12'\n" +
	"\x05error\x18\x01 \x01(\v2\f.error.ErrorH\x00R\x05error\x88\x01\x01\x12\x13\n" +
	"\x02id\x18\x02 \x01(\fH\x01R\x02id\x88\x01\x01B\b\n" +
	"\x06_errorB\x05\n" +
	"\x03_id\"f\n" +
	"\x10UpdateTagRequest\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\fR\x02id\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x00R\x04name\x88\x01\x01B\a\n" +
	"\x05_name\"F\n" +
	"\x11UpdateTagResponse\x12'\n" +
	"\x05error\x18\x01 \x01(\v2\f.error.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"D\n" +
	"\x10DeleteTagRequest\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\fR\x02id\"F\n" +
	"\x11DeleteTagResponse\x12'\n" +
	"\x05error\x18\x01 \x01(\v2\f.error.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"@\n" +
	"\x1cGetTagsToTransactionsRequest\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\"R\n" +
	"\x1dGetTagsToTransactionsResponse\x12'\n" +
	"\x05error\x18\x01 \x01(\v2\f.error.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error2\xe1\x02\n" +
	"\vTagEndpoint\x126\n" +
	"\aGetTags\x12\x13.tag.GetTagsRequest\x1a\x14.tag.GetTagsResponse\"\x00\x12<\n" +
	"\tCreateTag\x12\x15.tag.CreateTagRequest\x1a\x16.tag.CreateTagResponse\"\x00\x12<\n" +
	"\tUpdateTag\x12\x15.tag.UpdateTagRequest\x1a\x16.tag.UpdateTagResponse\"\x00\x12<\n" +
	"\tDeleteTag\x12\x15.tag.DeleteTagRequest\x1a\x16.tag.DeleteTagResponse\"\x00\x12`\n" +
	"\x15GetTagsToTransactions\x12!.tag.GetTagsToTransactionsRequest\x1a\".tag.GetTagsToTransactionsResponse\"\x00B\bZ\x06/protob\x06proto3"

var (
	file_proto_tag_tag_endpoint_proto_rawDescOnce sync.Once
	file_proto_tag_tag_endpoint_proto_rawDescData []byte
)

func file_proto_tag_tag_endpoint_proto_rawDescGZIP() []byte {
	file_proto_tag_tag_endpoint_proto_rawDescOnce.Do(func() {
		file_proto_tag_tag_endpoint_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tag_tag_endpoint_proto_rawDesc), len(file_proto_tag_tag_endpoint_proto_rawDesc)))
	})
	return file_proto_tag_tag_endpoint_proto_rawDescData
}

var file_proto_tag_tag_endpoint_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_tag_tag_endpoint_proto_goTypes = []any{
	(*Tag)(nil),                           // 0: tag.Tag
	(*GetTagsRequest)(nil),                // 1: tag.GetTagsRequest
	(*GetTagsResponse)(nil),               // 2: tag.GetTagsResponse
	(*CreateTagRequest)(nil),              // 3: tag.CreateTagRequest
	(*CreateTagResponse)(nil),             // 4: tag.CreateTagResponse
	(*UpdateTagRequest)(nil),              // 5: tag.UpdateTagRequest
	(*UpdateTagResponse)(nil),             // 6: tag.UpdateTagResponse
	(*DeleteTagRequest)(nil),              // 7: tag.DeleteTagRequest
	(*DeleteTagResponse)(nil),             // 8: tag.DeleteTagResponse
	(*GetTagsToTransactionsRequest)(nil),  // 9: tag.GetTagsToTransactionsRequest
	(*GetTagsToTransactionsResponse)(nil), // 10: tag.GetTagsToTransactionsResponse
	(*timestamppb.Timestamp)(nil),         // 11: google.protobuf.Timestamp
	(*Error)(nil),                         // 12: error.Error
}
var file_proto_tag_tag_endpoint_proto_depIdxs = []int32{
	11, // 0: tag.Tag.datetimeCreate:type_name -> google.protobuf.Timestamp
	12, // 1: tag.GetTagsResponse.error:type_name -> error.Error
	0,  // 2: tag.GetTagsResponse.tags:type_name -> tag.Tag
	11, // 3: tag.CreateTagRequest.datetimeCreate:type_name -> google.protobuf.Timestamp
	12, // 4: tag.CreateTagResponse.error:type_name -> error.Error
	12, // 5: tag.UpdateTagResponse.error:type_name -> error.Error
	12, // 6: tag.DeleteTagResponse.error:type_name -> error.Error
	12, // 7: tag.GetTagsToTransactionsResponse.error:type_name -> error.Error
	1,  // 8: tag.TagEndpoint.GetTags:input_type -> tag.GetTagsRequest
	3,  // 9: tag.TagEndpoint.CreateTag:input_type -> tag.CreateTagRequest
	5,  // 10: tag.TagEndpoint.UpdateTag:input_type -> tag.UpdateTagRequest
	7,  // 11: tag.TagEndpoint.DeleteTag:input_type -> tag.DeleteTagRequest
	9,  // 12: tag.TagEndpoint.GetTagsToTransactions:input_type -> tag.GetTagsToTransactionsRequest
	2,  // 13: tag.TagEndpoint.GetTags:output_type -> tag.GetTagsResponse
	4,  // 14: tag.TagEndpoint.CreateTag:output_type -> tag.CreateTagResponse
	6,  // 15: tag.TagEndpoint.UpdateTag:output_type -> tag.UpdateTagResponse
	8,  // 16: tag.TagEndpoint.DeleteTag:output_type -> tag.DeleteTagResponse
	10, // 17: tag.TagEndpoint.GetTagsToTransactions:output_type -> tag.GetTagsToTransactionsResponse
	13, // [13:18] is the sub-list for method output_type
	8,  // [8:13] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_tag_tag_endpoint_proto_init() }
func file_proto_tag_tag_endpoint_proto_init() {
	if File_proto_tag_tag_endpoint_proto != nil {
		return
	}
	file_proto_error_error_proto_init()
	file_proto_tag_tag_endpoint_proto_msgTypes[2].OneofWrappers = []any{}
	file_proto_tag_tag_endpoint_proto_msgTypes[4].OneofWrappers = []any{}
	file_proto_tag_tag_endpoint_proto_msgTypes[5].OneofWrappers = []any{}
	file_proto_tag_tag_endpoint_proto_msgTypes[6].OneofWrappers = []any{}
	file_proto_tag_tag_endpoint_proto_msgTypes[8].OneofWrappers = []any{}
	file_proto_tag_tag_endpoint_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tag_tag_endpoint_proto_rawDesc), len(file_proto_tag_tag_endpoint_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tag_tag_endpoint_proto_goTypes,
		DependencyIndexes: file_proto_tag_tag_endpoint_proto_depIdxs,
		MessageInfos:      file_proto_tag_tag_endpoint_proto_msgTypes,
	}.Build()
	File_proto_tag_tag_endpoint_proto = out.File
	file_proto_tag_tag_endpoint_proto_goTypes = nil
	file_proto_tag_tag_endpoint_proto_depIdxs = nil
}
