// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/tag/tag-endpoint.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TagEndpoint_GetTags_FullMethodName               = "/tag.TagEndpoint/GetTags"
	TagEndpoint_CreateTag_FullMethodName             = "/tag.TagEndpoint/CreateTag"
	TagEndpoint_UpdateTag_FullMethodName             = "/tag.TagEndpoint/UpdateTag"
	TagEndpoint_DeleteTag_FullMethodName             = "/tag.TagEndpoint/DeleteTag"
	TagEndpoint_GetTagsToTransactions_FullMethodName = "/tag.TagEndpoint/GetTagsToTransactions"
)

// TagEndpointClient is the client API for TagEndpoint service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TagEndpointClient interface {
	// GetTags получение всех подкатегорий
	GetTags(ctx context.Context, in *GetTagsRequest, opts ...grpc.CallOption) (*GetTagsResponse, error)
	// CreateTag создание подкатегории
	CreateTag(ctx context.Context, in *CreateTagRequest, opts ...grpc.CallOption) (*CreateTagResponse, error)
	// UpdateTag редактирование подкатегории
	UpdateTag(ctx context.Context, in *UpdateTagRequest, opts ...grpc.CallOption) (*UpdateTagResponse, error)
	// DeleteTag удаление подкатегории
	DeleteTag(ctx context.Context, in *DeleteTagRequest, opts ...grpc.CallOption) (*DeleteTagResponse, error)
	// GetTagsToTransactions получение всех связей между подкатегориями и транзакциями
	GetTagsToTransactions(ctx context.Context, in *GetTagsToTransactionsRequest, opts ...grpc.CallOption) (*GetTagsToTransactionsResponse, error)
}

type tagEndpointClient struct {
	cc grpc.ClientConnInterface
}

func NewTagEndpointClient(cc grpc.ClientConnInterface) TagEndpointClient {
	return &tagEndpointClient{cc}
}

func (c *tagEndpointClient) GetTags(ctx context.Context, in *GetTagsRequest, opts ...grpc.CallOption) (*GetTagsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTagsResponse)
	err := c.cc.Invoke(ctx, TagEndpoint_GetTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tagEndpointClient) CreateTag(ctx context.Context, in *CreateTagRequest, opts ...grpc.CallOption) (*CreateTagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTagResponse)
	err := c.cc.Invoke(ctx, TagEndpoint_CreateTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tagEndpointClient) UpdateTag(ctx context.Context, in *UpdateTagRequest, opts ...grpc.CallOption) (*UpdateTagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateTagResponse)
	err := c.cc.Invoke(ctx, TagEndpoint_UpdateTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tagEndpointClient) DeleteTag(ctx context.Context, in *DeleteTagRequest, opts ...grpc.CallOption) (*DeleteTagResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTagResponse)
	err := c.cc.Invoke(ctx, TagEndpoint_DeleteTag_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tagEndpointClient) GetTagsToTransactions(ctx context.Context, in *GetTagsToTransactionsRequest, opts ...grpc.CallOption) (*GetTagsToTransactionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTagsToTransactionsResponse)
	err := c.cc.Invoke(ctx, TagEndpoint_GetTagsToTransactions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TagEndpointServer is the server API for TagEndpoint service.
// All implementations must embed UnimplementedTagEndpointServer
// for forward compatibility.
type TagEndpointServer interface {
	// GetTags получение всех подкатегорий
	GetTags(context.Context, *GetTagsRequest) (*GetTagsResponse, error)
	// CreateTag создание подкатегории
	CreateTag(context.Context, *CreateTagRequest) (*CreateTagResponse, error)
	// UpdateTag редактирование подкатегории
	UpdateTag(context.Context, *UpdateTagRequest) (*UpdateTagResponse, error)
	// DeleteTag удаление подкатегории
	DeleteTag(context.Context, *DeleteTagRequest) (*DeleteTagResponse, error)
	// GetTagsToTransactions получение всех связей между подкатегориями и транзакциями
	GetTagsToTransactions(context.Context, *GetTagsToTransactionsRequest) (*GetTagsToTransactionsResponse, error)
	mustEmbedUnimplementedTagEndpointServer()
}

// UnimplementedTagEndpointServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTagEndpointServer struct{}

func (UnimplementedTagEndpointServer) GetTags(context.Context, *GetTagsRequest) (*GetTagsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTags not implemented")
}
func (UnimplementedTagEndpointServer) CreateTag(context.Context, *CreateTagRequest) (*CreateTagResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTag not implemented")
}
func (UnimplementedTagEndpointServer) UpdateTag(context.Context, *UpdateTagRequest) (*UpdateTagResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTag not implemented")
}
func (UnimplementedTagEndpointServer) DeleteTag(context.Context, *DeleteTagRequest) (*DeleteTagResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteTag not implemented")
}
func (UnimplementedTagEndpointServer) GetTagsToTransactions(context.Context, *GetTagsToTransactionsRequest) (*GetTagsToTransactionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTagsToTransactions not implemented")
}
func (UnimplementedTagEndpointServer) mustEmbedUnimplementedTagEndpointServer() {}
func (UnimplementedTagEndpointServer) testEmbeddedByValue()                     {}

// UnsafeTagEndpointServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TagEndpointServer will
// result in compilation errors.
type UnsafeTagEndpointServer interface {
	mustEmbedUnimplementedTagEndpointServer()
}

func RegisterTagEndpointServer(s grpc.ServiceRegistrar, srv TagEndpointServer) {
	// If the following call panics, it indicates UnimplementedTagEndpointServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TagEndpoint_ServiceDesc, srv)
}

func _TagEndpoint_GetTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagEndpointServer).GetTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TagEndpoint_GetTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagEndpointServer).GetTags(ctx, req.(*GetTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TagEndpoint_CreateTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagEndpointServer).CreateTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TagEndpoint_CreateTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagEndpointServer).CreateTag(ctx, req.(*CreateTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TagEndpoint_UpdateTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagEndpointServer).UpdateTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TagEndpoint_UpdateTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagEndpointServer).UpdateTag(ctx, req.(*UpdateTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TagEndpoint_DeleteTag_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTagRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagEndpointServer).DeleteTag(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TagEndpoint_DeleteTag_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagEndpointServer).DeleteTag(ctx, req.(*DeleteTagRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TagEndpoint_GetTagsToTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTagsToTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TagEndpointServer).GetTagsToTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TagEndpoint_GetTagsToTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TagEndpointServer).GetTagsToTransactions(ctx, req.(*GetTagsToTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TagEndpoint_ServiceDesc is the grpc.ServiceDesc for TagEndpoint service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TagEndpoint_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tag.TagEndpoint",
	HandlerType: (*TagEndpointServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTags",
			Handler:    _TagEndpoint_GetTags_Handler,
		},
		{
			MethodName: "CreateTag",
			Handler:    _TagEndpoint_CreateTag_Handler,
		},
		{
			MethodName: "UpdateTag",
			Handler:    _TagEndpoint_UpdateTag_Handler,
		},
		{
			MethodName: "DeleteTag",
			Handler:    _TagEndpoint_DeleteTag_Handler,
		},
		{
			MethodName: "GetTagsToTransactions",
			Handler:    _TagEndpoint_GetTagsToTransactions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/tag/tag-endpoint.proto",
}
