// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/enums/transactionType.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TransactionType int32

const (
	TransactionType_Unspecified TransactionType = 0
	TransactionType_Transfer    TransactionType = 1 // Перевод между счетами
	TransactionType_Consumption TransactionType = 2 // Расход
	TransactionType_Balancing   TransactionType = 3 // Балансировка
	TransactionType_Income      TransactionType = 4 // Доход
)

// Enum value maps for TransactionType.
var (
	TransactionType_name = map[int32]string{
		0: "Unspecified",
		1: "Transfer",
		2: "Consumption",
		3: "Balancing",
		4: "Income",
	}
	TransactionType_value = map[string]int32{
		"Unspecified": 0,
		"Transfer":    1,
		"Consumption": 2,
		"Balancing":   3,
		"Income":      4,
	}
)

func (x TransactionType) Enum() *TransactionType {
	p := new(TransactionType)
	*p = x
	return p
}

func (x TransactionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_enums_transactionType_proto_enumTypes[0].Descriptor()
}

func (TransactionType) Type() protoreflect.EnumType {
	return &file_proto_enums_transactionType_proto_enumTypes[0]
}

func (x TransactionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionType.Descriptor instead.
func (TransactionType) EnumDescriptor() ([]byte, []int) {
	return file_proto_enums_transactionType_proto_rawDescGZIP(), []int{0}
}

var File_proto_enums_transactionType_proto protoreflect.FileDescriptor

const file_proto_enums_transactionType_proto_rawDesc = "" +
	"\n" +
	"!proto/enums/transactionType.proto\x12\x0ftransactionType*\\\n" +
	"\x0fTransactionType\x12\x0f\n" +
	"\vUnspecified\x10\x00\x12\f\n" +
	"\bTransfer\x10\x01\x12\x0f\n" +
	"\vConsumption\x10\x02\x12\r\n" +
	"\tBalancing\x10\x03\x12\n" +
	"\n" +
	"\x06Income\x10\x04B\bZ\x06/protob\x06proto3"

var (
	file_proto_enums_transactionType_proto_rawDescOnce sync.Once
	file_proto_enums_transactionType_proto_rawDescData []byte
)

func file_proto_enums_transactionType_proto_rawDescGZIP() []byte {
	file_proto_enums_transactionType_proto_rawDescOnce.Do(func() {
		file_proto_enums_transactionType_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_enums_transactionType_proto_rawDesc), len(file_proto_enums_transactionType_proto_rawDesc)))
	})
	return file_proto_enums_transactionType_proto_rawDescData
}

var file_proto_enums_transactionType_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_enums_transactionType_proto_goTypes = []any{
	(TransactionType)(0), // 0: transactionType.TransactionType
}
var file_proto_enums_transactionType_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_enums_transactionType_proto_init() }
func file_proto_enums_transactionType_proto_init() {
	if File_proto_enums_transactionType_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_enums_transactionType_proto_rawDesc), len(file_proto_enums_transactionType_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_enums_transactionType_proto_goTypes,
		DependencyIndexes: file_proto_enums_transactionType_proto_depIdxs,
		EnumInfos:         file_proto_enums_transactionType_proto_enumTypes,
	}.Build()
	File_proto_enums_transactionType_proto = out.File
	file_proto_enums_transactionType_proto_goTypes = nil
	file_proto_enums_transactionType_proto_depIdxs = nil
}
