// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: proto/transaction/transaction-endpoint.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Transaction struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 []byte                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                           // Идентификатор транзакции
	Type               TransactionType        `protobuf:"varint,2,opt,name=type,proto3,enum=transactionType.TransactionType" json:"type,omitempty"` // Тип транзакции
	AccountFromID      []byte                 `protobuf:"bytes,3,opt,name=accountFromID,proto3" json:"accountFromID,omitempty"`                     // Идентификатор счета списания
	AccountToID        []byte                 `protobuf:"bytes,4,opt,name=accountToID,proto3" json:"accountToID,omitempty"`                         // Идентификатор счета пополнения
	AmountFrom         float64                `protobuf:"fixed64,5,opt,name=amountFrom,proto3" json:"amountFrom,omitempty"`                         // Сумма сделки в первой валюте
	AmountTo           float64                `protobuf:"fixed64,6,opt,name=amountTo,proto3" json:"amountTo,omitempty"`                             // Сумма сделки во второй валюте
	DateTransaction    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=dateTransaction,proto3" json:"dateTransaction,omitempty"`                 // Дата транзакции (пользовательские)
	DatetimeCreate     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=datetimeCreate,proto3" json:"datetimeCreate,omitempty"`                   // Дата и время создания транзакции
	IsExecuted         bool                   `protobuf:"varint,9,opt,name=isExecuted,proto3" json:"isExecuted,omitempty"`                          // Исполнена операция или нет
	AccountingInCharts bool                   `protobuf:"varint,10,opt,name=accountingInCharts,proto3" json:"accountingInCharts,omitempty"`         // Учитывается ли транзакция в графиках или нет
	AccountGroupID     []byte                 `protobuf:"bytes,11,opt,name=accountGroupID,proto3" json:"accountGroupID,omitempty"`                  // Идентификатор группы счетов
	CreatedByUserID    []byte                 `protobuf:"bytes,12,opt,name=createdByUserID,proto3" json:"createdByUserID,omitempty"`                // Идентификатор пользователя, создавшего транзакцию
	Note               string                 `protobuf:"bytes,13,opt,name=note,proto3" json:"note,omitempty"`                                      // Заметка сделки
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_proto_transaction_transaction_endpoint_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_transaction_endpoint_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_proto_transaction_transaction_endpoint_proto_rawDescGZIP(), []int{0}
}

func (x *Transaction) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Transaction) GetType() TransactionType {
	if x != nil {
		return x.Type
	}
	return TransactionType_Unspecified
}

func (x *Transaction) GetAccountFromID() []byte {
	if x != nil {
		return x.AccountFromID
	}
	return nil
}

func (x *Transaction) GetAccountToID() []byte {
	if x != nil {
		return x.AccountToID
	}
	return nil
}

func (x *Transaction) GetAmountFrom() float64 {
	if x != nil {
		return x.AmountFrom
	}
	return 0
}

func (x *Transaction) GetAmountTo() float64 {
	if x != nil {
		return x.AmountTo
	}
	return 0
}

func (x *Transaction) GetDateTransaction() *timestamppb.Timestamp {
	if x != nil {
		return x.DateTransaction
	}
	return nil
}

func (x *Transaction) GetDatetimeCreate() *timestamppb.Timestamp {
	if x != nil {
		return x.DatetimeCreate
	}
	return nil
}

func (x *Transaction) GetIsExecuted() bool {
	if x != nil {
		return x.IsExecuted
	}
	return false
}

func (x *Transaction) GetAccountingInCharts() bool {
	if x != nil {
		return x.AccountingInCharts
	}
	return false
}

func (x *Transaction) GetAccountGroupID() []byte {
	if x != nil {
		return x.AccountGroupID
	}
	return nil
}

func (x *Transaction) GetCreatedByUserID() []byte {
	if x != nil {
		return x.CreatedByUserID
	}
	return nil
}

func (x *Transaction) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

type GetTransactionsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccessToken     string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`                               // Токен доступа
	AccountGroupIDs [][]byte               `protobuf:"bytes,2,rep,name=accountGroupIDs,proto3" json:"accountGroupIDs,omitempty"`                       // Идентификаторы групп счетов
	AccountID       []byte                 `protobuf:"bytes,3,opt,name=accountID,proto3,oneof" json:"accountID,omitempty"`                             // Транзакции какого счета нас интересуют
	DateFrom        *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=dateFrom,proto3,oneof" json:"dateFrom,omitempty"`                               // Дата, от которой начинать учитывать транзакции
	DateTo          *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=dateTo,proto3,oneof" json:"dateTo,omitempty"`                                   // Дата, до которой учитывать транзакции
	Limit           *uint32                `protobuf:"varint,6,opt,name=limit,proto3,oneof" json:"limit,omitempty"`                                    // Количество транзакций в списке для пагинации
	Offset          *uint32                `protobuf:"varint,7,opt,name=offset,proto3,oneof" json:"offset,omitempty"`                                  // Смещение относительно начала списка для пагинации
	Type            *TransactionType       `protobuf:"varint,8,opt,name=type,proto3,enum=transactionType.TransactionType,oneof" json:"type,omitempty"` // Тип транзакции
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetTransactionsRequest) Reset() {
	*x = GetTransactionsRequest{}
	mi := &file_proto_transaction_transaction_endpoint_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsRequest) ProtoMessage() {}

func (x *GetTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_transaction_endpoint_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_proto_transaction_transaction_endpoint_proto_rawDescGZIP(), []int{1}
}

func (x *GetTransactionsRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *GetTransactionsRequest) GetAccountGroupIDs() [][]byte {
	if x != nil {
		return x.AccountGroupIDs
	}
	return nil
}

func (x *GetTransactionsRequest) GetAccountID() []byte {
	if x != nil {
		return x.AccountID
	}
	return nil
}

func (x *GetTransactionsRequest) GetDateFrom() *timestamppb.Timestamp {
	if x != nil {
		return x.DateFrom
	}
	return nil
}

func (x *GetTransactionsRequest) GetDateTo() *timestamppb.Timestamp {
	if x != nil {
		return x.DateTo
	}
	return nil
}

func (x *GetTransactionsRequest) GetLimit() uint32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

func (x *GetTransactionsRequest) GetOffset() uint32 {
	if x != nil && x.Offset != nil {
		return *x.Offset
	}
	return 0
}

func (x *GetTransactionsRequest) GetType() TransactionType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return TransactionType_Unspecified
}

type GetTransactionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"`         // Объект ошибки
	Transactions  []*Transaction         `protobuf:"bytes,2,rep,name=transactions,proto3" json:"transactions,omitempty"` // Список транзакций
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionsResponse) Reset() {
	*x = GetTransactionsResponse{}
	mi := &file_proto_transaction_transaction_endpoint_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionsResponse) ProtoMessage() {}

func (x *GetTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_transaction_endpoint_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionsResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_proto_transaction_transaction_endpoint_proto_rawDescGZIP(), []int{2}
}

func (x *GetTransactionsResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *GetTransactionsResponse) GetTransactions() []*Transaction {
	if x != nil {
		return x.Transactions
	}
	return nil
}

type CreateTransactionRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AccessToken        string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`                          // Токен доступа
	Id                 []byte                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`                                            // Идентификатор транзакции
	AccountFromID      []byte                 `protobuf:"bytes,3,opt,name=accountFromID,proto3" json:"accountFromID,omitempty"`                      // Идентификатор счета списания
	AccountToID        []byte                 `protobuf:"bytes,4,opt,name=accountToID,proto3" json:"accountToID,omitempty"`                          // Идентификатор счета пополнения
	AccountGroupID     []byte                 `protobuf:"bytes,5,opt,name=accountGroupID,proto3" json:"accountGroupID,omitempty"`                    // Идентификатор группы счетов
	AmountFrom         float64                `protobuf:"fixed64,6,opt,name=amountFrom,proto3" json:"amountFrom,omitempty"`                          // Сумма списания с первого счета
	AmountTo           float64                `protobuf:"fixed64,7,opt,name=amountTo,proto3" json:"amountTo,omitempty"`                              // Сумма пополнения второго счета (в случаях меж валютной транзакции цифры отличаются)
	DateTransaction    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=dateTransaction,proto3" json:"dateTransaction,omitempty"`                  // Дата транзакции
	DatetimeCreate     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=datetimeCreate,proto3" json:"datetimeCreate,omitempty"`                    // Дата создания транзакции
	IsExecuted         bool                   `protobuf:"varint,10,opt,name=isExecuted,proto3" json:"isExecuted,omitempty"`                          // Исполнена операция или нет (если нет, сделки как бы не существует)
	AccountingInCharts bool                   `protobuf:"varint,11,opt,name=accountingInCharts,proto3" json:"accountingInCharts,omitempty"`          // Учитывается ли транзакция в графиках или нет
	Type               TransactionType        `protobuf:"varint,12,opt,name=type,proto3,enum=transactionType.TransactionType" json:"type,omitempty"` // Тип транзакции
	Note               string                 `protobuf:"bytes,13,opt,name=note,proto3" json:"note,omitempty"`                                       // Заметка для транзакции
	TagIDs             [][]byte               `protobuf:"bytes,14,rep,name=tagIDs,proto3" json:"tagIDs,omitempty"`                                   // Идентификаторы тегов
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CreateTransactionRequest) Reset() {
	*x = CreateTransactionRequest{}
	mi := &file_proto_transaction_transaction_endpoint_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionRequest) ProtoMessage() {}

func (x *CreateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_transaction_endpoint_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionRequest.ProtoReflect.Descriptor instead.
func (*CreateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_transaction_transaction_endpoint_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTransactionRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *CreateTransactionRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *CreateTransactionRequest) GetAccountFromID() []byte {
	if x != nil {
		return x.AccountFromID
	}
	return nil
}

func (x *CreateTransactionRequest) GetAccountToID() []byte {
	if x != nil {
		return x.AccountToID
	}
	return nil
}

func (x *CreateTransactionRequest) GetAccountGroupID() []byte {
	if x != nil {
		return x.AccountGroupID
	}
	return nil
}

func (x *CreateTransactionRequest) GetAmountFrom() float64 {
	if x != nil {
		return x.AmountFrom
	}
	return 0
}

func (x *CreateTransactionRequest) GetAmountTo() float64 {
	if x != nil {
		return x.AmountTo
	}
	return 0
}

func (x *CreateTransactionRequest) GetDateTransaction() *timestamppb.Timestamp {
	if x != nil {
		return x.DateTransaction
	}
	return nil
}

func (x *CreateTransactionRequest) GetDatetimeCreate() *timestamppb.Timestamp {
	if x != nil {
		return x.DatetimeCreate
	}
	return nil
}

func (x *CreateTransactionRequest) GetIsExecuted() bool {
	if x != nil {
		return x.IsExecuted
	}
	return false
}

func (x *CreateTransactionRequest) GetAccountingInCharts() bool {
	if x != nil {
		return x.AccountingInCharts
	}
	return false
}

func (x *CreateTransactionRequest) GetType() TransactionType {
	if x != nil {
		return x.Type
	}
	return TransactionType_Unspecified
}

func (x *CreateTransactionRequest) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *CreateTransactionRequest) GetTagIDs() [][]byte {
	if x != nil {
		return x.TagIDs
	}
	return nil
}

type CreateTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"` // Объект ошибки
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTransactionResponse) Reset() {
	*x = CreateTransactionResponse{}
	mi := &file_proto_transaction_transaction_endpoint_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTransactionResponse) ProtoMessage() {}

func (x *CreateTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_transaction_endpoint_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTransactionResponse.ProtoReflect.Descriptor instead.
func (*CreateTransactionResponse) Descriptor() ([]byte, []int) {
	return file_proto_transaction_transaction_endpoint_proto_rawDescGZIP(), []int{4}
}

func (x *CreateTransactionResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type UpdateTransactionRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	AccessToken        string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`                      // Токен доступа
	Id                 []byte                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`                                        // Идентификатор транзакции
	AccountFromID      []byte                 `protobuf:"bytes,3,opt,name=accountFromID,proto3,oneof" json:"accountFromID,omitempty"`            // Идентификатор счета списания
	AccountToID        []byte                 `protobuf:"bytes,4,opt,name=accountToID,proto3,oneof" json:"accountToID,omitempty"`                // Идентификатор счета пополнения
	AmountFrom         *float64               `protobuf:"fixed64,5,opt,name=amountFrom,proto3,oneof" json:"amountFrom,omitempty"`                // Сумма списания с первого счета
	AmountTo           *float64               `protobuf:"fixed64,6,opt,name=amountTo,proto3,oneof" json:"amountTo,omitempty"`                    // Сумма пополнения второго счета
	DateTransaction    *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=dateTransaction,proto3,oneof" json:"dateTransaction,omitempty"`        // Дата транзакции
	IsExecuted         *bool                  `protobuf:"varint,8,opt,name=isExecuted,proto3,oneof" json:"isExecuted,omitempty"`                 // Исполнена операция или нет (если нет, сделки как бы не существует)
	AccountingInCharts *bool                  `protobuf:"varint,9,opt,name=accountingInCharts,proto3,oneof" json:"accountingInCharts,omitempty"` // Учитывается ли транзакция в графиках или нет
	Note               *string                `protobuf:"bytes,10,opt,name=note,proto3,oneof" json:"note,omitempty"`                             // Заметка для транзакции
	TagIDs             [][]byte               `protobuf:"bytes,11,rep,name=tagIDs,proto3" json:"tagIDs,omitempty"`                               // Идентификаторы тегов
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdateTransactionRequest) Reset() {
	*x = UpdateTransactionRequest{}
	mi := &file_proto_transaction_transaction_endpoint_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTransactionRequest) ProtoMessage() {}

func (x *UpdateTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_transaction_endpoint_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTransactionRequest.ProtoReflect.Descriptor instead.
func (*UpdateTransactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_transaction_transaction_endpoint_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateTransactionRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *UpdateTransactionRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *UpdateTransactionRequest) GetAccountFromID() []byte {
	if x != nil {
		return x.AccountFromID
	}
	return nil
}

func (x *UpdateTransactionRequest) GetAccountToID() []byte {
	if x != nil {
		return x.AccountToID
	}
	return nil
}

func (x *UpdateTransactionRequest) GetAmountFrom() float64 {
	if x != nil && x.AmountFrom != nil {
		return *x.AmountFrom
	}
	return 0
}

func (x *UpdateTransactionRequest) GetAmountTo() float64 {
	if x != nil && x.AmountTo != nil {
		return *x.AmountTo
	}
	return 0
}

func (x *UpdateTransactionRequest) GetDateTransaction() *timestamppb.Timestamp {
	if x != nil {
		return x.DateTransaction
	}
	return nil
}

func (x *UpdateTransactionRequest) GetIsExecuted() bool {
	if x != nil && x.IsExecuted != nil {
		return *x.IsExecuted
	}
	return false
}

func (x *UpdateTransactionRequest) GetAccountingInCharts() bool {
	if x != nil && x.AccountingInCharts != nil {
		return *x.AccountingInCharts
	}
	return false
}

func (x *UpdateTransactionRequest) GetNote() string {
	if x != nil && x.Note != nil {
		return *x.Note
	}
	return ""
}

func (x *UpdateTransactionRequest) GetTagIDs() [][]byte {
	if x != nil {
		return x.TagIDs
	}
	return nil
}

type UpdateTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"` // Объект ошибки
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTransactionResponse) Reset() {
	*x = UpdateTransactionResponse{}
	mi := &file_proto_transaction_transaction_endpoint_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTransactionResponse) ProtoMessage() {}

func (x *UpdateTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_transaction_endpoint_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTransactionResponse.ProtoReflect.Descriptor instead.
func (*UpdateTransactionResponse) Descriptor() ([]byte, []int) {
	return file_proto_transaction_transaction_endpoint_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateTransactionResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type DeleteTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"` // Токен доступа
	Id            []byte                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`                   // Идентификатор транзакции
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTransactionRequest) Reset() {
	*x = DeleteTransactionRequest{}
	mi := &file_proto_transaction_transaction_endpoint_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTransactionRequest) ProtoMessage() {}

func (x *DeleteTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_transaction_endpoint_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTransactionRequest.ProtoReflect.Descriptor instead.
func (*DeleteTransactionRequest) Descriptor() ([]byte, []int) {
	return file_proto_transaction_transaction_endpoint_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteTransactionRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *DeleteTransactionRequest) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

type DeleteTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"` // Объект ошибки
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTransactionResponse) Reset() {
	*x = DeleteTransactionResponse{}
	mi := &file_proto_transaction_transaction_endpoint_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTransactionResponse) ProtoMessage() {}

func (x *DeleteTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_transaction_transaction_endpoint_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTransactionResponse.ProtoReflect.Descriptor instead.
func (*DeleteTransactionResponse) Descriptor() ([]byte, []int) {
	return file_proto_transaction_transaction_endpoint_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteTransactionResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_proto_transaction_transaction_endpoint_proto protoreflect.FileDescriptor

const file_proto_transaction_transaction_endpoint_proto_rawDesc = "" +
	"\n" +
	",proto/transaction/transaction-endpoint.proto\x12\vtransaction\x1a\x17proto/error/error.proto\x1a!proto/enums/transactionType.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x97\x04\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x124\n" +
	"\x04type\x18\x02 \x01(\x0e2 .transactionType.TransactionTypeR\x04type\x12$\n" +
	"\raccountFromID\x18\x03 \x01(\fR\raccountFromID\x12 \n" +
	"\vaccountToID\x18\x04 \x01(\fR\vaccountToID\x12\x1e\n" +
	"\n" +
	"amountFrom\x18\x05 \x01(\x01R\n" +
	"amountFrom\x12\x1a\n" +
	"\bamountTo\x18\x06 \x01(\x01R\bamountTo\x12D\n" +
	"\x0fdateTransaction\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x0fdateTransaction\x12B\n" +
	"\x0edatetimeCreate\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x0edatetimeCreate\x12\x1e\n" +
	"\n" +
	"isExecuted\x18\t \x01(\bR\n" +
	"isExecuted\x12.\n" +
	"\x12accountingInCharts\x18\n" +
	" \x01(\bR\x12accountingInCharts\x12&\n" +
	"\x0eaccountGroupID\x18\v \x01(\fR\x0eaccountGroupID\x12(\n" +
	"\x0fcreatedByUserID\x18\f \x01(\fR\x0fcreatedByUserID\x12\x12\n" +
	"\x04note\x18\r \x01(\tR\x04note\"\xb4\x03\n" +
	"\x16GetTransactionsRequest\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\x12(\n" +
	"\x0faccountGroupIDs\x18\x02 \x03(\fR\x0faccountGroupIDs\x12!\n" +
	"\taccountID\x18\x03 \x01(\fH\x00R\taccountID\x88\x01\x01\x12;\n" +
	"\bdateFrom\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\bdateFrom\x88\x01\x01\x127\n" +
	"\x06dateTo\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampH\x02R\x06dateTo\x88\x01\x01\x12\x19\n" +
	"\x05limit\x18\x06 \x01(\rH\x03R\x05limit\x88\x01\x01\x12\x1b\n" +
	"\x06offset\x18\a \x01(\rH\x04R\x06offset\x88\x01\x01\x129\n" +
	"\x04type\x18\b \x01(\x0e2 .transactionType.TransactionTypeH\x05R\x04type\x88\x01\x01B\f\n" +
	"\n" +
	"_accountIDB\v\n" +
	"\t_dateFromB\t\n" +
	"\a_dateToB\b\n" +
	"\x06_limitB\t\n" +
	"\a_offsetB\a\n" +
	"\x05_type\"\x8a\x01\n" +
	"\x17GetTransactionsResponse\x12'\n" +
	"\x05error\x18\x01 \x01(\v2\f.error.ErrorH\x00R\x05error\x88\x01\x01\x12<\n" +
	"\ftransactions\x18\x02 \x03(\v2\x18.transaction.TransactionR\ftransactionsB\b\n" +
	"\x06_error\"\xb4\x04\n" +
	"\x18CreateTransactionRequest\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\fR\x02id\x12$\n" +
	"\raccountFromID\x18\x03 \x01(\fR\raccountFromID\x12 \n" +
	"\vaccountToID\x18\x04 \x01(\fR\vaccountToID\x12&\n" +
	"\x0eaccountGroupID\x18\x05 \x01(\fR\x0eaccountGroupID\x12\x1e\n" +
	"\n" +
	"amountFrom\x18\x06 \x01(\x01R\n" +
	"amountFrom\x12\x1a\n" +
	"\bamountTo\x18\a \x01(\x01R\bamountTo\x12D\n" +
	"\x0fdateTransaction\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x0fdateTransaction\x12B\n" +
	"\x0edatetimeCreate\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\x0edatetimeCreate\x12\x1e\n" +
	"\n" +
	"isExecuted\x18\n" +
	" \x01(\bR\n" +
	"isExecuted\x12.\n" +
	"\x12accountingInCharts\x18\v \x01(\bR\x12accountingInCharts\x124\n" +
	"\x04type\x18\f \x01(\x0e2 .transactionType.TransactionTypeR\x04type\x12\x12\n" +
	"\x04note\x18\r \x01(\tR\x04note\x12\x16\n" +
	"\x06tagIDs\x18\x0e \x03(\fR\x06tagIDs\"N\n" +
	"\x19CreateTransactionResponse\x12'\n" +
	"\x05error\x18\x01 \x01(\v2\f.error.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\xbb\x04\n" +
	"\x18UpdateTransactionRequest\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\fR\x02id\x12)\n" +
	"\raccountFromID\x18\x03 \x01(\fH\x00R\raccountFromID\x88\x01\x01\x12%\n" +
	"\vaccountToID\x18\x04 \x01(\fH\x01R\vaccountToID\x88\x01\x01\x12#\n" +
	"\n" +
	"amountFrom\x18\x05 \x01(\x01H\x02R\n" +
	"amountFrom\x88\x01\x01\x12\x1f\n" +
	"\bamountTo\x18\x06 \x01(\x01H\x03R\bamountTo\x88\x01\x01\x12I\n" +
	"\x0fdateTransaction\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x04R\x0fdateTransaction\x88\x01\x01\x12#\n" +
	"\n" +
	"isExecuted\x18\b \x01(\bH\x05R\n" +
	"isExecuted\x88\x01\x01\x123\n" +
	"\x12accountingInCharts\x18\t \x01(\bH\x06R\x12accountingInCharts\x88\x01\x01\x12\x17\n" +
	"\x04note\x18\n" +
	" \x01(\tH\aR\x04note\x88\x01\x01\x12\x16\n" +
	"\x06tagIDs\x18\v \x03(\fR\x06tagIDsB\x10\n" +
	"\x0e_accountFromIDB\x0e\n" +
	"\f_accountToIDB\r\n" +
	"\v_amountFromB\v\n" +
	"\t_amountToB\x12\n" +
	"\x10_dateTransactionB\r\n" +
	"\v_isExecutedB\x15\n" +
	"\x13_accountingInChartsB\a\n" +
	"\x05_note\"N\n" +
	"\x19UpdateTransactionResponse\x12'\n" +
	"\x05error\x18\x01 \x01(\v2\f.error.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"L\n" +
	"\x18DeleteTransactionRequest\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\fR\x02id\"N\n" +
	"\x19DeleteTransactionResponse\x12'\n" +
	"\x05error\x18\x01 \x01(\v2\f.error.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error2\xa7\x03\n" +
	"\x13TransactionEndpoint\x12^\n" +
	"\x0fGetTransactions\x12#.transaction.GetTransactionsRequest\x1a$.transaction.GetTransactionsResponse\"\x00\x12d\n" +
	"\x11CreateTransaction\x12%.transaction.CreateTransactionRequest\x1a&.transaction.CreateTransactionResponse\"\x00\x12d\n" +
	"\x11UpdateTransaction\x12%.transaction.UpdateTransactionRequest\x1a&.transaction.UpdateTransactionResponse\"\x00\x12d\n" +
	"\x11DeleteTransaction\x12%.transaction.DeleteTransactionRequest\x1a&.transaction.DeleteTransactionResponse\"\x00B\bZ\x06/protob\x06proto3"

var (
	file_proto_transaction_transaction_endpoint_proto_rawDescOnce sync.Once
	file_proto_transaction_transaction_endpoint_proto_rawDescData []byte
)

func file_proto_transaction_transaction_endpoint_proto_rawDescGZIP() []byte {
	file_proto_transaction_transaction_endpoint_proto_rawDescOnce.Do(func() {
		file_proto_transaction_transaction_endpoint_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_transaction_transaction_endpoint_proto_rawDesc), len(file_proto_transaction_transaction_endpoint_proto_rawDesc)))
	})
	return file_proto_transaction_transaction_endpoint_proto_rawDescData
}

var file_proto_transaction_transaction_endpoint_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_transaction_transaction_endpoint_proto_goTypes = []any{
	(*Transaction)(nil),               // 0: transaction.Transaction
	(*GetTransactionsRequest)(nil),    // 1: transaction.GetTransactionsRequest
	(*GetTransactionsResponse)(nil),   // 2: transaction.GetTransactionsResponse
	(*CreateTransactionRequest)(nil),  // 3: transaction.CreateTransactionRequest
	(*CreateTransactionResponse)(nil), // 4: transaction.CreateTransactionResponse
	(*UpdateTransactionRequest)(nil),  // 5: transaction.UpdateTransactionRequest
	(*UpdateTransactionResponse)(nil), // 6: transaction.UpdateTransactionResponse
	(*DeleteTransactionRequest)(nil),  // 7: transaction.DeleteTransactionRequest
	(*DeleteTransactionResponse)(nil), // 8: transaction.DeleteTransactionResponse
	(TransactionType)(0),              // 9: transactionType.TransactionType
	(*timestamppb.Timestamp)(nil),     // 10: google.protobuf.Timestamp
	(*Error)(nil),                     // 11: error.Error
}
var file_proto_transaction_transaction_endpoint_proto_depIdxs = []int32{
	9,  // 0: transaction.Transaction.type:type_name -> transactionType.TransactionType
	10, // 1: transaction.Transaction.dateTransaction:type_name -> google.protobuf.Timestamp
	10, // 2: transaction.Transaction.datetimeCreate:type_name -> google.protobuf.Timestamp
	10, // 3: transaction.GetTransactionsRequest.dateFrom:type_name -> google.protobuf.Timestamp
	10, // 4: transaction.GetTransactionsRequest.dateTo:type_name -> google.protobuf.Timestamp
	9,  // 5: transaction.GetTransactionsRequest.type:type_name -> transactionType.TransactionType
	11, // 6: transaction.GetTransactionsResponse.error:type_name -> error.Error
	0,  // 7: transaction.GetTransactionsResponse.transactions:type_name -> transaction.Transaction
	10, // 8: transaction.CreateTransactionRequest.dateTransaction:type_name -> google.protobuf.Timestamp
	10, // 9: transaction.CreateTransactionRequest.datetimeCreate:type_name -> google.protobuf.Timestamp
	9,  // 10: transaction.CreateTransactionRequest.type:type_name -> transactionType.TransactionType
	11, // 11: transaction.CreateTransactionResponse.error:type_name -> error.Error
	10, // 12: transaction.UpdateTransactionRequest.dateTransaction:type_name -> google.protobuf.Timestamp
	11, // 13: transaction.UpdateTransactionResponse.error:type_name -> error.Error
	11, // 14: transaction.DeleteTransactionResponse.error:type_name -> error.Error
	1,  // 15: transaction.TransactionEndpoint.GetTransactions:input_type -> transaction.GetTransactionsRequest
	3,  // 16: transaction.TransactionEndpoint.CreateTransaction:input_type -> transaction.CreateTransactionRequest
	5,  // 17: transaction.TransactionEndpoint.UpdateTransaction:input_type -> transaction.UpdateTransactionRequest
	7,  // 18: transaction.TransactionEndpoint.DeleteTransaction:input_type -> transaction.DeleteTransactionRequest
	2,  // 19: transaction.TransactionEndpoint.GetTransactions:output_type -> transaction.GetTransactionsResponse
	4,  // 20: transaction.TransactionEndpoint.CreateTransaction:output_type -> transaction.CreateTransactionResponse
	6,  // 21: transaction.TransactionEndpoint.UpdateTransaction:output_type -> transaction.UpdateTransactionResponse
	8,  // 22: transaction.TransactionEndpoint.DeleteTransaction:output_type -> transaction.DeleteTransactionResponse
	19, // [19:23] is the sub-list for method output_type
	15, // [15:19] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_proto_transaction_transaction_endpoint_proto_init() }
func file_proto_transaction_transaction_endpoint_proto_init() {
	if File_proto_transaction_transaction_endpoint_proto != nil {
		return
	}
	file_proto_error_error_proto_init()
	file_proto_enums_transactionType_proto_init()
	file_proto_transaction_transaction_endpoint_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_transaction_transaction_endpoint_proto_msgTypes[2].OneofWrappers = []any{}
	file_proto_transaction_transaction_endpoint_proto_msgTypes[4].OneofWrappers = []any{}
	file_proto_transaction_transaction_endpoint_proto_msgTypes[5].OneofWrappers = []any{}
	file_proto_transaction_transaction_endpoint_proto_msgTypes[6].OneofWrappers = []any{}
	file_proto_transaction_transaction_endpoint_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_transaction_transaction_endpoint_proto_rawDesc), len(file_proto_transaction_transaction_endpoint_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_transaction_transaction_endpoint_proto_goTypes,
		DependencyIndexes: file_proto_transaction_transaction_endpoint_proto_depIdxs,
		MessageInfos:      file_proto_transaction_transaction_endpoint_proto_msgTypes,
	}.Build()
	File_proto_transaction_transaction_endpoint_proto = out.File
	file_proto_transaction_transaction_endpoint_proto_goTypes = nil
	file_proto_transaction_transaction_endpoint_proto_depIdxs = nil
}
