// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: proto/usersToAccountGroup/usersToAccountGroup-endpoint.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserToAccountGroup struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AccountGroupID []byte                 `protobuf:"bytes,1,opt,name=accountGroupID,proto3" json:"accountGroupID,omitempty"` // Идентификатор группы счетов
	UserID         []byte                 `protobuf:"bytes,2,opt,name=userID,proto3" json:"userID,omitempty"`                 // Идентификатор пользователя
	DatetimeCreate *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=datetimeCreate,proto3" json:"datetimeCreate,omitempty"` // Дата и время добавления участника
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserToAccountGroup) Reset() {
	*x = UserToAccountGroup{}
	mi := &file_proto_usersToAccountGroup_usersToAccountGroup_endpoint_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserToAccountGroup) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserToAccountGroup) ProtoMessage() {}

func (x *UserToAccountGroup) ProtoReflect() protoreflect.Message {
	mi := &file_proto_usersToAccountGroup_usersToAccountGroup_endpoint_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserToAccountGroup.ProtoReflect.Descriptor instead.
func (*UserToAccountGroup) Descriptor() ([]byte, []int) {
	return file_proto_usersToAccountGroup_usersToAccountGroup_endpoint_proto_rawDescGZIP(), []int{0}
}

func (x *UserToAccountGroup) GetAccountGroupID() []byte {
	if x != nil {
		return x.AccountGroupID
	}
	return nil
}

func (x *UserToAccountGroup) GetUserID() []byte {
	if x != nil {
		return x.UserID
	}
	return nil
}

func (x *UserToAccountGroup) GetDatetimeCreate() *timestamppb.Timestamp {
	if x != nil {
		return x.DatetimeCreate
	}
	return nil
}

type GetUsersToAccountGroupRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AccessToken     string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`         // Токен доступа
	AccountGroupIDs [][]byte               `protobuf:"bytes,2,rep,name=accountGroupIDs,proto3" json:"accountGroupIDs,omitempty"` // Идентификаторы групп счетов
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetUsersToAccountGroupRequest) Reset() {
	*x = GetUsersToAccountGroupRequest{}
	mi := &file_proto_usersToAccountGroup_usersToAccountGroup_endpoint_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersToAccountGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersToAccountGroupRequest) ProtoMessage() {}

func (x *GetUsersToAccountGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_usersToAccountGroup_usersToAccountGroup_endpoint_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersToAccountGroupRequest.ProtoReflect.Descriptor instead.
func (*GetUsersToAccountGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_usersToAccountGroup_usersToAccountGroup_endpoint_proto_rawDescGZIP(), []int{1}
}

func (x *GetUsersToAccountGroupRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *GetUsersToAccountGroupRequest) GetAccountGroupIDs() [][]byte {
	if x != nil {
		return x.AccountGroupIDs
	}
	return nil
}

type GetUsersToAccountGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"` // Объект ошибки
	Members       []*UserToAccountGroup  `protobuf:"bytes,2,rep,name=members,proto3" json:"members,omitempty"`   // Участники запрошенных групп
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUsersToAccountGroupResponse) Reset() {
	*x = GetUsersToAccountGroupResponse{}
	mi := &file_proto_usersToAccountGroup_usersToAccountGroup_endpoint_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUsersToAccountGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUsersToAccountGroupResponse) ProtoMessage() {}

func (x *GetUsersToAccountGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_usersToAccountGroup_usersToAccountGroup_endpoint_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUsersToAccountGroupResponse.ProtoReflect.Descriptor instead.
func (*GetUsersToAccountGroupResponse) Descriptor() ([]byte, []int) {
	return file_proto_usersToAccountGroup_usersToAccountGroup_endpoint_proto_rawDescGZIP(), []int{2}
}

func (x *GetUsersToAccountGroupResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

func (x *GetUsersToAccountGroupResponse) GetMembers() []*UserToAccountGroup {
	if x != nil {
		return x.Members
	}
	return nil
}

type AddUserToAccountGroupRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AccessToken    string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`       // Токен доступа
	AccountGroupID []byte                 `protobuf:"bytes,2,opt,name=accountGroupID,proto3" json:"accountGroupID,omitempty"` // Идентификатор группы счетов
	UserID         []byte                 `protobuf:"bytes,3,opt,name=userID,proto3" json:"userID,omitempty"`                 // Идентификатор добавляемого пользователя
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AddUserToAccountGroupRequest) Reset() {
	*x = AddUserToAccountGroupRequest{}
	mi := &file_proto_usersToAccountGroup_usersToAccountGroup_endpoint_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserToAccountGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserToAccountGroupRequest) ProtoMessage() {}

func (x *AddUserToAccountGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_usersToAccountGroup_usersToAccountGroup_endpoint_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserToAccountGroupRequest.ProtoReflect.Descriptor instead.
func (*AddUserToAccountGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_usersToAccountGroup_usersToAccountGroup_endpoint_proto_rawDescGZIP(), []int{3}
}

func (x *AddUserToAccountGroupRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *AddUserToAccountGroupRequest) GetAccountGroupID() []byte {
	if x != nil {
		return x.AccountGroupID
	}
	return nil
}

func (x *AddUserToAccountGroupRequest) GetUserID() []byte {
	if x != nil {
		return x.UserID
	}
	return nil
}

type AddUserToAccountGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"` // Объект ошибки
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddUserToAccountGroupResponse) Reset() {
	*x = AddUserToAccountGroupResponse{}
	mi := &file_proto_usersToAccountGroup_usersToAccountGroup_endpoint_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddUserToAccountGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddUserToAccountGroupResponse) ProtoMessage() {}

func (x *AddUserToAccountGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_usersToAccountGroup_usersToAccountGroup_endpoint_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddUserToAccountGroupResponse.ProtoReflect.Descriptor instead.
func (*AddUserToAccountGroupResponse) Descriptor() ([]byte, []int) {
	return file_proto_usersToAccountGroup_usersToAccountGroup_endpoint_proto_rawDescGZIP(), []int{4}
}

func (x *AddUserToAccountGroupResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type RemoveUserFromAccountGroupRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AccessToken    string                 `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`       // Токен доступа
	AccountGroupID []byte                 `protobuf:"bytes,2,opt,name=accountGroupID,proto3" json:"accountGroupID,omitempty"` // Идентификатор группы счетов
	UserID         []byte                 `protobuf:"bytes,3,opt,name=userID,proto3" json:"userID,omitempty"`                 // Идентификатор удаляемого пользователя
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RemoveUserFromAccountGroupRequest) Reset() {
	*x = RemoveUserFromAccountGroupRequest{}
	mi := &file_proto_usersToAccountGroup_usersToAccountGroup_endpoint_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUserFromAccountGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserFromAccountGroupRequest) ProtoMessage() {}

func (x *RemoveUserFromAccountGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_usersToAccountGroup_usersToAccountGroup_endpoint_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserFromAccountGroupRequest.ProtoReflect.Descriptor instead.
func (*RemoveUserFromAccountGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_usersToAccountGroup_usersToAccountGroup_endpoint_proto_rawDescGZIP(), []int{5}
}

func (x *RemoveUserFromAccountGroupRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RemoveUserFromAccountGroupRequest) GetAccountGroupID() []byte {
	if x != nil {
		return x.AccountGroupID
	}
	return nil
}

func (x *RemoveUserFromAccountGroupRequest) GetUserID() []byte {
	if x != nil {
		return x.UserID
	}
	return nil
}

type RemoveUserFromAccountGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3,oneof" json:"error,omitempty"` // Объект ошибки
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveUserFromAccountGroupResponse) Reset() {
	*x = RemoveUserFromAccountGroupResponse{}
	mi := &file_proto_usersToAccountGroup_usersToAccountGroup_endpoint_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveUserFromAccountGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveUserFromAccountGroupResponse) ProtoMessage() {}

func (x *RemoveUserFromAccountGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_usersToAccountGroup_usersToAccountGroup_endpoint_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveUserFromAccountGroupResponse.ProtoReflect.Descriptor instead.
func (*RemoveUserFromAccountGroupResponse) Descriptor() ([]byte, []int) {
	return file_proto_usersToAccountGroup_usersToAccountGroup_endpoint_proto_rawDescGZIP(), []int{6}
}

func (x *RemoveUserFromAccountGroupResponse) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

var File_proto_usersToAccountGroup_usersToAccountGroup_endpoint_proto protoreflect.FileDescriptor

const file_proto_usersToAccountGroup_usersToAccountGroup_endpoint_proto_rawDesc = "" +
	"\n" +
	"<proto/usersToAccountGroup/usersToAccountGroup-endpoint.proto\x12\x13usersToAccountGroup\x1a\x17proto/error/error.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x98\x01\n" +
	"\x12UserToAccountGroup\x12&\n" +
	"\x0eaccountGroupID\x18\x01 \x01(\fR\x0eaccountGroupID\x12\x16\n" +
	"\x06userID\x18\x02 \x01(\fR\x06userID\x12B\n" +
	"\x0edatetimeCreate\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0edatetimeCreate\"k\n" +
	"\x1dGetUsersToAccountGroupRequest\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\x12(\n" +
	"\x0faccountGroupIDs\x18\x02 \x03(\fR\x0faccountGroupIDs\"\x96\x01\n" +
	"\x1eGetUsersToAccountGroupResponse\x12'\n" +
	"\x05error\x18\x01 \x01(\v2\f.error.ErrorH\x00R\x05error\x88\x01\x01\x12A\n" +
	"\amembers\x18\x02 \x03(\v2'.usersToAccountGroup.UserToAccountGroupR\amembersB\b\n" +
	"\x06_error\"\x80\x01\n" +
	"\x1cAddUserToAccountGroupRequest\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\x12&\n" +
	"\x0eaccountGroupID\x18\x02 \x01(\fR\x0eaccountGroupID\x12\x16\n" +
	"\x06userID\x18\x03 \x01(\fR\x06userID\"R\n" +
	"\x1dAddUserToAccountGroupResponse\x12'\n" +
	"\x05error\x18\x01 \x01(\v2\f.error.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\"\x85\x01\n" +
	"!RemoveUserFromAccountGroupRequest\x12 \n" +
	"\vaccessToken\x18\x01 \x01(\tR\vaccessToken\x12&\n" +
	"\x0eaccountGroupID\x18\x02 \x01(\fR\x0eaccountGroupID\x12\x16\n" +
	"\x06userID\x18\x03 \x01(\fR\x06userID\"W\n" +
	"\"RemoveUserFromAccountGroupResponse\x12'\n" +
	"\x05error\x18\x01 \x01(\v2\f.error.ErrorH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error2\xb8\x03\n" +
	"\x1bUsersToAccountGroupEndpoint\x12\x83\x01\n" +
	"\x16GetUsersToAccountGroup\x122.usersToAccountGroup.GetUsersToAccountGroupRequest\x1a3.usersToAccountGroup.GetUsersToAccountGroupResponse\"\x00\x12\x80\x01\n" +
	"\x15AddUserToAccountGroup\x121.usersToAccountGroup.AddUserToAccountGroupRequest\x1a2.usersToAccountGroup.AddUserToAccountGroupResponse\"\x00\x12\x8f\x01\n" +
	"\x1aRemoveUserFromAccountGroup\x126.usersToAccountGroup.RemoveUserFromAccountGroupRequest\x1a7.usersToAccountGroup.RemoveUserFromAccountGroupResponse\"\x00B\bZ\x06/protob\x06proto3"

var (
	file_proto_usersToAccountGroup_usersToAccountGroup_endpoint_proto_rawDescOnce sync.Once
	file_proto_usersToAccountGroup_usersToAccountGroup_endpoint_proto_rawDescData []byte
)

func file_proto_usersToAccountGroup_usersToAccountGroup_endpoint_proto_rawDescGZIP() []byte {
	file_proto_usersToAccountGroup_usersToAccountGroup_endpoint_proto_rawDescOnce.Do(func() {
		file_proto_usersToAccountGroup_usersToAccountGroup_endpoint_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_usersToAccountGroup_usersToAccountGroup_endpoint_proto_rawDesc), len(file_proto_usersToAccountGroup_usersToAccountGroup_endpoint_proto_rawDesc)))
	})
	return file_proto_usersToAccountGroup_usersToAccountGroup_endpoint_proto_rawDescData
}

var file_proto_usersToAccountGroup_usersToAccountGroup_endpoint_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_usersToAccountGroup_usersToAccountGroup_endpoint_proto_goTypes = []any{
	(*UserToAccountGroup)(nil),                 // 0: usersToAccountGroup.UserToAccountGroup
	(*GetUsersToAccountGroupRequest)(nil),      // 1: usersToAccountGroup.GetUsersToAccountGroupRequest
	(*GetUsersToAccountGroupResponse)(nil),     // 2: usersToAccountGroup.GetUsersToAccountGroupResponse
	(*AddUserToAccountGroupRequest)(nil),       // 3: usersToAccountGroup.AddUserToAccountGroupRequest
	(*AddUserToAccountGroupResponse)(nil),      // 4: usersToAccountGroup.AddUserToAccountGroupResponse
	(*RemoveUserFromAccountGroupRequest)(nil),  // 5: usersToAccountGroup.RemoveUserFromAccountGroupRequest
	(*RemoveUserFromAccountGroupResponse)(nil), // 6: usersToAccountGroup.RemoveUserFromAccountGroupResponse
	(*timestamppb.Timestamp)(nil),              // 7: google.protobuf.Timestamp
	(*Error)(nil),                              // 8: error.Error
}
var file_proto_usersToAccountGroup_usersToAccountGroup_endpoint_proto_depIdxs = []int32{
	7, // 0: usersToAccountGroup.UserToAccountGroup.datetimeCreate:type_name -> google.protobuf.Timestamp
	8, // 1: usersToAccountGroup.GetUsersToAccountGroupResponse.error:type_name -> error.Error
	0, // 2: usersToAccountGroup.GetUsersToAccountGroupResponse.members:type_name -> usersToAccountGroup.UserToAccountGroup
	8, // 3: usersToAccountGroup.AddUserToAccountGroupResponse.error:type_name -> error.Error
	8, // 4: usersToAccountGroup.RemoveUserFromAccountGroupResponse.error:type_name -> error.Error
	1, // 5: usersToAccountGroup.UsersToAccountGroupEndpoint.GetUsersToAccountGroup:input_type -> usersToAccountGroup.GetUsersToAccountGroupRequest
	3, // 6: usersToAccountGroup.UsersToAccountGroupEndpoint.AddUserToAccountGroup:input_type -> usersToAccountGroup.AddUserToAccountGroupRequest
	5, // 7: usersToAccountGroup.UsersToAccountGroupEndpoint.RemoveUserFromAccountGroup:input_type -> usersToAccountGroup.RemoveUserFromAccountGroupRequest
	2, // 8: usersToAccountGroup.UsersToAccountGroupEndpoint.GetUsersToAccountGroup:output_type -> usersToAccountGroup.GetUsersToAccountGroupResponse
	4, // 9: usersToAccountGroup.UsersToAccountGroupEndpoint.AddUserToAccountGroup:output_type -> usersToAccountGroup.AddUserToAccountGroupResponse
	6, // 10: usersToAccountGroup.UsersToAccountGroupEndpoint.RemoveUserFromAccountGroup:output_type -> usersToAccountGroup.RemoveUserFromAccountGroupResponse
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_usersToAccountGroup_usersToAccountGroup_endpoint_proto_init() }
func file_proto_usersToAccountGroup_usersToAccountGroup_endpoint_proto_init() {
	if File_proto_usersToAccountGroup_usersToAccountGroup_endpoint_proto != nil {
		return
	}
	file_proto_error_error_proto_init()
	file_proto_usersToAccountGroup_usersToAccountGroup_endpoint_proto_msgTypes[2].OneofWrappers = []any{}
	file_proto_usersToAccountGroup_usersToAccountGroup_endpoint_proto_msgTypes[4].OneofWrappers = []any{}
	file_proto_usersToAccountGroup_usersToAccountGroup_endpoint_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_usersToAccountGroup_usersToAccountGroup_endpoint_proto_rawDesc), len(file_proto_usersToAccountGroup_usersToAccountGroup_endpoint_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_usersToAccountGroup_usersToAccountGroup_endpoint_proto_goTypes,
		DependencyIndexes: file_proto_usersToAccountGroup_usersToAccountGroup_endpoint_proto_depIdxs,
		MessageInfos:      file_proto_usersToAccountGroup_usersToAccountGroup_endpoint_proto_msgTypes,
	}.Build()
	File_proto_usersToAccountGroup_usersToAccountGroup_endpoint_proto = out.File
	file_proto_usersToAccountGroup_usersToAccountGroup_endpoint_proto_goTypes = nil
	file_proto_usersToAccountGroup_usersToAccountGroup_endpoint_proto_depIdxs = nil
}
