// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/usersToAccountGroup/usersToAccountGroup-endpoint.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UsersToAccountGroupEndpoint_GetUsersToAccountGroup_FullMethodName     = "/usersToAccountGroup.UsersToAccountGroupEndpoint/GetUsersToAccountGroup"
	UsersToAccountGroupEndpoint_AddUserToAccountGroup_FullMethodName      = "/usersToAccountGroup.UsersToAccountGroupEndpoint/AddUserToAccountGroup"
	UsersToAccountGroupEndpoint_RemoveUserFromAccountGroup_FullMethodName = "/usersToAccountGroup.UsersToAccountGroupEndpoint/RemoveUserFromAccountGroup"
)

// UsersToAccountGroupEndpointClient is the client API for UsersToAccountGroupEndpoint service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Связь "пользователь состоит в группе счетов" — отдельная сущность/модуль, не часть
// accountGroup: используется как единственная точка правды для видимости и прав доступа во всех
// местах, где данные пересекают границу одного пользователя (счета-мосты и pendingLinkedTransfer,
// в перспективе — любой другой шаринг данных между людьми).
type UsersToAccountGroupEndpointClient interface {
	// GetUsersToAccountGroup возвращает участников группы счетов — источник кандидатов для
	// линковки счёта-моста (account.UpdateAccountRequest.linkedAccountID) и точка проверки
	// видимости pendingLinkedTransfer на бэкенде.
	GetUsersToAccountGroup(ctx context.Context, in *GetUsersToAccountGroupRequest, opts ...grpc.CallOption) (*GetUsersToAccountGroupResponse, error)
	// AddUserToAccountGroup добавляет пользователя в группу счетов. Кто именно может это вызывать
	// (только существующий участник?) и нужен ли отдельный флоу приглашения/подтверждения —
	// определяется бэкендом, контракт этого не ограничивает.
	AddUserToAccountGroup(ctx context.Context, in *AddUserToAccountGroupRequest, opts ...grpc.CallOption) (*AddUserToAccountGroupResponse, error)
	// RemoveUserFromAccountGroup убирает пользователя из группы счетов (выход самого пользователя,
	// либо удаление другим участником — авторизация на бэкенде).
	RemoveUserFromAccountGroup(ctx context.Context, in *RemoveUserFromAccountGroupRequest, opts ...grpc.CallOption) (*RemoveUserFromAccountGroupResponse, error)
}

type usersToAccountGroupEndpointClient struct {
	cc grpc.ClientConnInterface
}

func NewUsersToAccountGroupEndpointClient(cc grpc.ClientConnInterface) UsersToAccountGroupEndpointClient {
	return &usersToAccountGroupEndpointClient{cc}
}

func (c *usersToAccountGroupEndpointClient) GetUsersToAccountGroup(ctx context.Context, in *GetUsersToAccountGroupRequest, opts ...grpc.CallOption) (*GetUsersToAccountGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUsersToAccountGroupResponse)
	err := c.cc.Invoke(ctx, UsersToAccountGroupEndpoint_GetUsersToAccountGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersToAccountGroupEndpointClient) AddUserToAccountGroup(ctx context.Context, in *AddUserToAccountGroupRequest, opts ...grpc.CallOption) (*AddUserToAccountGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddUserToAccountGroupResponse)
	err := c.cc.Invoke(ctx, UsersToAccountGroupEndpoint_AddUserToAccountGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersToAccountGroupEndpointClient) RemoveUserFromAccountGroup(ctx context.Context, in *RemoveUserFromAccountGroupRequest, opts ...grpc.CallOption) (*RemoveUserFromAccountGroupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveUserFromAccountGroupResponse)
	err := c.cc.Invoke(ctx, UsersToAccountGroupEndpoint_RemoveUserFromAccountGroup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsersToAccountGroupEndpointServer is the server API for UsersToAccountGroupEndpoint service.
// All implementations must embed UnimplementedUsersToAccountGroupEndpointServer
// for forward compatibility.
//
// Связь "пользователь состоит в группе счетов" — отдельная сущность/модуль, не часть
// accountGroup: используется как единственная точка правды для видимости и прав доступа во всех
// местах, где данные пересекают границу одного пользователя (счета-мосты и pendingLinkedTransfer,
// в перспективе — любой другой шаринг данных между людьми).
type UsersToAccountGroupEndpointServer interface {
	// GetUsersToAccountGroup возвращает участников группы счетов — источник кандидатов для
	// линковки счёта-моста (account.UpdateAccountRequest.linkedAccountID) и точка проверки
	// видимости pendingLinkedTransfer на бэкенде.
	GetUsersToAccountGroup(context.Context, *GetUsersToAccountGroupRequest) (*GetUsersToAccountGroupResponse, error)
	// AddUserToAccountGroup добавляет пользователя в группу счетов. Кто именно может это вызывать
	// (только существующий участник?) и нужен ли отдельный флоу приглашения/подтверждения —
	// определяется бэкендом, контракт этого не ограничивает.
	AddUserToAccountGroup(context.Context, *AddUserToAccountGroupRequest) (*AddUserToAccountGroupResponse, error)
	// RemoveUserFromAccountGroup убирает пользователя из группы счетов (выход самого пользователя,
	// либо удаление другим участником — авторизация на бэкенде).
	RemoveUserFromAccountGroup(context.Context, *RemoveUserFromAccountGroupRequest) (*RemoveUserFromAccountGroupResponse, error)
	mustEmbedUnimplementedUsersToAccountGroupEndpointServer()
}

// UnimplementedUsersToAccountGroupEndpointServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUsersToAccountGroupEndpointServer struct{}

func (UnimplementedUsersToAccountGroupEndpointServer) GetUsersToAccountGroup(context.Context, *GetUsersToAccountGroupRequest) (*GetUsersToAccountGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUsersToAccountGroup not implemented")
}
func (UnimplementedUsersToAccountGroupEndpointServer) AddUserToAccountGroup(context.Context, *AddUserToAccountGroupRequest) (*AddUserToAccountGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddUserToAccountGroup not implemented")
}
func (UnimplementedUsersToAccountGroupEndpointServer) RemoveUserFromAccountGroup(context.Context, *RemoveUserFromAccountGroupRequest) (*RemoveUserFromAccountGroupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveUserFromAccountGroup not implemented")
}
func (UnimplementedUsersToAccountGroupEndpointServer) mustEmbedUnimplementedUsersToAccountGroupEndpointServer() {
}
func (UnimplementedUsersToAccountGroupEndpointServer) testEmbeddedByValue() {}

// UnsafeUsersToAccountGroupEndpointServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UsersToAccountGroupEndpointServer will
// result in compilation errors.
type UnsafeUsersToAccountGroupEndpointServer interface {
	mustEmbedUnimplementedUsersToAccountGroupEndpointServer()
}

func RegisterUsersToAccountGroupEndpointServer(s grpc.ServiceRegistrar, srv UsersToAccountGroupEndpointServer) {
	// If the following call panics, it indicates UnimplementedUsersToAccountGroupEndpointServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UsersToAccountGroupEndpoint_ServiceDesc, srv)
}

func _UsersToAccountGroupEndpoint_GetUsersToAccountGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUsersToAccountGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersToAccountGroupEndpointServer).GetUsersToAccountGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsersToAccountGroupEndpoint_GetUsersToAccountGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersToAccountGroupEndpointServer).GetUsersToAccountGroup(ctx, req.(*GetUsersToAccountGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersToAccountGroupEndpoint_AddUserToAccountGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddUserToAccountGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersToAccountGroupEndpointServer).AddUserToAccountGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsersToAccountGroupEndpoint_AddUserToAccountGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersToAccountGroupEndpointServer).AddUserToAccountGroup(ctx, req.(*AddUserToAccountGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersToAccountGroupEndpoint_RemoveUserFromAccountGroup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveUserFromAccountGroupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersToAccountGroupEndpointServer).RemoveUserFromAccountGroup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UsersToAccountGroupEndpoint_RemoveUserFromAccountGroup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersToAccountGroupEndpointServer).RemoveUserFromAccountGroup(ctx, req.(*RemoveUserFromAccountGroupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UsersToAccountGroupEndpoint_ServiceDesc is the grpc.ServiceDesc for UsersToAccountGroupEndpoint service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UsersToAccountGroupEndpoint_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "usersToAccountGroup.UsersToAccountGroupEndpoint",
	HandlerType: (*UsersToAccountGroupEndpointServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetUsersToAccountGroup",
			Handler:    _UsersToAccountGroupEndpoint_GetUsersToAccountGroup_Handler,
		},
		{
			MethodName: "AddUserToAccountGroup",
			Handler:    _UsersToAccountGroupEndpoint_AddUserToAccountGroup_Handler,
		},
		{
			MethodName: "RemoveUserFromAccountGroup",
			Handler:    _UsersToAccountGroupEndpoint_RemoveUserFromAccountGroup_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/usersToAccountGroup/usersToAccountGroup-endpoint.proto",
}
